### ISSUE TITLE
Ark configuration should support multiple AZs for PersistentVolumeProvider

### ISSUE THREAD

**Issue by ashish-amarnath** [heptio/ark#101]
Ark configuration only supports a single availability zone for a persistent volume snapshot.
Even though the underlying AWS API, to create volume snapshots, seems to support multiple AZs
This is the code snippet, from the block_storage_adaptor, that I am referring to.

`azReq     = &ec2.DescribeAvailabilityZonesInput{ZoneNames: []*string{&availabilityZone}}`

**Comment by ashish-amarnath** [comment]
The fix for this shouldn't require invasive change. The fix will involve:
1. Using the `AvailabilityZone` field of `AWSConfig` struct to be `[]string` instead of `string` or use comma separated values for AZs. Using comma separated values would be a better option here as it will not change the JSON schema of the configuration object.
2. Converting the CSV string to `[]string` in `NewBlockStorageAdapter` while validating the availability zones 

Other ideas/suggestions?

**Comment by ashish-amarnath** [comment]
IMO, `CreateVolumeFromSnapshot` will also have to be updated to create the volume back into the correct AZ.

**Comment by jrnt30** [comment]
First, thanks for bringing this up.  I recall looking at this and being a bit confused when I first looked at Ark and it has fallen off my radar. 

I'm curious, would it be more appropriate to simply remove the `AvailabilityZone` attribute from `AWSConfig` all together?  I think philosophically, I tend to think "Regionally" for AWS and not AZ specific.  Looking at your code changes, it seems that we end up driving a majority of the work from the vol's AZ anyways and ignore the `AWSConfig` outside of the AZ validation that first occurs. 

I personally think it would be a bit more robust to remove the AZ validation and simply "trust" what comes off of the AZs themselves.  What do you think?

**Comment by ashish-amarnath** [comment]
Let me 'double click' and verify that the availability zone can be removed without increasing the surface area of this change.
I agree that removing the availability zone would be ideal. The change that I currently have in the PR may add to fragility.

**Comment by adiletmaratov** [comment]
The same problem on GCP. When I got a gcloud disk, which is in a different zone, it just says `not found` instead of looking for all available zones in that cluster

**Comment by skriss** [comment]
Fixed by #102 

cc @adiletmaratov
