### ISSUE TITLE
Modify backup/Action interface

### ISSUE THREAD

**Issue by skriss** [heptio/ark#105]
Per https://github.com/heptio/ark/pull/54#issuecomment-324368048, it would be nice to update the Action interface.

@ncdc now that I'm looking again at what you were proposing I realized it's not what I originally thought it was. Should we just include the Backup as a field on the ActionContext, and keep allowing the Actions to modify it as necessary? Since we're not going to use an Options struct, I don't see any major issue with this.

**Comment by ncdc** [comment]
Yes, I think putting the backup on the ActionContext makes sense.

**Comment by skriss** [comment]
will address this as part of #65 since the interface will be changing for that
