### ISSUE TITLE
Add brew cask to install cli?

### ISSUE THREAD

**Issue by omerlh** [heptio/ark#1051]
[Brew](https://brew.sh/) is used to installing various utilities on macos, it will be nice to use it to install the CLI.

**Comment by wiegandf** [comment]
https://formulae.brew.sh/formula/ark

**Comment by ncdc** [comment]
Thanks @wiegandf for pointing out the existing formula.

@skriss we might want to submit a PR against the brew formula for ark to add the yaml.

**Comment by omerlh** [comment]
Thanks! I can confirm it's working. Added a quick note to the docs - what do you think?
