### ISSUE TITLE
Allow Ark server to run in arbitrary namespaces

### ISSUE THREAD

**Issue by SleepyBrett** [heptio/ark#106]
Currently the Ark server component assumes that it's configuration is stored in api.DefaultNamespace (heptio-ark) with no way to override. As cluster admins we put these kind of tools into a 'utils' namespace and would like to do the same for Ark.

The server component should probably assume it's configuration is stored in the namespace it's deployed in. The client would need to support a namespace flag or configuration or both.

**Comment by ncdc** [comment]
To do this, we should
1. Use the in-cluster namespace for the ark server
1. Add `--namespace`/`-n` to the ark CLI
1. Optionally have `~/.arkconfig` or `~/.config/ark` as a means to set the default namespace so you don't have to type `--namespace` all the time

**Comment by woop** [comment]
@ncdc Can I work on a PR for (1) and (2)?

**Comment by ncdc** [comment]
Definitely, thanks!

**Comment by ncdc** [comment]
If there’s anything that you think needs discussion before coding, feel
free to raise that here first.

**Comment by ncdc** [comment]
@SleepyBrett @woop just checking in - are either of you working on this? Thanks!

**Comment by woop** [comment]
@ncdc I'm not actively working on this. Bit short on time. I'll swing back when I have more free time.

**Comment by ashish-amarnath** [comment]
I can try to get this done.
My approach, for the server, was to inject the namespace into the server as an environment and read the environment variable, if it exists, else use the default namespace. @ncdc Can you elaborate on 

> Use the in-cluster namespace for the ark server
Is this an option for one of the kubernetes APIs?

**Comment by ashish-amarnath** [comment]
My approach, for the server, was to inject the namespace into the server as an environment and read the environment variable, if it exists, else use the default namespace. @ncdc Can you elaborate on 

> Use the in-cluster namespace for the ark server
Is this an option for one of the kubernetes APIs?

**Comment by ashish-amarnath** [comment]
My approach, for the server, was to inject the namespace into the server as an environment and read the environment variable, if it exists, else use the default namespace. @ncdc Can you elaborate on 

> Use the in-cluster namespace for the ark server
Is this an option for one of the kubernetes APIs?

**Comment by ashish-amarnath** [comment]
My approach, for the server, was to inject the namespace into the server as an environment and read the environment variable, if it exists, else use the default namespace. @ncdc Can you elaborate on "Use the in-cluster namespace for the ark server"
Is this an option for one of the kubernetes APIs? Not too familiar with using the k8s APIs.

**Comment by ashish-amarnath** [comment]
My approach, for the server, was to inject the namespace into the server as an environment and read the environment variable, if it exists, else use the default namespace. @ncdc Can you elaborate on "Use the in-cluster namespace for the ark server"
Is this an option for one of the kubernetes APIs? Not too familiar with using the k8s APIs.

**Comment by ashish-amarnath** [comment]
My approach, for the server, was to inject the namespace into the server as an environment and read the environment variable, if it exists, else use the default namespace. @ncdc Can you elaborate on "Use the in-cluster namespace for the ark server"
Is this an option for one of the kubernetes APIs? Not too familiar with using the k8s APIs.

**Comment by ncdc** [comment]
@ashish-amarnath yes, it's part of client-go. Let me see if I can dig up the exact code you'll need.

**Comment by ncdc** [comment]
@ashish-amarnath in pkg/client/client.go, replace the call to `clientcmd.BuildConfigFromKubeconfigGetter` with this:
```go
clientConfig := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(
  loader,
  &clientcmd.ConfigOverrides{},
)
```

That gives you a `clientcmd.ClientConfig`, upon which you can invoke `Namespace()`, and that will return the pod's namespace if you're running it in a Kubernetes cluster. You'll probably need to tweak it so that there's a `ClientConfig()` function that returns the `clientcmd.ClientConfig`, and then the current `Config()` function can just call that, and then return the `*rest.Config` as it currently does. Or something like that...
