### ISSUE TITLE
Unexpected behaviour of ark while taking backup.

### ISSUE THREAD

**Issue by sachinar** [heptio/ark#1070]
Hi Team,
@ncdc We are taking backup of kubernetes deployments here what we observed.

1. Firstly we have taken data & deployment backup, in deployment data is about 100 MB,it almost taken 1 Minute for backup to complete.
2. We tried with different setup with same deployment & same data, Now backup taken almost 24 Hours to complete.
 We are unable to find why this happening , even in logs also there is no error.
This is happening with every deployment where we are using ark tool to take backup.

**Comment by ncdc** [comment]
@sachinar 

1. Where are you running Kubernetes?
1. What version of Ark?
1. Are you saying you have 100MB of data in a persistent volume?

(in the future, please use our issue template - thanks!)

**Comment by sachinar** [comment]
@ncdc 
1. We are using VMware for kubernetes These are on-prem clusters.
2. We are using v0.10.0 version & we previously using v0.9.1 
3. Yes.

**Comment by ncdc** [comment]
What storage provider are you using?

**Comment by sachinar** [comment]
We are using node storage for backup & for PV also we are using local storage.
We are not using NFS or any storage provider for PV. We are storing PV volume data on node itself.

**Comment by ncdc** [comment]
Could you please share `ark backup-location get -o yaml` and `ark snapshot-location get -o yaml`?

**Comment by sachinar** [comment]
Hi @ncdc ,
kindly find output.
`ark backup-location get -o yaml`
> apiVersion: ark.heptio.com/v1
kind: BackupStorageLocation
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"ark.heptio.com/v1","kind":"BackupStorageLocation","metadata":{"annotations":{},"name":"default","namespace":"heptio-ark"},"spec":{"config":{"region":"minio","s3ForcePathStyle":"true","s3Url":"http://172.16.23.31:31356"},"objectStorage":{"bucket":"ark"},"provider":"aws"}}
  creationTimestamp: 2018-11-20T17:11:51Z
  generation: 1
  name: default
  namespace: heptio-ark
  resourceVersion: "12002883"
  selfLink: /apis/ark.heptio.com/v1/namespaces/heptio-ark/backupstoragelocations/default
  uid: 5f701601-ece7-11e8-a87c-005056bef59d
spec:
  config:
    region: minio
    s3ForcePathStyle: "true"
    s3Url: http://172.16.23.31:31356
  objectStorage:
    bucket: ark
    prefix: ""
  provider: aws
status:
  lastSyncedTime: null

`ark snapshot-location get -o yaml`

> apiVersion: ark.heptio.com/v1
items: []
kind: VolumeSnapshotLocationList
metadata:
  resourceVersion: "12003681"
  selfLink: /apis/ark.heptio.com/v1/namespaces/heptio-ark/volumesnapshotlocations

**Comment by ncdc** [comment]
Ok, unless I'm missing something, it doesn't look like you are configured to take snapshots of your persistent volumes.

Could you please paste the output of `ark backup get -o yaml`?

**Comment by sachinar** [comment]
`ark backup get -o yaml`

apiVersion: ark.heptio.com/v1
items: []
kind: BackupList
metadata:
  resourceVersion: "12005579"
  selfLink: /apis/ark.heptio.com/v1/namespaces/heptio-ark/backups

**Comment by ncdc** [comment]
I'm confused - you have 0 backups?

**Comment by sachinar** [comment]
currently we don't have backup on this setup.

**Comment by ncdc** [comment]
Could you please run these commands against whatever cluster is being "slow"?

**Comment by sachinar** [comment]
yeah will update u the same.
 @ncdc Thanks in advance.

**Comment by ncdc** [comment]
That backup hasn't been processed (its status.phase is empty). Could you please check `kubectl -n heptio-ark get pod` and `kubectl -n heptio-ark logs deploy/ark`?

**Comment by sachinar** [comment]
@ncdc 

This is what happening when we are taking backup.

`time="2018-11-22T10:10:53Z" level=info msg="Retrieved 0 items" backup=heptio-ark/mongo-backup group=extensions/v1beta1 groupResource=podsecuritypolicies.extensions logSource="pkg/backup/resource_backupper.go:243" namespace=
time="2018-11-22T10:10:53Z" level=info msg="Backup completed with errors: [timed out waiting for all PodVolumeBackups to complete, timed out waiting for all PodVolumeBackups to complete, timed out waiting for all PodVolumeBackups to complete]" backup=heptio-ark/mongo-backup logSource="pkg/backup/backup.go:289"`


As we already added timeout in `05-ark-backupstoragelocation.yaml`

`backupSyncPeriod: 30m`
`gcSyncPeriod: 30m`
`scheduleSyncPeriod: 1m`
`restoreOnlyMode: false`

`# This part is what was added`
`podVolumeOperationTimeout: 24h`

**Comment by ncdc** [comment]
@sachinar not sure if you still have the logs, but if you do, could you please grab them from the ark restic pod(s) on your node(s)?

**Comment by sachinar** [comment]
@ncdc If I have data of 90GB. How much time ark will take to backed up the data? 

We are really confused about ark behaviour. Because we have 90 GB of data in 4 different pods with  statefulset. We have started backup around 5 hours backup but still it is in in-progress state.

`ark backup describe ignite-backup --details `

> Name:         ignite-backup
Namespace:    heptio-ark
Labels:       ark.heptio.com/storage-location=default
Annotations:  <none>

Phase:  InProgress

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  app=infra-distributed-db

Storage Location:  default

Snapshot PVs:  true

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    <n/a>
Completed:  <n/a>

Expiration:  2019-01-03 01:20:15 -0500 EST

Validation errors:  <none>

Persistent Volumes: <none included>

Restic Backups:
  New:
    default/infra-distributed-db-0: ignite-logs, ignite-work




`ark get backup`

> ignite-backup   InProgress   0001-01-01 00:00:00 +0000 UTC   29d       default            app=infra-distributed-db
sftp-backup     Completed    2018-12-04 01:17:40 -0500 EST   29d       default            app=infra-sftp

`date`

> Tue Dec  4 07:27:36 EST 2018

`ark backup-location get -o yaml`

> apiVersion: ark.heptio.com/v1
kind: BackupStorageLocation
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"ark.heptio.com/v1","kind":"BackupStorageLocation","metadata":{"annotations":{},"name":"default","namespace":"heptio-ark"},"spec":{"config":{"region":"minio","s3ForcePathStyle":"true","s3Url":"http://minio.heptio-ark.svc:9000"},"objectStorage":{"bucket":"ark"},"provider":"aws"}}
  creationTimestamp: 2018-12-04T06:10:50Z
  generation: 1
  name: default
  namespace: heptio-ark
  resourceVersion: "1284654"
  selfLink: /apis/ark.heptio.com/v1/namespaces/heptio-ark/backupstoragelocations/default
  uid: 595b4b46-f78b-11e8-99f8-005056884c3e
spec:
  config:
    region: minio
    s3ForcePathStyle: "true"
    s3Url: http://10.101.84.30:9000
  objectStorage:
    bucket: ark
    prefix: ""
  provider: aws
status:
  lastSyncedRevision: d956b052-9a22-4ef0-8004-ac3b2b9cb8de
  lastSyncedTime: 2018-12-04T12:20:18Z

`ark snapshot-location get -o yaml`


> apiVersion: ark.heptio.com/v1
items: []
kind: VolumeSnapshotLocationList
metadata:
  resourceVersion: "1286820"
  selfLink: /apis/ark.heptio.com/v1/namespaces/heptio-ark/volumesnapshotlocations

**Comment by ncdc** [comment]
@sachinar I saw you chatted on Slack with @skriss - were you able to resolve this?

**Comment by sachinar** [comment]
@ncdc  yep but need to check It is resolved or not.
I will get you posted on this.

**Comment by sachinar** [comment]
@ncdc I think this issue is resolved I just saw. Backup is going on. If any help I will post in Slack channel.

**Comment by ncdc** [comment]
Thanks, I'll close for now.

**Comment by mgunter-pivotal** [comment]
@sachinar - what did you find out above. (I am going to go to slack and see if I can see the convo there.)
thx
