### ISSUE TITLE
Manual S3 copies not showing up in Ark

### ISSUE THREAD

**Issue by jaygorrell** [heptio/ark#1071]
**What steps did you take and what happened:**
1. Take a backup with ark
2. Replicate it to the backup s3 bucket of another cluster
3. Ark does not see the backup with `ark get backups`

This can be simplified with one cluster to get the same result:
1. Take a backup with ark
2. Copy the backup somewhere else
3. Remove the backup using the ark cli
4. Manually put the same backup files back where they were
5. Ark does not see the backup with `ark get backups`

**What did you expect to happen:**
Based on the documentation, it sounds like Ark should be scanning S3 as the source of truth in this scenario, making manually placed (or s3 replicated) backups appear to the ark cli. Is that wrong?

**The output of the following commands will help us better understand what's going on**:
* `kubectl logs deployment/ark -n heptio-ark
I do see lots of:
```
time="2018-11-20T13:58:28Z" level=error msg="Error in syncHandler, re-adding item to queue" controller=downloadrequest error="backup.ark.heptio.com \"mybackup\" not found" error.file="download_request_controller.go:166" error.function="(*downloadRequestController).generatePreSignedURL" key=heptio-ark/mybackup-20181120085300 logSource="pkg/controller/generic_controller.go:137"
```

**Environment:**

- Ark version (use `ark version`):  0.10.0
- Kubernetes version (use `kubectl version`): 1.10.5
- Kubernetes installer & version: kops 1.10
- Cloud provider or hardware configuration: AWS

**Comment by ncdc** [comment]
@jaygorrell This should be working. The ark server syncs the list of backups from object storage to kubernetes every minute. Is it possible you didn't wait long enough? Could you please gist or attach the full ark server log?

**Comment by jaygorrell** [comment]
I'm running the test again now:
10:17 - Uploaded backup to S3 manually
10:48 - Decided to use ark to manually take a different (larger) snapshot
10:48 - New snapshot was in ark cli, but not the existing one
10:51 - New snapshot finished and ark cli showed the manual one

There's a lot of noise in my logs from testing but I'll try again with a fresh pod if it'd be helpful. I can try to do the manual snapshot earlier (after 5 minutes or so) to see if that's really what made it show up.

**Comment by skriss** [comment]
@jaygorrell when you're moving backups around, are you including the `ark-backup.json` file, or only the tarball? The former is needed for Ark to be able to pick up the backup from S3

**Comment by jaygorrell** [comment]
I'm including the whole folder

**Comment by skriss** [comment]
Gotcha. So I think what's going on here is -- Ark doesn't expect users to be modifying the contents of its bucket behind the scenes.  It uses a file, `metadata/revision`, to track whether any changes have been made to the object storage bucket since the last time it synced, and it updates this file every time it creates/deletes a backup.  If there's no change to that file and it hasn't been >1 hour since the last sync, it assumes nothing has changed and won't sync backups in.

In the case where you took a new backup, Ark updated the `metadata/revision` file, so the sync process ran within a minute or so after.

So - if you want to manually move things around, you can probably manually delete the `metadata/revision` file in the bucket where you're moving backups to, which will lead Ark to re-sync soon after.

**Comment by jaygorrell** [comment]
I had another test going and just deleted that file, which worked as you described. 

So in my scenario I wanted to have s3 bucket replication sending things to another region (hence my test). As long as the revision file is being replicated, I should be okay then... right? The other region cluster would see the revision changed and perform a sync.

I'm fine if this is closed if that's working as designed... I can definitely make it work for my use-case. Thanks for the very quick responses!

**Comment by skriss** [comment]
Yep - that sounds right.  Also, just so you know - we do have plans to implement native cross-region backup replication, as well as to improve the experience of sharing backups across clusters.  So don't take the current state of functionality in these areas as the desired state, it's just where we've been able to get so far.  Stay tuned!
