### ISSUE TITLE
Getting started documentation link 404s on master

### ISSUE THREAD

**Issue by acbramley** [heptio/ark#1073]
**What steps did you take and what happened:**
Go to https://heptio.github.io/ark/master/ and click the Getting started link in the left hand nav.

Page 404s https://heptio.github.io/ark/master/get-started

**What did you expect to happen:**

Page displays.

**Comment by skriss** [comment]
thanks for the report @acbramley

**Comment by skriss** [comment]
This was actually resolved by #1121, while #1126 remains unresolved.
