### ISSUE TITLE
Documentation page missed or referred wrongly

### ISSUE THREAD

**Issue by dfad1ripe** [heptio/ark#1075]
**What steps did you take and what happened:**
On https://heptio.github.io/ark/v0.10.0/azure-config documentation page, there is a phrase under "Credentials and configuration" section that says:
"Replace <YOUR_TIMEOUT>. See the VolumeSnapshotLocation definition for details."
Here, words "VolumeSnapshotLocation definition" are a link to "https://heptio.github.io/docs/api-types/volumesnapshotlocation.md#azure" page that is missed (returns error 404).

**What did you expect to happen:**
Actual documentation page

**Anything else you would like to add:**
Short investigation shows that there is "https://heptio.github.io/ark/v0.10.0/api-types/volumesnapshotlocation.md" page that might be the one to be referred instead.

**Comment by skriss** [comment]
Closed by #1143
