### ISSUE TITLE
Cannot migrate k8s objects to a new cluster on Azure

### ISSUE THREAD

**Issue by moepot** [heptio/ark#1080]
**What steps did you take and what happened:**
We are running a kubernetes cluster on Azure (using AKS Azure Kubernetes Service). We have to create a new cluster and migrate all objects including PV from the old to the new cluster.

Heptio Ark docs says that this is possible:
https://github.com/heptio/ark/blob/master/docs/migration-case.md

These names are replaced by generic names:

Old cluster name: cluster-old
Old cluster resource group: rmg-old

New cluster name: cluster-new
New cluster resource group: rmg-new

I tested the case by creating a test deployment inside a new namespace called "nginx-example", see:
https://gist.github.com/moepot/a3827ba662f0c45b73efc283139b6599

Then, I created a backup on the old cluster:
`ark create backup migration-test-2 --include-namespaces nginx-example`

I waited until the backup showed as *completed*.

On the new cluster, I deployed Heptio Ark with `--restore-only` option using the exact same resources configuration. The only thing I adjusted was the `cloud-credentials` secrets, where I updated the value for `AZURE_RESOURCE_GROUP`. Reason for this is because AKS automatically creates a new resource group for each kubernetes cluster. The docs says this value must be set to the according k8s cluster.

On the new cluster, I tested with `ark get backups` that the backup was available, which was the case.

On the new cluster, I started a restore:
`ark restore create --from-backup migration-test-2`

I waited until `ark get restores` showed *completed*. From ark point of view, everything looked fine. When I was checking the pod, it showed me these errors:

```
AttachVolume.Attach failed for volume "pvc-9c7ea14e-f187-11e8-bf3a-0a58ac1f039a" : Attach volume "restore-8b42499a-3557-4525-abce-966cdf1145a0" to instance "/subscriptions/my-subscription/resourceGroups/rmg-new/providers/Microsoft.Compute/virtualMachines/aks-agentpool-41264722-5" failed with compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client 'ac6102d4-34fa-4a3e-82bc-1c49138dd07f' with object id 'ac6102d4-34fa-4a3e-82bc-1c49138dd07f' has permission to perform action 'Microsoft.Compute/virtualMachines/write' on scope '/subscriptions/my-subscription/resourceGroups/rmg-new/providers/Microsoft.Compute/virtualMachines/aks-agentpool-41264722-5'; however, it does not have permission to perform action 'write' on the linked scope(s) '/subscriptions/my-subscription/resourceGroups/rmg-old/providers/Microsoft.Compute/disks/restore-8b42499a-3557-4525-abce-966cdf1145a0'."
```

I checked Azure Portal and I noticed that it successfully created a new disk:
`restore-8b42499a-3557-4525-abce-966cdf1145a0`

The disk was created in the old resource group `rmg-old`. Kubernetes tried to attach the disk in `rmg-old` on an k8s agent in resoure group `rmg-new`, which was not possible because of permission violations.

**What did you expect to happen:**

The new vDisk `restore-8b42499a-3557-4525-abce-966cdf1145a0` which was restored from the snapshot should have been created in the resource group `rmg-new`.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
https://gist.github.com/moepot/57192bd9a84b1fc71810d5fc9d98d460

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Ark version (use `ark version`):  0.10.0
- Kubernetes version (use `kubectl version`): v1.11.4
- Kubernetes installer & version: 
- Cloud provider or hardware configuration: Azure Kubernetes Service
- OS (e.g. from `/etc/os-release`): macOS Mojave

**Comment by ncdc** [comment]
@moepot I just double-checked the code, and Ark uses the `AZURE_RESOURCE_GROUP` value from the `cloud-credentials` secret when asking Azure to create a new disk. For reference, it's this call: https://docs.microsoft.com/en-us/rest/api/compute/disks/createorupdate.

Is there any chance you modified the `AZURE_RESOURCE_GROUP` value in your secret **after** you installed Ark in the `rmg-new` cluster?

**Comment by moepot** [comment]
Hi @ncdc 

> Is there any chance you modified the AZURE_RESOURCE_GROUP value in your secret after you installed Ark in the rmg-new cluster?

Yes. I realized later that I had to modify the value, so I modified it after the ark installation. As I type this, I realize that I possibly have to kill the ark controller? ...

**Comment by ncdc** [comment]
@moepot yes, the Ark server does not watch the secret to see if anything changed. You have to manually restart the Ark server pod (either by deleting it, or by scaling the Ark deployment down to 0 and then back up to 1).

**Comment by moepot** [comment]
Thank you @ncdc.
I deleted the ark pod and created a new backup and restore `migration-test-4`.

Now I get a WARNING in the restore object:


```
ark describe restore migration-test-4-20181126171315
Name:         migration-test-4-20181126171315
Namespace:    heptio-ark
Labels:       <none>
Annotations:  <none>

Backup:  migration-test-4

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.ark.heptio.com, restores.ark.heptio.com
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto

Phase:  Completed

Validation errors:  <none>

Warnings:
  Ark:        <none>
  Cluster:  not restored: persistentvolumes "pvc-c7244f27-f192-11e8-bf3a-0a58ac1f039a" already exists and is different from backed up version.
  Namespaces: <none>

Errors:
  Ark:        <none>
  Cluster:    <none>
  Namespaces: <none>
```

**Comment by ncdc** [comment]
You would have needed to delete some or all of the objects created from your first restore attempt in the new cluster; in this case, specifically the PV and probably the PVC too.

**Comment by moepot** [comment]
Thank you very much! It worked now. Should I send a PR to clarify the migration-case.md ? I'd add another point like 

> Cluster 1: Make sure to remove all objects before restoring on the new cluster.

**Comment by ncdc** [comment]
@Bradamant3 ^^^^
