### ISSUE TITLE
Allow creation of backup from Schedule

### ISSUE THREAD

**Issue by jrnt30** [heptio/ark#1085]
At times we want to manually kick off a set of backups "out of band of their normal schedule".  It would be useful if we had the ability  to create a `Backup` off of a `Schedule` and simply re-use that information already similar to the new Kuberente's Job cli's ability to create  `--from <CronJob>`

**Comment by ncdc** [comment]
Dupe of #656 😄

**Comment by jrnt30** [comment]
Thanks!  At least it wasn't my issue... :)
