### ISSUE TITLE
Server's client qps and burst should be configurable

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#109]
The defaults from client-go are qps=5 and burst=10. We should make these configurable so the server's requests aren't necessarily throttled all the time (the user/operator should be in control).

xref #108 
cc @dgoodwin

**Comment by rosskukulinski** [comment]
This likely would help improve the Ark performance for larger clusters.

**Comment by rosskukulinski** [comment]
This should be a metric that is exposed by #84.  Users should be able to know the maximum values for qps and burst (gauge), the current value (gauge), the number of times a request has throttled (counter).

**Comment by ncdc** [comment]
FYI I don't believe client-go gives us access to throttling information. It's unlikely we'll be able to expose any metrics around throttling unless/until client-go exposes it.

**Comment by ncdc** [comment]
It currently logs that information using `glog.V(4)`. Can't wait for client-go to have a configurable logger implementation....

**Comment by ffd2subroutine** [comment]
@ncdc this just means setting them in Config func https://github.com/heptio/ark/blob/master/pkg/client/client.go#L33 or even after calling it here https://github.com/heptio/ark/blob/master/pkg/cmd/server/server.go#L191 or ?

**Comment by ncdc** [comment]
@ffd2subroutine I think we'd want it to be configurable for the `ark server` command, using flags, with more sensible defaults (5 and 10 probably are a bit low). I think it would be ok to apply the values after the config is created in server.go.

**Comment by ffd2subroutine** [comment]
@ncdc okay thanks
