### ISSUE TITLE
Don't restore default service accounts or their associated secrets

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#110]
These will be created automatically by the control plane

cc @dgoodwin

**Comment by dgoodwin** [comment]
Ideally some way to configure what constitutes a default service account. OpenShift side we have a couple additional ones we don't want to recreate. I don't think these are annotated today, but it would be nice if they and "default" were.

This gets pretty close to the need to plug-in custom restorer logic, what to skip, what to transform, and what to merge.

**Comment by ncdc** [comment]
I once had a vision of externalizing all the restoration logic to some sort of config file with a DSL, but that's obviously a lot more work than what we did for the initial alpha release. Hopefully however we design pluggable external backup actions & restorers will facilitate things like this for you in OpenShift.

**Comment by ncdc** [comment]
We probably do need to restore the default SA, but have a way for it to be merged into the new one created automatically by Kube

**Comment by dgoodwin** [comment]
We hit this as well, merging customized image pull secrets between the old and new was the only use case we'd discovered so far but I'm sure there are more.

**Comment by ncdc** [comment]
Our thinking is to have custom pluggable conflict resolution handlers. We'll have some OOTB ones. Maybe even have one where you can just specify fields to copy over wholesale from the backup to what's in the new cluster (e.g. image pull secrets).

**Comment by ncdc** [comment]
Closing as we actually do want to restore default SAs and use conflict resolution to merge things like image pull secrets
