### ISSUE TITLE
An error occurred: unknown flag: --snapshotVolumes

### ISSUE THREAD

**Issue by gandarez** [heptio/ark#1100]
**What steps did you take and what happened:**
./ark backup create mano-brown_20181130_1 --snapshotVolumes

**What did you expect to happen:**
To create volume snapshots

**Environment:**

- Ark version (use `ark version`): v0.10.0
- Kubernetes version (use `kubectl version`): v1.11.2-gke.18

**Comment by skriss** [comment]
@gandarez the flag you're looking for is `--snapshot-volumes` (though you don't really even need to specify it explicitly - as long as you have a `VolumeSnapshotLocation` configured, snapshots will automatically be taken).

**Comment by gandarez** [comment]
voila!
