### ISSUE TITLE
Backup changes deployments apiVersion

### ISSUE THREAD

**Issue by shaikatz** [heptio/ark#1109]
**What steps did you take and what happened:**
We run a backup and the resulting deployment files apiVersion changed from `extensions/v1beta1` to `apps/v1`.

**What did you expect to happen:**
The resources apiVersion shouldn't be changed by ark backup.

**Anything else you would like to add:**
This behaviour blocks us from downgrading from 1.11.4 cluster to version that doesn't support `apps/v1`.

**Environment:**

- Ark version (use `ark version`):  0.9.10
- Kubernetes version (use `kubectl version`): 1.11.4
- Kubernetes installer & version: acs-engine 0.25.3
- Cloud provider or hardware configuration: azure

**Comment by ncdc** [comment]
The only thing that quickly comes to mind would be to add a field to the backup allowing the user to indicate if they want the oldest api version or the server's preferred api version. Ark currently uses the server's preferred api version. xref #1105

**Comment by ncdc** [comment]
We also currently use `apps` in favor of `extensions`, so we would need a way to control that.

@shaikatz what version are you trying to downgrade to, and why?

**Comment by shaikatz** [comment]
We trying to downgrade to 1.8.8 because we came up with some issues with 1.11.4 installation and we want to go back to our safe place before trying anything else.

**Comment by rosskukulinski** [comment]
Hi @shaikatz,

Thanks for using Ark and I'm sorry you ran into problems with your Kubernetes upgrade from 1.8.8 to 1.11.4.

Unfortunately, Ark isn't currently capable of supporting Kubernetes cluster downgrades.  As @ncdc mentioned, Ark is currently configured to use the API Server's preferred API version, which is appropriate for _most_ situations, especially for Kubernetes upgrades.  As we work towards our 1.0 release next year, we'll be working hard to ensure better documentation and guidance on upgrade & downgrade processes.

That said, you _may_ be able to leverage a manual work around to deal with the API version changes.  At a high level, you'll need to download your Ark backup tarball from Azure storage (you can use `ark backup download`), extract & edit the Deployment json to downgrade the API versions (and adjust any other necessary API spec changes), re-compress, and upload to Azure storage.  Then try restoring your backup again.
