### ISSUE TITLE
backup fails on pvc's "error creating snapshot" in AKS cluster

### ISSUE THREAD

**Issue by johnjbateman** [heptio/ark#1110]
**What steps did you take and what happened:**
I followed the exact same steps for two clusters.  One worked and one didn't.  After running all the installation and deployment of the yamls, the first initial backup fails at the steps to backup PersistentVolumeClaims.

ark backup create <name>

Error from backup logs is:

`backup=heptio-ark/nexsys-prod error="error creating snapshot: rpc error: code = Unknown desc = azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/50b308c6-62f8-47a1-8932-663bde48dc53/resourceGroups/MC_eus2-prod-infrastructure-rg_nexsys-eus2-prod-aks_eastus2/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-4f21a407-d22c-11e8-827e-12827ba1213e?api-version=2016-04-30-preview: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '401'" group=v1 groupResource=pods logSource="pkg/backup/item_backupper.go:209" name=prometheus-k8s-db-prometheus-k8s-1 namespace=monitoring`

**What did you expect to happen:**

Backup should succeed on the snapshot of the PVC.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/ark -n heptio-ark`
https://gist.github.com/johnjbateman/a0f1492b90756367209c036e6c274bf8

* `ark backup describe <backupname>` or `kubectl get backup/<backupname> -n heptio-ark -o yaml`
`apiVersion: ark.heptio.com/v1
kind: Backup
metadata:
  creationTimestamp: 2018-12-04T15:38:27Z
  generation: 1
  name: nexsys-prod
  namespace: heptio-ark
  resourceVersion: "8407075"
  selfLink: /apis/ark.heptio.com/v1/namespaces/heptio-ark/backups/nexsys-prod
  uid: a498b3ad-f7da-11e8-968f-46fe7194455f
spec:
  excludedNamespaces: null
  excludedResources: null
  hooks:
    resources: null
  includeClusterResources: null
  includedNamespaces:
  - '*'
  includedResources: null
  labelSelector: null
  storageLocation: ""
  ttl: 720h0m0s
  volumeSnapshotLocations: null
status:
  completionTimestamp: 2018-12-04T15:38:45Z
  expiration: 2019-01-03T15:38:27Z
  phase: Failed
  startTimestamp: 2018-12-04T15:38:27Z
  validationErrors: null
  version: 1
  volumeSnapshotsAttempted: 0
  volumeSnapshotsCompleted: 0`

* `ark backup logs nexsys-prod | grep kubernetes-dynamic-pvc`
https://gist.github.com/johnjbateman/e97172e0fbff46dd02c8a402767252a4

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

AKS in Azure
Separate SPN's, Subscriptions, Resource Groups, and Clusters for the backup that worked and that didn't.  But same Tenant.

I have selected the AZURE_RESOURCE_GROUP as the MC_ group and the backup is in that same resource group

The SPN was a contributor to the subscription and it didn't work.  Upgraded to owner of the subscription and that still doesn't work.

**Environment:**

- Ark version (use `ark version`): 

Not Working: Version: v0.10.0 (also tried Version: v0.9.0 and it didn't work)
Working: Version: v0.9.0
  
- Kubernetes version (use `kubectl version`): 

Not Working: Version: 1.11.3

Working: Version: 1.11.2

- Kubernetes installer & version: N/A
- Cloud provider or hardware configuration: AKS (managed)
- OS (e.g. from `/etc/os-release`): Linux Ubuntu 16.04

**Comment by ncdc** [comment]
@johnjbateman when we've seen this before, it's almost always a typo in the cloud-credentials secret (extra whitespace, etc).... right @skriss?

**Comment by johnjbateman** [comment]
These are the steps I followed.  I don't know how I could have typo'd:

~~~
AZURE_CLIENT_SECRET=`az ad sp create-for-rbac --name "heptio-ark-prod" --role "Contributor" --query 'password' -o tsv`

AZURE_PRINCIPAL_NAME="heptio-ark-prod"
AZURE_RESOURCE_GROUP=MC_eus2-prod-infrastructure-rg_nexsys-eus2-prod-aks_eastus2

AZURE_STORAGE_KEY=`az storage account keys list \
    --account-name $AZURE_STORAGE_ACCOUNT_ID \
    --resource-group $AZURE_BACKUP_RESOURCE_GROUP \
    --query '[0].value' \
    -o tsv`

AZURE_SUBSCRIPTION_ID=`az account list --query '[?isDefault].id' -o tsv`
AZURE_TENANT_ID=`az account list --query '[?isDefault].tenantId' -o tsv`

# Reset and capture password for service credential
AZURE_CLIENTSECRET=`az ad sp credential reset --name "$AZURE_PRINCIPAL_NAME" --years 0 --query 'password'_ -o tsv`

AZURE_CLIENT_ID=`az ad sp list --display-name "$AZURE_PRINCIPAL_NAME" --query '[0].appId' -o tsv`

kubectl create secret generic cloud-credentials \
    --namespace heptio-ark \
    --from-literal AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID} \
    --from-literal AZURE_TENANT_ID=${AZURE_TENANT_ID} \
    --from-literal AZURE_RESOURCE_GROUP=${AZURE_RESOURCE_GROUP} \
    --from-literal AZURE_CLIENT_ID=${AZURE_CLIENT_ID} \
    --from-literal AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET} \
    --from-literal AZURE_STORAGE_ACCOUNT_ID=${AZURE_STORAGE_ACCOUNT_ID} \
    --from-literal AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY}
~~~

**Comment by johnjbateman** [comment]
I just saw this:

`--query 'password'`

Is the word 'password' a literal?  Should that be an actual password?

**Comment by ncdc** [comment]
No, it's correct as `'password'` - that tells `az` that you want it to output just the password from the returned data.

**Comment by johnjbateman** [comment]
OK, thank you.  I checked the values in the secret, and I see they look fine.  I don't know what else to check:

~~~
Name:         cloud-credentials
Namespace:    heptio-ark
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
AZURE_TENANT_ID:           36 bytes
AZURE_CLIENT_ID:           36 bytes
AZURE_CLIENT_SECRET:       36 bytes
AZURE_RESOURCE_GROUP:      59 bytes
AZURE_STORAGE_ACCOUNT_ID:  15 bytes
AZURE_STORAGE_KEY:         88 bytes
AZURE_SUBSCRIPTION_ID:     36 bytes
~~~

I echo'd out the values of those variables and they look right.  for the AZURE_CLIENT_SECRET, where can I verify that?  in Azure AD?

**Comment by ncdc** [comment]
FWIW, a previously reported similar issue: #269.

You wrote above that the subscription is different in the one that's failing. AFAIK, `AZURE_SUBSCRIPTION_ID=`az account list --query '[?isDefault].id' -o tsv` will always return the same subscription. Can you confirm that you have the subscription correct?

**Comment by skriss** [comment]
@johnjbateman in https://github.com/heptio/ark/issues/1110#issuecomment-444176578, the first line sets `AZURE_CLIENT_SECRET`, then later you reset the secret and assign the new value to `AZURE_CLIENTSECRET` (note missing underscore), then you create the `cloud-credentials` secret using `AZURE_CLIENT_SECRET` (which is the original/no longer valid value).

You shouldn't need to reset the secret since the first line will auto-generate it, and store it in `AZURE_CLIENT_SECRET`.

**Comment by johnjbateman** [comment]
Yes, that was verified by echoing the value of that variable.  It is correct as to which subscription I am working with now (the one that is not working)

**Comment by johnjbateman** [comment]
@skriss I will check that right now.

**Comment by johnjbateman** [comment]
@skriss It was the typo in the variable AZURE_CLIENTSECRET.  Somehow that change got committed to my repo!  This is working now.  Thank you!
