### ISSUE TITLE
Simplify what's shown in `ark version`

### ISSUE THREAD

**Issue by skriss** [heptio/ark#1111]
`ark version` output is currently as follows:

For a release:
```
Version: v0.10.0
Git commit: v0.10.0
Git tree state: clean
```

For a development binary or container image binary built with `make build`, `make local`, etc:
```
Version: master
Git commit: v0.10.0-14-g4c5f352a
Git tree state: dirty
```

I'd like to make some changes to this:
- `Version` should remain as-is, which is either the git tag (if for a release built with goreleaser) or the value specified for `VERSION` (if built using `make build`)
- `Git commit` should *always* show the full git commit SHA that the build is for, rather than what it shows today
- `Git tree state`: I'm not sure on this one. Do folks think it's useful, or should we just drop it? Goreleaser doesn't actually let you build a release if the tree state isn't clean, so this is really only relevant for container image builds (either dev or release) and dev binary builds.  For release container image builds, since Jenkins is pulling the code directly from GH, logically it shouldn't be possible to have a non-clean status, unless something crazy is happening in Jenkins-land.  :shrug:

cc @ncdc @nrb @wwitzel3 @carlisia

**Comment by nrb** [comment]
This seems reasonable to me.

How do you think we should render server version when that's added? I assume what will be returned will be the same string that's displayed for client-side, just attached to the CRD, so it would look something like `Server version: v0.10.0`.

**Comment by skriss** [comment]
@nrb yeah that's what I was thinking.

anyone else opposed to dropping `Git tree state`?

**Comment by ncdc** [comment]
+1 to dropping as long as we include `--dirty` as part of our `git describe` to get the commit.

**Comment by skriss** [comment]
@ncdc I wasn't planning to use `git describe` to get the commit -- I was proposing switching to outputting the full SHA there, which `goreleaser` exposes as a built-in template var, and which our image build would get using `git rev-parse HEAD`.  If we want to keep the output of `git describe` there (which isn't just the straight SHA), *and* show an indication of dirty or not, then not sure that there's really any point in changing anything.  I thought you were onboard with dropping the tree state indication per https://github.com/heptio/ark/pull/1000/files/18b434cb241613a994303a7a2d0a1a6f55f7f4a0#diff-3a895417c300af3c34fab6ebb556e984

**Comment by skriss** [comment]
I'm happy to keep a clean/dirty indication if it's useful -- but I would still like to switch from `git describe` output to a a full git SHA for `Git version`

**Comment by ncdc** [comment]
@skriss my concern was that we might accidentally ship something with a dirty tree state, but upon further reflection, because goreleaser requires a clean checkout before it will proceed, that won't be an issue.

However, let's say that someone is building and testing ark locally, and they have uncommitted changes that are incorporated into the build. I think this is a situation where showing `-dirty` is appropriate. Or am I over worrying? 😄
