### ISSUE TITLE
Appending to CHANGELOG.md causes too many merge conflicts.

### ISSUE THREAD

**Issue by wwitzel3** [heptio/ark#1112]
Overlooked the fact that a person adding a changelog entry to the same file for every PR could create a lot of merge conflicts. We will adopt the pattern of adding a new file for every changelog entry in the `changelog/unreleased` folder.

We will update our contributing doc and current development changelog to reflect this.

**Comment by wwitzel3** [comment]
See discussion: https://github.com/heptio/ark/pull/234#issuecomment-444261265

**Comment by wwitzel3** [comment]
I think for now I won't add any special tooling for this. During a release we can just `cat changelog/unreleased/*` to get the changelog list. Opinions?

**Comment by ncdc** [comment]
SGTM @wwitzel3!

**Comment by ncdc** [comment]
Let's say I put this in my file:
```
  * Add pprof support to the Ark server (#234, @ncdc)
```

That's the current format. That includes indentation, the bullet, the PR number, and the author.

What if we did something like this? The file name includes the PR number and the GitHub username, such as `234-ncdc`, and the contents then look like this:
```
Add pprof support to the Ark server
```

Or is that too much work (tooling wise) and we should just keep it simple for now?

**Comment by wwitzel3** [comment]
I like the `issue-author` naming convention. We would need to add some helper that spit out the desired format, but that wouldn't be difficult at all. I am fine with that as our starting point here. Do you imagine that would be run as a make target? `make gen-changelog`

I do want to try and keep things as simple as possible for now and extend it as we make releases and find pain points.

**Comment by ncdc** [comment]
The more makefile targets, the merrier! 😄 If we have a simple tool to walk the unreleased dir and spit out properly formatted text, 👍

**Comment by carlisia** [comment]
This sounds very doable, 👍

**Comment by carlisia** [comment]
But also, the tooling doesn't have to be done as part of this issue.
