### ISSUE TITLE
We need your ideas for renaming Heptio Ark!

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#1122]
VMware has announced its intent to acquire Heptio, and as we join forces we are going to resolve any confusion / conflict with Arq (a different backup tool). We need your ideas to rename Heptio Ark—please jump in with suggestions that meet these criteria:

1. English word. No made-up terms or acronyms please. The name should be discoverable in an English dictionary.
2. Nautical theme. To be consistent with our other projects, it'd be ideal if the term had some nautical ties.

Final name selection requires legal clearance and a few other logistical bits, so we'll handle that internally. If we choose your submission, we will thank you with Heptio swag. Please submit your ideas BEFORE Monday, Dec. 17th. Thank you!

**Please submit constructive names only - no Boaty McBoatface, etc**. _thank you_

**Comment by carlisia** [comment]
- VMware Anchor: Don't leave your clusters adrift / Never lose your clusters

- Barge

- Barca

**Comment by wwitzel3** [comment]
* gantry

**Comment by timothysc** [comment]
kivotós - ark in greek.

**Comment by carlisia** [comment]
Needs to be an english word!

**Comment by skriss** [comment]
- bulwark
- krate

**Comment by ncdc** [comment]
Posting on behalf of Jeff Settle: dolly, after the cloned sheep

**Comment by wskulley** [comment]
lifeboat
preserver
dinghy
pinnace

**Comment by jonmeacham** [comment]
Drydock

**Comment by dharmab** [comment]
Something related to marine salvage seems approriate. _Vasa_ or _Azorian_?

**Comment by sfotony** [comment]
EPIRB

**Comment by jcrowthe** [comment]
- First Mate - the second in command of the ship
- Extremis - the point at which two vessels must break away to avoid a collision

**Comment by wbauern** [comment]
Arky McArkface

**Comment by jcrowthe** [comment]
"BackupMcBacky Face"

**Comment by katiemorrissey** [comment]
Drogue /droʊɡ/
A device to slow a boat down in a storm so that it does not speed excessively down the slope of a wave and crash into the next one. It is generally constructed of heavy flexible material in the shape of a cone.

**Comment by ncdc** [comment]
Please keep the names constructive. We'll be deleting those that are not.

**Comment by stevesloka** [comment]
**lagan**: cargo jettisoned from ship but marked by buoys for recovery

**Comment by jbeda** [comment]
BlueMarlin -- [the ship shipping ship](https://en.wikipedia.org/wiki/MV_Blue_Marlin)

**Comment by detiber** [comment]
naval recovery ships: https://history.nasa.gov/ships.html

**Comment by cparedes** [comment]
Heptio Backup and Recovery Cruise Ship (tm)

**Comment by rdodev** [comment]
* Cove (a sheltered bay where ships go set anchor in bad weather)
* Rescue
* Crane (used to move containers on and off ships)

**Comment by opowbow** [comment]
Stern

Tide

Rum

**Comment by rdodev** [comment]
* Heptio Lifevest
* Heptio Flare
* Heptio Lighthouse

**Comment by ncdc** [comment]
@rdodev can't have Heptio in the name 😛

**Comment by rdodev** [comment]
@ncdc fixed :)

**Comment by jcrowthe** [comment]
- Scuttle - as in we're scuttling the remainder of the k8s ship in favor of a full disaster recovery

**Comment by wskulley** [comment]
Cutter

**Comment by kris-nova** [comment]
Sloop

**Comment by k8k** [comment]
Noah

**Comment by kris-nova** [comment]
Dingy!

**Comment by castrojo** [comment]
Pharos - the lighthouse of alexandria
Ikaros - sounds cool, and greek but not too greek?

**Comment by jcrowthe** [comment]
Waypoint

**Comment by MQasimSarfraz** [comment]
Concur

**Comment by xstevens** [comment]
* Tug
* Auxiliary

**Comment by bgulla** [comment]
Tender - boat, or a larger ship used to service or support other boats or ships, generally by transporting people and/or supplies to and from shore or another ship.

**Comment by xgerman** [comment]
Ahab

**Comment by lachie83** [comment]
embarcadero - pier in Spanish.

**Comment by nautalice** [comment]
Carpathia - the ship that responded to the Titanic's distress signal

**Comment by aimzOG** [comment]
Marine: 
a) nautical themed
b) the military sends in the Marines when all hell breaks loose. They’re smaller than the rest of the branches because they’re specialized for more intense situations!- is a disaster happening? Send out your Marines!

Minesweeper
A vessel designed or equipped to clear areas of water of mines without necessaril detecting them first. It differs from a minehunter (q.v.), which is designed or equipped to detect and destroy individual mines.


Bailer
A device for removing water that has entered the boat.

Convoy
A group of ships traveling together for mutual support and protection.

**Comment by danderson** [comment]
Muster (assemble in a group, as when evacuating a ship). Has another more military meaning that may be unpalatable.

**Comment by blakedot** [comment]
deepocalypse

**Comment by tracymiranda** [comment]
felucca 

https://commons.wikimedia.org/wiki/File:Felucca_at_sunset_on_the_River_Nile_-_panoramio.jpg

**Comment by marcwickenden** [comment]
Boaty McBoatface. Sorry, couldn’t resist. It’s an English thing (google it). :-)

**Comment by dharmab** [comment]
@ncdc you should probably put "No BoatyMcboatface puns" in your top level seeing how popular that is. 😆

**Comment by jaxxstorm** [comment]
Flotsam: the wreckage of a ship or its cargo found floating on or washed up by the sea.

The ship has sunk (cluster) but the cargo (resources) are still recoverable

**Comment by ncdc** [comment]
@dharmab will do

**Comment by mpatters72** [comment]
Davy Jones Locker - where all the lost things go
Lift Bag - raises sunk ships

**Comment by blakedot** [comment]
lifeboat

**Comment by danderson** [comment]
Lifeboat - ensuring the survival of a ship's most important cargo

**Comment by jessfraz** [comment]
In the name of Unix, I am going to go with “backup” I know super creative :)

**Comment by ncdc** [comment]
@jessfraz well played

**Comment by marcwickenden** [comment]
Shark

**Comment by ncdc** [comment]
except you left in too many letters: `bkup`

**Comment by danderson** [comment]
Voyage - short for Voyage Data Recorder (VDR), the nautical equivalent of black boxes in aircraft.

**Comment by aserhat** [comment]
stow - pack or store (an object) carefully and neatly in a particular place.

**Comment by vllry** [comment]
Cluster in a bottle? Bottle?

**Comment by chadmillard** [comment]
Bumpkin 
Ahull

**Comment by homer6** [comment]
Dolly

https://en.wikipedia.org/wiki/Dolly_(sheep)

**Comment by blakedot** [comment]
Heptio Harbor - it's the safe place you keep your stuff

**Comment by MrMitch** [comment]
May I suggest _*Boaty*_, after the great [Boaty McBoatFace](https://en.wikipedia.org/wiki/Boaty_McBoatface)

**Comment by maorfr** [comment]
Salvage!

**Comment by recollir** [comment]
lazarette

>A lazarette is usually a storage locker used for gear or equipment a sailor or boatswain would use around the decks on a sailing vessel.

https://en.m.wikipedia.org/wiki/Lazarette

**Comment by stabby-r7** [comment]
Lifeboat

**Comment by scaranoj** [comment]
- kube-rescue
- [PFD](https://en.wikipedia.org/wiki/Personal_flotation_device)

**Comment by TamikoT** [comment]
Arkive  #dadjokes

**Comment by Abdennebi** [comment]
*Cleat* : A piece of metal or wood having projecting arms or ends on which a rope can be wound or secured (from: https://ahdictionary.com/word/search.html?q=cleat)

**Comment by ChristianAlexander** [comment]
Astern - like [astern propulsion](https://en.m.wikipedia.org/wiki/Astern_propulsion) (to back up a ship)

**Comment by wwitzel3** [comment]
loxodograph: An apparatus that records the course that a ship has travelled
https://en.m.wiktionary.org/wiki/loxodograph

**Comment by AlainRoy** [comment]
Haul
This is a nautical term that means "to steer a vessel closer to the direction of the window. It also gives a feeling for what the tool does with cluster data: it hauls to to a backup location, or to a new cluster. To be clear, this is not an acronym that starts with Heptio Ark. :)

**Comment by fabiorauber** [comment]
What about Caravel?

**Comment by dbowling** [comment]
Harbormaster. From Wikipedia: an official responsible for enforcing the regulations of a particular harbour or port, in order to ensure the safety of navigation, the security of the harbour and the correct operation of the port facilities.

**Comment by dangodev** [comment]
**Shore** (or **Shoring**): metal or wood used at sea to repair a leak (also, to make it back to shore, a safe place)
**Outrigger**: stabilizing structure on ships

**Comment by TigerC10** [comment]
Fathom.  In old maritime tradition, to measure the distance of how far your ship has travelled you'd drop a weight and then measure the rope that went off the ship by the arm-length.

**Comment by hhoover** [comment]
Pontoon
airtight hollow structures designed to provide buoyancy in water.

**Comment by lypht** [comment]
Floe

**Comment by csantanapr** [comment]
KimeMachine (ala Time Machine) :-)

**Comment by acbramley** [comment]
Something that isn't named the same as a very popular video game would be great :)

**Comment by bmess** [comment]
Pequod - The whaling ship in Moby Dick but also the rescue helicopter in Metal Gear V

**Comment by rikatz** [comment]
Heptio NOEH (Not Only Etcd Harmed), as Noeh also being the biblical person of the Ark (Noeh, Noah)

**Comment by rikatz** [comment]
Can be also only Noe (Not Only ETCD), as spelt in Portuguese :P

**Comment by csantanapr** [comment]
Kup (sounds like backup)

**Comment by rothgar** [comment]
keel - it's the part of the boat under water that keeps the boat upright. Keeling is another word for capsizing. It also already has a k in the name 😁

**Comment by karlkfi** [comment]
*Freebooter* - The pirate who knows where your k8s treasure is buried. The only one who can recover this plunder and restore your ship to its former glory. 

Mascot: a parrot with an eye patch and a tricorner hat who says “Batten down the hatches! Keep a weather eye open, matey! A storm be comin’!”

**Comment by axw** [comment]
Starship, as in interstellar travel.

**Comment by hharnisc** [comment]
Mutiny

**Comment by jethr0null** [comment]
Ballast - heavy material, such as gravel, sand, iron, or lead, placed low in a vessel to improve its stability

**Comment by jaydeland** [comment]
Let's follow in the example of the Brits - Boaty Mcboatface
https://www.theguardian.com/environment/2016/apr/17/boaty-mcboatface-wins-poll-to-name-polar-research-vessel

In all seriousness:
1. Bunker - A container for storing coal or fuel oil for a ship's engine. (A place to store your container meta data so you can keep fueling your business when things faill
2. Keel - the backbone of a vessel (backups and failover are the backbone of reliable systems)
3. Tack: to change a vessel’s direction, or the new direction (The product helps you change tack easily when systems fail)

**Comment by dhananjaysathe** [comment]
Disaster recovery at sea ?
- SOS
- Mayday
- lifebouy

**Comment by waltisfrozen** [comment]
Triton - Greek god, the messenger of the sea. He guided the Argonauts when they were lost and helped them find the sea. In short, he bailed people out, not unlike how Ark has helps with cluster recovery.

**Comment by justaugustus** [comment]
*b4p* - it's like `backup`, but k8s-ified! :)

**Comment by wic6** [comment]
Salvor : 
a person or company involved in saving ships that have been sunk or damaged, and the goods inside them

**Comment by tomplus** [comment]
**shark** - sh + ark ;)

**Comment by elisiano** [comment]
**bark**  - Backup And Recovery for Kubernetes

And, according to [wikipedia](https://en.wikipedia.org/wiki/Barque): 

> A barque, barc, or bark is a type of sailing vessel [...]

**Comment by dobozysaurus** [comment]
Parthenogenesis! Plenty of marine life does that (sharks, marbled crayfish, etc).

**Comment by tohjustin** [comment]
Admiral

**Comment by bbrundert** [comment]
Simply **Dock** (maintaining and repairing ships) 
(I see "Drydock" on the list already)

**Comment by elisiano** [comment]
> Simply **Dock** (maintaining and repairing ships)
> (I see "Drydock" on the list already)

and how would you call someone using that product? :trollface: Docker? 🤣

**Comment by bbrundert** [comment]
**Raft** - like an inflatable emergency liferaft (instead of lifeboat)

**Comment by parthi-geo** [comment]
##kaaka## - protection, last resort

**Comment by evillgenius75** [comment]
Salvage - rescue (a wrecked or disabled ship or its cargo) from loss at sea

**Comment by parthi-geo** [comment]
**Ahoy** - A cry to draw attention
**Banyan**  -  a short period of rest and relaxation 
**Rake**

**Comment by parthi-geo** [comment]
**Scow**

**Comment by dobozysaurus** [comment]
@ncdc Alternate suggestion, then: Ballast. Nothing provides stability to your system like a solid backup process.

**Comment by parthi-geo** [comment]
**Baleen**  - filter-feeder system that works by sucking in a large amount of water first and then pushes out water while filtering food sources. The feature I like in Ark is its ability to filter a subset of Kubernetes resources that matter to get the job done.

**Comment by mobeus1** [comment]
- V-Kraken - It will take your data to the bottom of the sea only to be summoned by a horde of undead. (like the kraken from Pirates of the Caribbean)
 - Anchor - to keep with the nautical nonsense theme of k8s + VMware Harbor
- Motoko - from Ghost in the Shell
- Artemis - because meh

**Comment by rguske** [comment]
**Lifebelt** (I saw Lifebuoy already...)
**Pearl**

**Comment by jenciso** [comment]
kbote = kubernetes + bote (lifeboat in spanish)

**Comment by mslocrian** [comment]
Flugel - the wing on which you fly your backups to the cloud.

**Comment by mauilion** [comment]
Klone or Kopy Ark is more than backup it can also be used as a templating tools for resources that you want to deploy.

**Comment by renatoassis** [comment]
Caravel - The caravel was a small, highly maneuverable sailing ship developed in the 15th century by the Portuguese

**Comment by cantbewong** [comment]
ark rename suggestion: Arise or Arise!

name emphasizes recovery stage of a backup - the most import function of what Ark does
sorry not really nautical theme but it does have an interesting Kubernetes + Heptio tie in.
Kubernetes used an "easter egg" to the seven of nine character from a star trek series related to the Borg race. Heptio continued the number 7 theme.
According to Wikipedia's Chinese numerology article:
`The number 7 (七, pinyin: qī) in Mandarin sounds like "even" in Mandarin (齊, pinyin: qí), so it is a good number for relationships. It also sounds like "arise" (起, pinyin: qǐ)`

**Comment by carlisia** [comment]
Phoenix

**Comment by stigsb** [comment]
Scuba - SCuba Used to Be Ark

**Comment by nodox** [comment]
Names:
- arc
- tangent
- radix
- feedbk
- noah
- pompeii

**Comment by spiffxp** [comment]
Celeste - The [Mary Celeste](https://en.wikipedia.org/wiki/Mary_Celeste) was a famous ghost ship

**Comment by TamikoT** [comment]
shArk 🦈

**Comment by rarean** [comment]
Vitamin C, helps recover from scurvy 😀

**Comment by geosoft1** [comment]
Dart (DisAster Recovery Tool). Also has some alternative meanings including nautical.

https://en.m.wikipedia.org/wiki/Glossary_of_nautical_terms

**Comment by tohjustin** [comment]
Since Kubernetes is a Greek term for _"governor"_, _"helmsman"_ or _"captain"_, we'll have an **Admiral** that give commands to the ship's helmsman when disaster strikes 😅 

or we can follow Kubernetes's Greek 🇬🇷 + Nautical 🚢  theme:
> **[Navarch](https://en.wikipedia.org/wiki/Navarch) (Greek: ναύαρχος)** - Greek word meaning "leader of the ships", which in some states became the title of an office equivalent to that of a modern admiral.

**Comment by opowbow** [comment]
Backstop - 

political in the EU currently ; positive baseball connotations ; and ..from a **water** perspective...when rowing - before you set off - you sit at "backstops" balance the boat ...and then go.....

**Comment by mark-j-chilvers** [comment]
Amber

**Comment by JessicaGreben** [comment]
koast-guard

watchkeep

buoy

beacon

**Comment by ricksevans** [comment]
marina

**Comment by ricksevans** [comment]
quay

**Comment by ricksevans** [comment]
landing

**Comment by HerrmannHinz** [comment]
https://en.wikipedia.org/wiki/Bathyscaphe_Trieste

first submarine in the Mariana Trench - maybe there are a cuttle, erm couple of more ideas in the article.

**Comment by HerrmannHinz** [comment]
moar ship - maybe a little pathetic. 

https://matrix.fandom.com/wiki/Nebuchadnezzar

**Comment by gitmedur** [comment]
Poseidon

**Comment by ype** [comment]
RRS Sir David Attenborough

https://en.wikipedia.org/wiki/RRS_Sir_David_Attenborough#Naming_poll

**Comment by cpuguy83** [comment]
icekube
