### ISSUE TITLE
Dangling PVCs caused backup be in failed state

### ISSUE THREAD

**Issue by jaxxstorm** [heptio/ark#1134]
**What steps did you take and what happened:**
Create a PVC in AWS
Delete the underlying EBS volume, but not the PVC

**What did you expect to happen:**
Some sort of error should be logged, but a backup failure shouldn't be thrown

**The output of the following commands will help us better understand what's going on**:
time="2018-12-19T19:18:04Z" level=info msg="Backup completed with errors: error getting volume info: rpc error: code = Unknown desc = InvalidVolume.NotFound: The volume 'vol-0470876891e1e4172' does not exist.\n\tstatus code: 400, request id: 6e45eb57-903a-4f30-b4bc-b4d546c27290" backup=heptio-ark/test logSource="pkg/backup/backup.go:289"

**Environment:**

- Ark version (use `ark version`):  v0.10.0
- Kubernetes version (use `kubectl version`): v1.12.2
- Kubernetes installer & version: kubeadm
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): CentOS

**Comment by ncdc** [comment]
@jaxxstorm thanks for the report. This is part of #286 (specifically this comment: 
https://github.com/heptio/ark/issues/286#issuecomment-440382021). Is it ok with you if we mark this as a duplicate and we keep track of it in 286?

**Comment by jaxxstorm** [comment]
Yes sure, couldn't find a related issue. Will close
