### ISSUE TITLE
ark restore from ebs snapshots on kubernetes doesn't preserve storage class metadata

### ISSUE THREAD

**Issue by sokoow** [heptio/ark#1177]
**What steps did you take and what happened:**
1. Created an EBS volume (kubernetes pv + storageclass metadata attached)
2. Filled it with some data
3. created ark backup - it created snapshots of EBSes, all fine here
4. Blew away my pv and pvc, removed from aws side also
5. Did ark restore, restore did bring back ebs snapshots correctly, but...

**What did you expect to happen:**
Old EBS pv/volume on my kube had a storage class attached to it, restored volume doesn't have it

**The output of the following commands will help us better understand what's going on**:
Unfortunately can't provide that.

**Environment:**
We're running ark 0.9.0
Kube 1.10.2
aws

**Comment by ncdc** [comment]
Hi @sokoow, this was previously filed as #791, and we have #1097 open to see if we need to continue doing this, or if we can start including the storage class when we restore. Would it be ok to close this issue and use #1097 for further comments?

**Comment by sokoow** [comment]
Sure, thanks for quick response
