### ISSUE TITLE
Can't get ark to startup

### ISSUE THREAD

**Issue by ivelichkovich** [heptio/ark#1181]
**What steps did you take and what happened:**
I deployed ark following the documentation for version v0.9.11.

**What did you expect to happen:**
Ark to startup.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/ark -n heptio-ark`
`time="2019-02-01T17:44:46Z" level=info msg="setting log-level to INFO"
time="2019-02-01T17:44:46Z" level=info msg="Starting Ark server v0.9.8" logSource="pkg/cmd/server/server.go:101"
time="2019-02-01T17:44:46Z" level=info msg="Checking existence of namespace" logSource="pkg/cmd/server/server.go:264" namespace=heptio-ark
time="2019-02-01T17:44:46Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:270" namespace=heptio-ark
An error occurred: unable to retrieve the complete list of server APIs: external.metrics.k8s.io/v1beta1: an error on the server ("Internal Server Error: \"/apis/external.metrics.k8s.io/v1beta1\": Unauthorized") has prevented the request from succeeding`

**Anything else you would like to add:**
We are running on EKS with k8s version 1.10.11

**Environment:**

- Ark version (use `ark version`): 
v0.9.11
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:03:09Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.11-eks", GitCommit:"6bf27214b7e3e1e47dce27dcbd73ee1b27adadd0", GitTreeState:"clean", BuildDate:"2018-12-04T13:33:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`
- Kubernetes installer & version:
EKS
- Cloud provider or hardware configuration:
AWS

**Comment by ncdc** [comment]
@ivelichkovich what do you have deployed for a custom/external metrics server? Are you able to `kubectl get --raw /apis/external.metrics.k8s.io/v1beta1`?

**Comment by ivelichkovich** [comment]
Yeah same error. What's interesting is before this error I was getting an error about an unrelated service account in a different namespace being unauthorized to do something so I deleted and recreated that service account and now have this error

**Comment by ncdc** [comment]
Could you please share `kubectl -n heptio-ark get deploy/ark -o yaml`?

**Comment by ivelichkovich** [comment]
`apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"ark","namespace":"heptio-ark"},"spec":{"replicas":1,"template":{"metadata":{"annotations":{"prometheus.io/path":"/metrics","prometheus.io/port":"8085","prometheus.io/scrape":"true"},"labels":{"component":"ark"}},"spec":{"containers":[{"args":["server","-v","3"],"command":["/ark"],"env":[{"name":"ARK_SCRATCH_DIR","value":"/scratch"},{"name":"AWS_CLUSTER_NAME","value":"daffy"}],"image":"gcr.io/heptio-images/ark:v0.9.8","name":"ark","volumeMounts":[{"mountPath":"/plugins","name":"plugins"},{"mountPath":"/scratch","name":"scratch"}]}],"restartPolicy":"Always","serviceAccountName":"ark","volumes":[{"emptyDir":{},"name":"plugins"},{"emptyDir":{},"name":"scratch"}]}}}}
  creationTimestamp: 2019-02-01T17:56:54Z
  generation: 3
  labels:
    component: ark
  name: ark
  namespace: heptio-ark
  resourceVersion: "84293593"
  selfLink: /apis/extensions/v1beta1/namespaces/heptio-ark/deployments/ark
  uid: c2d11012-264a-11e9-aea6-122e20a17724
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      component: ark
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8085"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        component: ark
    spec:
      containers:
      - args:
        - server
        - -v
        - "3"
        command:
        - /ark
        env:
        - name: ARK_SCRATCH_DIR
          value: /scratch
        - name: AWS_CLUSTER_NAME
          value: daffy
        image: gcr.io/heptio-images/ark:v0.9.8
        imagePullPolicy: IfNotPresent
        name: ark
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /plugins
          name: plugins
        - mountPath: /scratch
          name: scratch
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ark
      serviceAccountName: ark
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: plugins
      - emptyDir: {}
        name: scratch
status:
  conditions:
  - lastTransitionTime: 2019-02-01T17:56:54Z
    lastUpdateTime: 2019-02-01T17:58:31Z
    message: ReplicaSet "ark-54f754c87b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2019-02-01T19:33:08Z
    lastUpdateTime: 2019-02-01T19:33:08Z
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 3
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1`

I've been intentionally omitting the aws creds secret so that ark just uses the nodes aws perms.

Another interesting point is that ark on our prod cluster is okay, those nodes are still on 1.10.3 though

**Comment by ncdc** [comment]
Ok, now `kubectl get clusterrolebinding/ark -o yaml`?

**Comment by ivelichkovich** [comment]
`kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1beta1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"labels":{"component":"ark"},"name":"ark","namespace":""},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"cluster-admin"},"subjects":[{"kind":"ServiceAccount","name":"ark","namespace":"heptio-ark"}]}
  creationTimestamp: 2019-02-01T17:05:41Z
  labels:
    component: ark
  name: ark
  resourceVersion: "84212266"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/ark
  uid: 9b30616d-2643-11e9-ba6d-0a54d8ecfa86
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: ark
  namespace: heptio-ark`

**Comment by ncdc** [comment]
Also, when you're running `kubectl` in your terminal, what user are you?

**Comment by ivelichkovich** [comment]
The group is system:masters

**Comment by ncdc** [comment]
Your user is in `system:masters`?

**Comment by ivelichkovich** [comment]
Yeah that's how we attach but it breaks down to eks-admin service account attached to clusterrole cluster-admin

**Comment by ncdc** [comment]
There must be some difference between the ark serviceaccount's permissions and your user running `kubectl`. I can't say what specifically without seeing all the rbac details in your cluster.

**Comment by ivelichkovich** [comment]
I ran an ubuntu pod set to sleep with the same service account as ark. 

This happens `root@ark-5d8445dd77-26j7s:/# ./kubectl get --raw /apis/external.metrics.k8s.io/v1beta1
Error from server (InternalError): an error on the server ("Internal Server Error: \"/apis/external.metrics.k8s.io/v1beta1\": Unauthorized") has prevented the request from succeeding`

So you're right, digging into the cluster-admin role to try to find out why.

**Comment by ncdc** [comment]
I would take a look at all of the roles that your `kubectl` user has access to - my guess is that user has more roles than the `ark` SA
