### ISSUE TITLE
OpenStack storage backend

### ISSUE THREAD

**Issue by jamiehannaford** [heptio/ark#119]
Would be great to have some kind of storage driver for OpenStack Cinder and Swift that uses gophercloud. What do folks think? I might have time to help out with this, but just wanted to open a tracking issue for feedback and visibility

**Comment by ncdc** [comment]
@jamiehannaford thanks for the idea! Are you thinking this would be an object storage provider, where the backup tarballs go?

**Comment by jamiehannaford** [comment]
@ncdc Yeah exactly. So basically a new dir in [`pkg/cloudprovider`](https://github.com/heptio/ark/tree/master/pkg/cloudprovider) that implements the object storage interface. You can also implement an block storage provider for OpenStack for Ark snapshotting.

**Comment by ncdc** [comment]
@jamiehannaford that would be cool! If you've got spare cycles to work on this, we'd be happy to review a PR. Otherwise, we'll be working on a roadmap for future features over the next week or so, and we'd add this to list for prioritization.

**Comment by ncdc** [comment]
PR: #164 

Removing `help wanted` label since there's a PR

**Comment by ncdc** [comment]
Spoke to someone at KubeCon Copenhagen who wants to take over this work. Will reach out separately and get the ball rolling there.
