### ISSUE TITLE
Add opentracing support

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#121]

**Comment by rosskukulinski** [comment]
What value would this provide?  Ark probably isn’t being used in situations where tracing would be valuable.

**Comment by ncdc** [comment]
I was brainstorming around possible features and thus wrote this one down. If we were to do this, it would potentially provide tracing into a single backup or restore's execution. I'm not sure if that would be useful or not. Probably once we do backup/restore progress (#20/#21), this won't provide much utility. I'd be fine closing.
