### ISSUE TITLE
Possibility of abstracting CRD/controller into common lib?

### ISSUE THREAD

**Issue by jamiehannaford** [heptio/ark#124]
This is more of a question than anything else but I was wondering if folks think there's enough common ground to abstract controller/CRD logic into a common library. A few months ago I wrote up a [proposal for a new community project](https://docs.google.com/document/d/1NJhFcNezJyLM952eaYVcdfIQFQYWsAx4oTaA82-Frdk/) that provides helper functionality and abstractions so that people don't need to duplicate the same boilerplate code when they write userland controllers. 

A few projects like rook and giant swarm are interested. Here are some related discussions:

https://github.com/rook/rook/issues/740
https://github.com/coreos/etcd-operator/issues/1125
https://github.com/giantswarm/aws-operator/issues/325

We've initially piggy backed off [rook's codebase](https://github.com/rook/operator-kit), but would like to expand and add new features so it aligns more with community expectations. I took a quick look at ark's architecture and it seems to have similar use cases (monitoring and reconciling CRD state). I would love to hear feedback from folks about this - I completely understand if it doesn't fit the needs of ark or other Heptio projects. Just thought I'd float the idea 😄

**Comment by timothysc** [comment]
This is generally a good thing provided the abstraction doesn't bloat and can live on it's own.

**Comment by ncdc** [comment]
@jamiehannaford agree with Tim - if we can make it simple, easy to use, and small.

**Comment by ncdc** [comment]
Ark now has a `genericController` struct that we may consider extracting into a standalone repo at some point, but I don't think we need to keep this issue open any more.
