### ISSUE TITLE
Switch to an interface for the logger

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#133]
Not that we want to switch impls again, but it's annoying to pass around `*logrus.Logger` vs `*logrus.Entry`. Let's move to an interface and call it a day.

cc @davecheney b/c I know you'll love this 😄

**Comment by davecheney** [comment]
How about this as a middle ground.

1. define something like `internal/log.Logger` as an interface which looks very close to logrus's api
2. use that for new development

..
..
..

99. revisit the methods in use and try to trim down the interface api later?

**Comment by skriss** [comment]
@ncdc logrus has a FieldLogger interface that both *Logger and *LogEntry implement. Do you want to use that, or have our own framework-agnostic interface?

**Comment by ncdc** [comment]
@skriss I didn't realize that existed when I was doing the pkg/backup refactoring. I don't feel super strongly about that vs our own.

**Comment by skriss** [comment]
yeah, I didn't realize it existed for awhile, else I would've used it to start with. I'd be comfortable with using that.
