### ISSUE TITLE
Set User-Agent

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#14]
Right now it's `ark/v1.7.1 (linux/amd64) kubernetes/$Format` where `v1.7.1` comes from kube / client-go. We should probably do something like:

`ark/v0.3.2 (linux/amd64) 35b865d`

**Comment by ncdc** [comment]
Might want to do `ark` for the cli and `ark-server` for the server

**Comment by ncdc** [comment]
@jrnt30 any interest in taking on this one?

**Comment by jrnt30** [comment]
Is 35b865d in your example the git sha that built the binary?

**Comment by ncdc** [comment]
@jrnt30 it's the git commit of the repo, yes. We'd want to set it in pkg/buildinfo/version.go via linker flags at build time.

**Comment by jrnt30** [comment]
Sounds good.  I actually already did some of that work for the WIP Backup Logs.  I will extract that and work on this
