### ISSUE TITLE
Add support for AWS IAM Instance Profile Auth

### ISSUE THREAD

**Issue by rji** [heptio/ark#140]
According to https://github.com/heptio/ark/blob/bb5088f5/docs/cloud-provider-specifics.md#aws, Ark requires the user to create and provide AWS access keys as Ark configuration parameters. In some environments, users are prevented from doing this, either by policy or by other site-specific technical measures.

That said, I'd like to request a feature.

As an Ark user, I want to be able to use [AWS IAM Instance Profiles](http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html) to authenticate with the AWS API, so that I don't have to create an AWS keypair. This would ensure that Ark uses patterns similar to those already in use by other Kubernetes-related projects, such as the [cluster-autoscaler](https://github.com/kubernetes/autoscaler/blob/afd066c9/cluster-autoscaler/cloudprovider/aws/README.md).

**Comment by ncdc** [comment]
Hi @rji, thanks for your feedback! We use this AWS session creation flow: https://github.com/heptio/ark/blob/b7c35551d7e5ef65f37a4fa2a93154e594471729/vendor/github.com/aws/aws-sdk-go/aws/session/session.go#L417-L471, so if that supports IAM instance profiles, you'll be able to take advantage of them right away (e.g., if you wanted to used an assumed role, Ark supports that). If that flow doesn't have the functionality you need, do you know which part of the AWS SDK for Go would let us do that?

cc @mattmoyer

**Comment by ncdc** [comment]
I should clarify that we don't currently allow you to configure anything via the AWS Go Config/Session-related structs, but we support any of the environment variables the SDK does (which allows for things like assumed roles).

**Comment by rji** [comment]
Oh interesting, thanks for the tip (and quick response) @ncdc! Reading through the code you linked to, I'm fairly certain this will work for us. For the time being, I'm going to close this issue since I don't think there's any action that needs to be taken, other than perhaps clarification in the AWS docs. If that isn't the case, we can always re-open it and contribute something back (docs or otherwise).

Thanks again!

**Comment by ncdc** [comment]
Sounds good, thanks @rji!
