### ISSUE TITLE
Label selector is ignored when getting backups and restores

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#160]
We have a flag for the label selector, and a variable to hold the value, but we aren't passing it to the List call.

**Comment by nrb** [comment]
I'll grab this as a first PR. I believe I found the location (https://github.com/heptio/ark/blob/master/pkg/cmd/cli/backup/get.go#L52), but need to do some research into Cobra to grok how it fits together.

**Comment by ncdc** [comment]
There, and pkg/cmd/cli/restore/get.go. Let us know if you need any pointers.
