### ISSUE TITLE
KmsKeyId can be alias as well

### ISSUE THREAD

**Issue by lli-hiya** [heptio/ark#161]
In the Config, we can specify KmsKeyId to allow for encryption and I accidentally find that if we give `alias/<alias-name>` in that field, it still works. But from the source code I didn't find any clue for this. Can someone help me verify this? Then I can create a PR to fix documentation.

**Comment by mattmoyer** [comment]
We end up passing the key "ID" to [`s3:PutObject`](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html) ([here](https://github.com/heptio/ark/blob/87f60ed853d70d618ef2987ccbbe88f827559fe1/pkg/cloudprovider/aws/object_storage_adapter.go#L79-L83)) which seems to allow KMS aliases as well as fully-specified KMS key ARNs. I haven't found where AWS documents that explicitly, but I'm +1 on documenting it in Ark.

**Comment by jfoy** [comment]
From http://docs.aws.amazon.com/kms/latest/developerguide/programming-aliases.html:
> You can use an alias as the value of the KeyId parameter only in the following operations:
> * DescribeKey
> * Encrypt
> * GenerateDataKey
> * GenerateDataKeyWithoutPlaintext
> * ReEncrypt

**Comment by skriss** [comment]
Fixed by #163
