### ISSUE TITLE
[Feature] Support storing Ark backups within a sub-dir of object storage buckets

### ISSUE THREAD

**Issue by skriss** [heptio/ark#167]
Right now Ark only supports storing backups within the root of an object storage bucket. It would be nice to support storing them within sub-dirs as well.

**Comment by ncdc** [comment]
Moving out of v0.7.0 as we'll probably do this as part of the backup target redesign.

**Comment by rosskukulinski** [comment]
I recommend default `subPath` value is `/` which will use the top-level directory of the storage bucket.

We should not assume `subpaths` exist, so we should create the complete path, `mkdir -p`, if it doesn't exist.

**Comment by rosskukulinski** [comment]
@ncdc works for me.  My `mkdir` comment was simply trying to clarify my point about creating subdirectories (if necessary)
