### ISSUE TITLE
Backup coverage reporting

### ISSUE THREAD

**Issue by kstewart** [heptio/ark#17]
It would be useful to be able to generate backup coverage reports - i.e. an easy way to see which objects in a cluster/namespace are/aren't being backed up by existing schedules. This could be done by listing all resources, then matching them to schedule backup specs based on namespace includes/excludes, resource includes/excludes, and label selector.

**Comment by ncdc** [comment]
@skriss any objections to closing this?

**Comment by skriss** [comment]
fine with me, closing.
