### ISSUE TITLE
Replace testlogger.NewNullLogger with arktest.NewLogger

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#181]

**Comment by lukepatrick** [comment]
What did you have in mind here? NewLogger and NewNullLogger are of different types
e.g.
`func NewLogger() *logrus.Entry {
	logger := logrus.New()
	logger.Out = ioutil.Discard
	return logrus.NewEntry(logger)
}`

and

`// NewNullLogger creates a discarding logger and installs the test hook.
func NewNullLogger() (*logrus.Logger, *Hook) {
	logger := logrus.New()
	logger.Out = ioutil.Discard
	return logger, NewLocal(logger)
}`

**Comment by ncdc** [comment]
@lukepatrick we'll probably do this as part of #133
