### ISSUE TITLE
monitoring scheduled backups

### ISSUE THREAD

**Issue by tomplus** [heptio/ark#190]
I don't see any option to monitor Ark, especially if scheduled jobs are performed. Is it possible now or would be in the future ? An endpoint with metrics exposed by BackupController would be very helpful and easy to integrate with Prometheus.

Thanks.

**Comment by ncdc** [comment]
Hi @tomplus, thanks for your feedback. We already have an open issue about adding metrics in Prometheus format - #84. Would you be ok if we closed this and you added your feedback to the other issue?

**Comment by tomplus** [comment]
Ups, sorry :) I really, really tried to find it. I close it now. Thanks.
