### ISSUE TITLE
Default backup TTL of 24hrs is too short

### ISSUE THREAD

**Issue by blakebarnett** [heptio/ark#195]
Maybe this is an edge case but I went to restore some backups I made from yesterday and was surprised to discover they were gone.  I suppose the expected use case is to start in restore-only mode so this wouldn't happen, but it does seem like a longer default TTL would make more sense, maybe 72h? A week?

**Comment by skriss** [comment]
Thanks for the feedback, @blakebarnett. That's probably a good change to make to the default going forward. Care to submit a PR? :) No worries if not, we'll keep the issue open.

**Comment by ncdc** [comment]
How about 30 days?
