### ISSUE TITLE
refresh the Ark config definition doc

### ISSUE THREAD

**Issue by skriss** [heptio/ark#197]
The config-definition doc is (IMHO) becoming unwieldy, particularly with recent changes to the Ark config. The nesting structure of the file has changed, so we're now using `/` to indicate sub-properties more frequently within this doc, which is not entirely clear. I think it's ready for a refresh, but would like to get input from a writer. Maybe we should add commented examples to this page?

**Comment by rosskukulinski** [comment]
@skriss you're referring to [this page](https://heptio.github.io/ark/v0.8.1/config-definition)?  If so I agree -- the table is also in need of some TLC - in particular the right column depending on how wide the window is.

Recommend doing this effort in parallel to #103 which will introduce BackupTargets.

**Comment by ncdc** [comment]
@skriss any objections to removing the Bug label from this issue?

**Comment by skriss** [comment]
nope, removed.

**Comment by skriss** [comment]
@rosskukulinski yep that's the one.
