### ISSUE TITLE
Are restores automatically incremental?

### ISSUE THREAD

**Issue by blakebarnett** [heptio/ark#200]
I saw some unexpected behavior when testing restores with version 0.5.1:

1. Created a backup named `e2e-1`
2. Deployed some stuff (ex. istio)
3. Created a backup named `e2e-2`
4. Deleted the cluster
5. Brought up a fresh minimal cluster
6. Restored backup `e2e-2`

When I ran `ark restore get` it listed both `e2e-1` and `e2e-2` as just `Completed`

I was expecting each backup/restore to be a completely separate thing, am I just mistaken or is this a bug?

**Comment by ncdc** [comment]
@blakebarnett this is what I would expect if you ran `ark backup get` - is there any chance that's what you did?

**Comment by blakebarnett** [comment]
I did, doesn't that just list the backups?  If not that is very surprising. :)

**Comment by ncdc** [comment]
You wrote "When I ran ark restore get it listed both e2e-1 and e2e-2 as just Completed", but if your backup is called `e2e-1`, then a corresponding restore would be called something like `e2e-1-20171114142940`.

Here is what I think happened - tell me if this is right?

1. Created backup `e2e-1`
1. Deployed some stuff
1. Created backup `e2e-2`
1. Deleted the cluster
1. Created new cluster
1. Restored backup `e2e-2`
1. Ran `ark backup get` and it listed both `e2e-1` and `e2e-2` as `Completed`.

**Comment by blakebarnett** [comment]
You're right they were the long-form unique names, but it was `ark restore get` that I ran in #7, and it showed both as completed when I had only requested `e2e-2`

**Comment by ncdc** [comment]
Thanks for clarifying. Any chance you could try to reproduce, copying & pasting the exact commands and output (just the relevant ones - like `ark backup get` and `ark restore get` at various stages)?

**Comment by blakebarnett** [comment]
Yep, will repro later today.

**Comment by ncdc** [comment]
@blakebarnett circling back - could you ever reproduce your issue?

**Comment by blakebarnett** [comment]
No I think this was another case of me mixing up clusters before I realized I couldn't set kube-context.
