### ISSUE TITLE
Add support for conflict handler plugins

### ISSUE THREAD

**Issue by dgoodwin** [heptio/ark#205]
An issue exists with the default created service accounts. If customized in any way, and included in a backup, the backup copy will be skipped on restore as the cluster controllers have already recreated a new default service account in the namespace. As such any customizations are lost. Image pull secrets are a good example here.

Propose adding a new plugin type for handling conflicts, which can return either nothing, or a patch to be applied to the existing object. 

pkg/restore/ConflictHandlerAction:

```
type ConflictHandlerAction interface {
    Resolve(existingObj runtime.Unstructured, backupObj runtime.Unstructured, restore *api.Restore, backup *api.Backup) (runtime.Unstructured)

    // As per ResourceRestoreAction
    AppliesTo() (includedNamespaces, excludedNamespaces, includedResources, excludedResources []string, selector string)
}
```

Return nil to indicate no changes are required to existing object.

Use Kube utils to generate a patch between existingObj and the return value, and submit to server.

**Comment by ncdc** [comment]
Instead of `Prepare`, how about `Resolve`? Also going to need both the `fromBackup` and `inCluster` copies of the object.

As far as the patch goes, we could maybe let the handler return the fully modified version that needs to be patched. Ark could generated the patch bytes.

I don't think we need WaitForReady and Ready.

**Comment by ncdc** [comment]
And we should have no-op be a valid resolution (which means use whatever's already in the cluster) - possibly by returning `nil` for the updated object.

**Comment by ncdc** [comment]
xref #130

**Comment by ncdc** [comment]
xref #74

**Comment by ncdc** [comment]
Closing in favor of #74.
