### ISSUE TITLE
AWS Quickstart Docs

### ISSUE THREAD

**Issue by stevesloka** [heptio/ark#208]
Would be nice to have the quick start docs for AWS (https://github.com/heptio/ark/blob/master/docs/cloud-provider-specifics.md#aws) also provide steps on how to create the S3 bucket from command line to follow with the command line steps to create the IAM user / policy. 

Also, would be a good practice to set the IAM policy to only allow access to that bucket and not all of S3.

**Comment by Bradamant3** [comment]
Is this issue closed with PR #259 ?

**Comment by ncdc** [comment]
I think so. @stevesloka could you please look at the latest docs on master for AWS and see if your requests were resolved?

**Comment by jrnt30** [comment]
The second piece of this, limiting the scope of the permissions grants is still outstanding.

**Comment by ncdc** [comment]
Last bit fixed by #363
