### ISSUE TITLE
backing up & restoring cronjobs

### ISSUE THREAD

**Issue by ipedrazas** [heptio/ark#209]
I've created and restored a backup and everything went well apart from restoring the cronjobs.

When you do the backup, you have entries like this one:

```
time="2017-11-21T10:36:03Z" level=info msg="Backing up resource" backup=heptio-ark/production group=batch/v1 groupResource=jobs.batch name=ach-confirmations-master-22c0879-1508335500 namespace=default

time="2017-11-21T10:36:03Z" level=info msg="Backing up resource" backup=heptio-ark/production group=batch/v1 groupResource=jobs.batch name=ach-rejects-achrun-f741700-1511173200 namespace=default
```

Note the `group=batch/v1`. Those cronjobs are not `batch/v1` but `batch/v2alpha1`:

```
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  creationTimestamp: 2017-07-21T15:09:45Z
  labels:
    chart: ddp-0.2.0
  name: ach-rejects-achrun-f741700
```

When you try to restore the backup you have these messages:

```
time="2017-11-21T11:06:41Z" level=error msg="Error refreshing discovery" error="unable to retrieve the complete list of server APIs: batch/v2alpha1: the server could not find the requested resource" error.file="helper.go:108" error.function="(*helper).Refresh" logSource="/go/src/github.com/heptio/ark/pkg/cmd/server/server.go:499"
```

This is the result of `kubectl api-versions`

```
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1beta1
apps/v1beta1
ark.heptio.com/v1
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
autoscaling/v1
batch/v1
batch/v2alpha1
certificates.k8s.io/v1beta1
extensions/v1beta1
networking.k8s.io/v1
policy/v1beta1
rbac.authorization.k8s.io/v1alpha1
rbac.authorization.k8s.io/v1beta1
settings.k8s.io/v1alpha1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1
```

**Comment by ncdc** [comment]
@ipedrazas Ark backs up the API version that the apiserver says is its "preferred" version, which is `batch/v1` in this case. Can you run `ark backup download <backup name>`, untar it, and check to see what the job's apiVersion is stored as?

What versions of Kubernetes and Ark are you testing with?

We'll try to reproduce as well.

**Comment by ipedrazas** [comment]
ark version
Version: v0.5.1
Git commit: v0.5.1
Git tree state: clean

Kubernetes version: 1.7.10

The cronjob `resources/cronjobs.batch/namespaces/default/jbr-master-job-runner-stsu.json`  contains `batch/v2alpha1`

```
{"apiVersion":"batch/v2alpha1","kind":"CronJob","metadata":{"creationTimestamp":"2017-07-21T15:09:45Z",
```

I think it's what you mention about the "preferred" version. Clearly, the backup works, but then when you try to restore we have this error:

```
time="2017-11-21T11:06:41Z" level=error msg="Error refreshing discovery" error="unable to retrieve the complete list of server APIs: batch/v2alpha1: the server could not find the requested resource" error.file="helper.go:108" error.function="(*helper).Refresh" logSource="/go/src/github.com/heptio/ark/pkg/cmd/server/server.go:499"
```
Which makes me think that `ark` cannot create a `batch/v2alpha1` object.

**Comment by ncdc** [comment]
Can you paste the output of ‘kubectl get --raw /apis/batch’?

**Comment by ipedrazas** [comment]
```
{"kind":"APIGroup","apiVersion":"v1","name":"batch","versions":[{"groupVersion":"batch/v1","version":"v1"},{"groupVersion":"batch/v2alpha1","version":"v2alpha1"}],"preferredVersion":{"groupVersion":"batch/v1","version":"v1"},"serverAddressByClientCIDRs":null}
```

**Comment by ipedrazas** [comment]
Is there any way to change the "_preferred_" version?

**Comment by ncdc** [comment]
That's up to the server, and it's hard-coded.

Can you gist/paste this: `kubectl get cronjob/<your cron job name> --v=8` (adjust the namespace, etc. as needed)

**Comment by ipedrazas** [comment]
Here it goes

https://gist.github.com/ipedrazas/4b977023ee61681a016150ba8ef7decb

**Comment by skriss** [comment]
@ipedrazas are you restoring into the same cluster that you're backing up from?

**Comment by ipedrazas** [comment]
we cannot reproduce this issue anymore
