### ISSUE TITLE
How to delete / replace backups

### ISSUE THREAD

**Issue by gargath** [heptio/ark#212]
Hi,

I have a feeling that this is a really stupid question, but I haven't managed to find a conclusive answer in the docs:

How does one go about deleting or overwriting a backup object?
Can it just be deleted from S3 (in our case)?

An `ark backup delete` subcommand would be useful.

Thanks,

Phil

**Comment by ncdc** [comment]
Thanks for trying out Ark! For now, if you delete from s3, it will
eventually be deleted from Kube too. We do plan to have a delete
subcommand, but haven’t gotten around to it yet. Hopefully soon!

**Comment by gargath** [comment]
But to be clear, it is entirely safe to just delete the S3 folder corresponding to the backup?

**Comment by ncdc** [comment]
If you’re fine not having the backup data any more, yes.

**Comment by etiennetremel** [comment]
I also agree with @gargath, it would be nice to have such feature, that would ease deletion of associated snapshots, for now we have to manually look for the ark tag and the creation date added to the snapshot.

**Comment by ncdc** [comment]
This is definitely a feature we plan to add. We'd definitely welcome & appreciate pull requests if anyone has time. Otherwise, it's on our roadmap, and we will eventually implement it.

**Comment by skriss** [comment]
I'm working on this ATM.
