### ISSUE TITLE
Restoring a PVC/PV using the default storageClass

### ISSUE THREAD

**Issue by blakebarnett** [heptio/ark#224]
Ark v0.5.1
k8s v1.7.10

Currently we rely on the default storageClass to dynamically provision our EBS volumes.  Ark will happily snapshot them and even restore the PV and PVC, but because it's a default storageClass there's no volumeID specified, so the PVC happily creates a new PV and ignores the previous one.

My question is, if we set `volumeReclaimPolicy: Retain` and restore from an ark backup, is it expected that we will need to manually modify all PVCs to point at the restored volumes?  Are there any plans to handle this situation automatically in ark?

**Comment by ncdc** [comment]
Can you paste sample yaml for a PV and PVC?

**Comment by blakebarnett** [comment]
Sure, here's a basic example without the reclaim policy set:

```apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
  creationTimestamp: 2017-11-29T20:23:32Z
  labels:
    app: dex-postgresql
    chart: postgresql-0.8.3
    heritage: Tiller
    release: dex
  name: dex-postgresql
  namespace: security
  resourceVersion: "4197"
  selfLink: /api/v1/namespaces/security/persistentvolumeclaims/dex-postgresql
  uid: 2b6fa8c6-d543-11e7-ad59-02df93e00a3a
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: gp2
  volumeName: pvc-2b6fa8c6-d543-11e7-ad59-02df93e00a3a
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  phase: Bound
```

```apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: aws-ebs-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/aws-ebs
  creationTimestamp: 2017-11-29T20:23:33Z
  labels:
    failure-domain.beta.kubernetes.io/region: us-east-1
    failure-domain.beta.kubernetes.io/zone: us-east-1b
  name: pvc-2b6fa8c6-d543-11e7-ad59-02df93e00a3a
  resourceVersion: "4195"
  selfLink: /api/v1/persistentvolumes/pvc-2b6fa8c6-d543-11e7-ad59-02df93e00a3a
  uid: 2bcaef10-d543-11e7-ad59-02df93e00a3a
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://us-east-1b/vol-009dd3e2df1be41c0
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: dex-postgresql
    namespace: security
    resourceVersion: "4153"
    uid: 2b6fa8c6-d543-11e7-ad59-02df93e00a3a
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2
status:
  phase: Bound
```

**Comment by blakebarnett** [comment]
So for testing, I delete the cluster this volume is in (which deletes the PV because of the reclaimPolicy), the backup has a valid snapshot.  If I redeploy the cluster and install ark, then do a restore, the EBS volume gets recreated from the snapshot, but the PVC is using a new different PV.

**Comment by ncdc** [comment]
Can you also share the `status` portion from `ark backup get <backup name>`?

**Comment by ncdc** [comment]
> but because it's a default storageClass there's no volumeID specified, so the PVC happily creates a new PV and ignores the previous one.

Where are you seeing a lack of a volumeID?

**Comment by blakebarnett** [comment]
Because we're using the default storageClass we don't specify the volume ID in the PVC.

```status:
  expiration: 2017-11-30T20:33:21Z
  phase: Completed
  validationErrors: null
  version: 1
  volumeBackups:
    pvc-2b6fa8c6-d543-11e7-ad59-02df93e00a3a:
      availabilityZone: us-east-1b
      snapshotID: snap-0618ccfa847dbe65f
      type: gp2
```

**Comment by ncdc** [comment]
> Because we're using the default storageClass we don't specify the volume ID in the PVC.

That's normal/expected and Ark should work just fine with that.

**Comment by ncdc** [comment]
Could you please check your restore's logs and paste anything related to `pvc-2b6fa8c6-d543-11e7-ad59-02df93e00a3a` (and a few lines of context before/after too)?

**Comment by blakebarnett** [comment]
I suppose we should work around this by using 

```  selector:
    matchLabels:
      app: ...
      release: ...
```

In our PVCs then?  It was just unexpected behavior to me that it recreated the EBS volume, but then didn't use it.

**Comment by ncdc** [comment]
You may be running into a bug, but the expected behavior is that it will create a new EBS volume from the EBS snapshot, and associate it with the PV/PVC.

**Comment by ncdc** [comment]
You shouldn't need to do anything with matchLabels, no. Let's keep debugging 😄

**Comment by blakebarnett** [comment]
ok, doing another delete/restore to capture logs (sorry, didn't keep the old ones around due to the low TTL)

**Comment by blakebarnett** [comment]
ok, it worked that time...  the difference being that this is on k8s 1.8.4 now (testing upgrades right now). 

I was wondering if maybe this happens if the pod gets scheduled to a different AZ than the original PV was created in?  We have 3 AZs configured.

I'll try to recreate with 1.7 if you think that might be relevant.

**Comment by ncdc** [comment]
> I was wondering if maybe this happens if the pod gets scheduled to a different AZ than the original PV was created in? We have 3 AZs configured.

It could be something along these lines. We'll examine the code and see if anything stands out.

**Comment by blakebarnett** [comment]
I am about 80% sure this was a my own dumb fault.  We have all our cluster configs in the same kubeconfig, and I believe I was actually backing up and restoring a different cluster than I was expecting because I forgot to set the current-context.

related: https://github.com/heptio/ark/issues/207
