### ISSUE TITLE
restoring from one GKE cluster to another leaves target cluster unusable

### ISSUE THREAD

**Issue by djschny** [heptio/ark#23]
The goal was to perform a backup on one GKE cluster and then restore into a fresh brand new GKE cluster of the same version, number of nodes, etc. However afterwards the following items happen to the target cluster:

# Unexpected Behavior

* Trying to view the dashboard UI, proxy, or look at logs for a pod will yield the error:
```
$ kubectl --namespace=heptio-ark logs ark-1716490312-bkzhm 
Error from server: Get https://gke-cluster-2-default-pool-c30ff04e-055z:10250/containerLogs/heptio-ark/ark-1716490312-bkzhm/ark: No SSH tunnels currently open. Were the targets able to accept an ssh-key for user "gke-3159bbe8fc682764335a"?
```
* Listing the nodes in the cluster will list nodes that aren't present in the cluster and were the names of the nodes in the original cluster:
```
$ kubectl get nodes
NAME                                       STATUS    AGE       VERSION
gke-cluster-1-default-pool-c7c701f6-0pjb   Unknown   4m        
gke-cluster-1-default-pool-c7c701f6-l5ml   Unknown   4m        
gke-cluster-1-default-pool-c7c701f6-wp5n   Unknown   4m        
gke-cluster-2-default-pool-c30ff04e-055z   Ready     19m       v1.7.2
gke-cluster-2-default-pool-c30ff04e-czlx   Ready     19m       v1.7.2
gke-cluster-2-default-pool-c30ff04e-jz2h   Ready     19m       v1.7.2
```

* After restoring, the cluster will become unresponsive for about a minute with kubectl commands timing out and the cluster UI admin screen showing it unavailable. It eventually returns

* Services will not get LoadBalancer IPs associated with them

* The ark restore log has numerous errors. See this gist https://gist.github.com/djschny/f0879b2173478ce03238b0a68e4345c4

# Steps to reproduce

* Create two `1.7.2` three node clusters in GKE (`cluster-` and `cluster-2`)
* Create some namespaces and deployments in `cluster-1`
* Install ark on `cluster-1`
* perform a backup `ark backup create everything --exclude-namespaces=kube-system,heptio-ark --snapshot-volumes` even making sure to exclude system/sensitive namespaces
* Install ark on `cluster-2`
* perform a restore `ark restore create everything --restore-volumes`

**Comment by ncdc** [comment]
@djschny can you try specifying `--exclude-resources nodes` when you create the backup?

**Comment by ncdc** [comment]
Re the warnings & errors in the gist, I saw 2 different categories, both of which we're currently aware:

1. An item of the same name already exists
1. Unable to create an RBAC resource because of a privilege escalation

For 1, we could potentially attempt to do a diff and only record a warning if there is a substantive difference. If you think that would be useful, let's file an issue for it.

For 2, we should probably document that if you want to restore RBAC resources, you will need to run the ark service account as cluster-admin.

**Comment by skriss** [comment]
@djschny - i was able to repro this issue. Excluding node resources from the backup eliminated the problem, as did manually kubectl delete-ing the extraneous nodes that got created in the target cluster from a full backup.

**Comment by djschny** [comment]
> @djschny can you try specifying --exclude-resources nodes when you create the backup?

I tried restoring with that option but it says it is invalid:

```
$ ark restore create everything3 --restore-volumes --exclude-resources nodes
Error: unknown flag: --exclude-resources
Usage:
  ark restore create BACKUP [flags]

Flags:
      --label-columns stringArray            a comma-separated list of labels to be displayed as columns
      --labels mapStringString               labels to apply to the restore
      --namespace-mappings mapStringString   namespace mappings from name in the backup to desired restored name in the form src1:dst1,src2:dst2,...
      --namespaces stringArray               comma-separated list of namespaces to restore
  -o, --output string                        Output display format. For create commands, display the object but do not send it to the server. Valid formats are 'table', 'json', and 'yaml'.
      --restore-volumes                      whether to restore volumes from snapshots
  -l, --selector labelSelector               only restore resources matching this label selector (default <none>)
      --show-labels                          show labels in the last column

Global Flags:
      --alsologtostderr                  log to standard error as well as files
      --kubeconfig string                Path to the kubeconfig file to use to talk to the Kubernetes apiserver. If unset, try the environment variable KUBECONFIG, as well as in-cluster configuration
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --logtostderr                      log to standard error instead of files
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          log level for V logs
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

An error occurred: unknown flag: --exclude-resources
```

**Comment by ncdc** [comment]
@djschny when creating the backup, not the restore. We will be adding that flag to the restore soon.

**Comment by djschny** [comment]
I retested on the backup side and that did the trick. There were still lots of errors/warnings as mentioned before. I'd like to keep this issue open though so that one and/or two things get tracked:

* documentation updated on extra flags needed
* adjust default settings so that no extra options should be needed

In the scenario of a simplistic backup everything and restore over to this fresh cluster item, it would be great if all the exceptions were not needed and more so not on the backup side:

```
ark backup create everything --exclude-namespaces=kube-system,heptio-ark --snapshot-volumes --exclude-resources nodes
```

I believe a subset of this is in the works already?

**Comment by ncdc** [comment]
@djschny that makes sense. Let's see how close we can get 😄

**Comment by ncdc** [comment]
I've split this out into 3 separate specific issues - #71, #72, #73, #74. I'm going to close this now. @djschny if you think I've missed anything, let me know and we'll create more issues.
