### ISSUE TITLE
Support watching/waiting for a backup/restore to finish after creating it

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#233]
Something like `ark backup/restore create foo --wait`. Could combine with #20 #21 to show progress updates as they occur.

**Comment by hectorj2f** [comment]
@ncdc We're also interesting on a `--wait` flag. We found scenarios where `ark restore create` successfully exits but the backup wasn't restore yet. Do you have any timeline for this new feature ?

**Comment by hectorj2f** [comment]
With some guidance I think I could even help with this and to contribute to ark :)

**Comment by hectorj2f** [comment]
Can we get a workaround before a new release is delivered ? We'd like to be sure when a backup is fully restored. Ark command says `the backup was successfully restored` but the operation is still going under hook.

**Comment by ncdc** [comment]
@hectorj2f we will be releasing v0.7.0 on February 15th, and we have adjusted the text when you run `ark restore create` to say
```
Restore request <name> submitted successfully.
Run `ark restore describe <name>` for more details
```

I realize this doesn't give you a "wait" feature in the short term, but it does clarify that the restore isn't immediately finished.

Are you still interested in trying to implement this functionality? We would love a contribution!

**Comment by hectorj2f** [comment]
@ncdc thanks! yeah, we'll upgrade our version to 0.7.0. We'll combine `restore get and restore describe`. 

Yes, I'd be interested but I might not have enough time to speed up this implementation at this moment :/.

**Comment by ncdc** [comment]
FYI @hectorj2f I have a WIP implementation for waiting for backups in #304. It's not going to make v0.7.0 but we will try to include it in v0.8.0 or possibly a v0.7.x.

**Comment by rosskukulinski** [comment]
Yes! This is a very helpful/important feature to integrate Ark into CI/CD or other automation workflows.

As a user, I would like to take a backup of my cluster before deploying a feature/config/etc.  If the deployment/change fails, I would like to trigger an Ark restore.  [This may be really helpful for complex deploys that may trigger db migrations, configmap/secret changes, etc, that are not covered by normal Kubernetes deployment rollback.]

Looks like @ncdc  already has a WIP PR -- what does it take to wrap that up?

**Comment by ncdc** [comment]
@rosskukulinski there's 1 or 2 minor things I'd want to change, but otherwise, it's basically ready to go. I'd also want to do something similar for `ark restore create` and maybe even `ark backup delete`.

**Comment by rosskukulinski** [comment]
+1 for consistency for having `--wait` across commands.
