### ISSUE TITLE
Support S3 server side encryption with KMS

### ISSUE THREAD

**Issue by madddi** [heptio/ark#24]
Hi,

we'd like to store encrypted backups in S3 using [S3 SSE with KMS](https://docs.aws.amazon.com/kms/latest/developerguide/services-s3.html#sse). Are you planning to support this?

The S3 go pkg should already support this so it should just be a matter of adding a config option and using it in `object_storage_adapter.go` in the AWS cloudprovider. If this is correct I could give it a go and submit a patch if you like.

**Comment by ncdc** [comment]
Hi @madddi, thanks for reporting this. It definitely sounds like something we should support. We would love a patch if you've got the time to do it. Thanks!

**Comment by madddi** [comment]
Hi @ncdc, we thought about deploying Ark on OpenShift but noticed that OpenShift is missing support for `CustomResourceDefinitons` or even `ThirdPartyResources`. The patch should be working, but I can't test it. Should I open a PR - the changes should be quick to review.

I hate to submit untested code but can't easily spin up a Kubernetes cluster on AWS right now.

**Comment by ncdc** [comment]
@madddi no worries - if you submit a PR, I think we should hopefully be able to test it.

**Comment by ncdc** [comment]
Fixed by #29
