### ISSUE TITLE
ACS/AKS quick start docs

### ISSUE THREAD

**Issue by sauryadas** [heptio/ark#240]
It would be great to add this documentation. right now folks have to look in 2 places .
1) the generic quick start
2) Cloud provider specifics
    https://github.com/heptio/ark/blob/master/docs/cloud-provider-specifics.md#azure

**Comment by ncdc** [comment]
Hi @sauryadas, thanks for your suggestion. We will be revamping our install & setup docs over the next few weeks. I believe, though, that you can just follow the cloud provider specifics for Azure and be good to go. If that's not the case, please let us know.

Note, we are aware we need to adjust one thing re AKS - we need to indicate that the resource group you set in the cloud-credentials file needs to be the AKS group that is created dynamically for the AKS cluster, and not the resource group in which you create the cluster.

**Comment by sauryadas** [comment]
Re:   Note, we are aware we need to adjust one thing re AKS - we need to indicate that the resource group you set in the cloud-credentials file needs to be the AKS group that is created dynamically for the AKS cluster, and not the resource group in which you create the cluster.

I dont think we need the RG in the cloud credentials file to be in the dynamically created RG. This has been fixed

**Comment by ncdc** [comment]
We had someone yesterday using the original RG and it wasn't able to find the managed disk to create a snapshot. Did a fix go out yesterday afternoon to translate the original RG to the dynamic one?

**Comment by ncdc** [comment]
cc @jimzim

**Comment by sauryadas** [comment]
@ paulbouwer fyi

**Comment by ncdc** [comment]
@Bradamant3 as you work through the docs revamp, please keep this in mind (or close if you think we're there now). Thanks.
