### ISSUE TITLE
restore objects without impacting data plane

### ISSUE THREAD

**Issue by yingnanzhang666** [heptio/ark#242]
**Scenario:**
When etcd cluster lost all the data (such as disk issue), etcd cluster become unhealthy and didn't provide service. But all the data plane is still running.

**Wishes:**
In this situation, we wish recover control plane, but shouldn't impact the data plane, such as pod/services/etc.

**Actual:**
If using ark backup to restore, it will delete all the status of objects and recreate them to cluster. The old status will lost, such as the service ip, it will change. Then the data plane will be impacted, although these data plane pods, services are running normally before.

**Comment by ncdc** [comment]
Hi @yingnanzhang666, thanks for reporting this. I'd like to tackle this as one or more concrete, specific issues. Would your immediate concern be resolved if we preserved a service's cluster IP?

**Comment by ncdc** [comment]
@yingnanzhang666 hi, just checking in to see if you think my suggestion is sufficient?

**Comment by ncdc** [comment]
Closing due to age. Please feel free to reopen if you want to revisit this.
