### ISSUE TITLE
Bug: $ark restore create <non-existent-backup-name> creates successfully

### ISSUE THREAD

**Issue by sauryadas** [heptio/ark#246]
Should ideally throw an error?

**Comment by ncdc** [comment]
Thanks for the report, this is something I meant to file a long time ago & forgot. Would you be interested in submitting a PR to address this?

**Comment by hectorj2f** [comment]
I also experienced this issue. I +1 on a quick fix

**Comment by sauryadas** [comment]
@paulbouwer

**Comment by ncdc** [comment]
We have a PR to fix this that we'll merge this week: #271.
