### ISSUE TITLE
AWS - Restore failed - unexpected character

### ISSUE THREAD

**Issue by splisson-altair** [heptio/ark#247]
I did a backup of a namespace to S3 that successfully completed
```
ark backup create aqa-backup5 --include-namespaces aqa
Backup "aqa-backup5" created successfully.

ark backup describe aqa-backup5

Name:         aqa-backup5
Namespace:    heptio-ark
Labels:       <none>
Annotations:  <none>

Namespaces:
  Included:  aqa
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Phase:  Completed

Backup Format Version:  1

Expiration:  2018-01-11 09:59:17 -0800 PST

Validation errors:  <none>

Persistent Volumes:
  data-pv-mongodb-aqa:
    Snapshot ID:        snap-xxx
    Type:               gp2
    Availability Zone:  us-east-1a
    IOPS:               <N/A>
  data-pv-search-aqa:
    Snapshot ID:        snap-yyyy
    Type:               gp2
    Availability Zone:  us-east-1a
    IOPS:               <N/A>
```

* Expected:
namespace restored

* Results:

When I try to restore it, I get:
```
ark restore create ark-backup-5

ark restore get
An error occurred: v1.RestoreList: Items: []v1.Restore: v1.Restore: Status: v1.RestoreStatus: Errors: readUint64: unexpected character: �, error found in #10 byte of ...|"errors":{"ark":null|..., bigger context ...|es":["*"],"restorePVs":false},"status":{"errors":{"ark":null,"cluster":null,"namespaces":null},"phas|...

kubectl -n heptio-ark logs ark-1326452586-j9snq 

E1212 18:03:42.180291       1 reflector.go:205] github.com/heptio/ark/pkg/generated/informers/externalversions/factory.go:61: Failed to list *v1.Restore: v1.RestoreList: Items: []v1.Restore: v1.Restore: Status: v1.RestoreStatus: Errors: readUint64: unexpected character: �, error found in #10 byte of ...|"errors":{"ark":null|..., bigger context ...|es":["*"],"restorePVs":false},"status":{"errors":{"ark":null,"cluster":null,"namespaces":null},"phas|...

**Comment by ncdc** [comment]
@splisson-altair it sounds like you might have a version mismatch. Could you please paste the output of `ark version` and `kubectl -n heptio-ark logs deploy/ark | grep 'Starting Ark server'`?

**Comment by splisson-altair** [comment]
ark version
Version: v0.6.0
Git commit: v0.6.0
Git tree state: clean

kubectl -n heptio-ark logs deploy/ark | grep 'Starting'
time="2017-12-12T17:58:50Z" level=info msg="Starting Ark server v0.6.0" logSource="pkg/cmd/server/server.go:86"
time="2017-12-12T17:58:50Z" level=info msg="Starting controllers" logSource="pkg/cmd/server/server.go:397"
time="2017-12-12T17:58:50Z" level=info msg="Starting RestoreController" logSource="pkg/controller/restore_controller.go:149"
time="2017-12-12T17:58:50Z" level=info msg="Starting DownloadRequestController" logSource="pkg/controller/download_request_controller.go:114"
time="2017-12-12T17:58:50Z" level=info msg="Starting BackupController" logSource="pkg/controller/backup_controller.go:142"
time="2017-12-12T17:58:50Z" level=info msg="Starting ScheduleController" logSource="pkg/controller/schedule_controller.go:129"

**Comment by ncdc** [comment]
Does this s3 bucket have restores created by a previous version of Ark?

**Comment by splisson-altair** [comment]
No, brand new bucket

**Comment by ncdc** [comment]
Can you paste/gist `kubectl -n heptio-ark get restore -o yaml`?

**Comment by splisson-altair** [comment]
kubectl -n heptio-ark get restore -o yaml
apiVersion: v1
items:
- apiVersion: ark.heptio.com/v1
  kind: Restore
  metadata:
    clusterName: ""
    creationTimestamp: 2017-12-12T18:02:11Z
    deletionGracePeriodSeconds: null
    deletionTimestamp: null
    name: ark-backup-5-20171212100211
    namespace: heptio-ark
    resourceVersion: "28311616"
    selfLink: /apis/ark.heptio.com/v1/namespaces/heptio-ark/restores/ark-backup-5-20171212100211
    uid: 939e7898-df66-11e7-bb4e-0ec7853b033a
  spec:
    backupName: ark-backup-5
    excludedNamespaces: null
    excludedResources: null
    includeClusterResources: null
    includedNamespaces:
    - '*'
    includedResources: null
    labelSelector: null
    namespaceMapping: {}
    restorePVs: null
  status:
    errors: 0
    phase: ""
    validationErrors: null
    warnings: 0
- apiVersion: ark.heptio.com/v1
  kind: Restore
  metadata:
    clusterName: ""
    creationTimestamp: 2017-12-12T18:03:21Z
    deletionGracePeriodSeconds: null
    deletionTimestamp: null
    name: ark-backup-5-20171212100320
    namespace: heptio-ark
    resourceVersion: "28311756"
    selfLink: /apis/ark.heptio.com/v1/namespaces/heptio-ark/restores/ark-backup-5-20171212100320
    uid: bd1c1e93-df66-11e7-bb4e-0ec7853b033a
  spec:
    backupName: ark-backup-5
    excludedNamespaces: null
    excludedResources: null
    includeClusterResources: null
    includedNamespaces:
    - '*'
    includedResources: null
    labelSelector: null
    namespaceMapping: {}
    restorePVs: null
  status:
    errors: 0
    phase: ""
    validationErrors: null
    warnings: 0
- apiVersion: ark.heptio.com/v1
  kind: Restore
  metadata:
    clusterName: ""
    creationTimestamp: 2017-12-12T18:10:52Z
    deletionGracePeriodSeconds: null
    deletionTimestamp: null
    name: ark-backup-6-20171212101051
    namespace: heptio-ark
    resourceVersion: "28312643"
    selfLink: /apis/ark.heptio.com/v1/namespaces/heptio-ark/restores/ark-backup-6-20171212101051
    uid: ca0d9f22-df67-11e7-bb4e-0ec7853b033a
  spec:
    backupName: ark-backup-6
    excludedNamespaces: null
    excludedResources: null
    includeClusterResources: null
    includedNamespaces:
    - '*'
    includedResources: null
    labelSelector: null
    namespaceMapping: {}
    restorePVs: null
  status:
    errors: 0
    phase: ""
    validationErrors: null
    warnings: 0
- apiVersion: ark.heptio.com/v1
  kind: Restore
  metadata:
    clusterName: ""
    creationTimestamp: 2017-12-12T18:11:21Z
    deletionGracePeriodSeconds: null
    deletionTimestamp: null
    name: ark-backup-6-20171212101120
    namespace: heptio-ark
    resourceVersion: "28312701"
    selfLink: /apis/ark.heptio.com/v1/namespaces/heptio-ark/restores/ark-backup-6-20171212101120
    uid: db564d94-df67-11e7-88b8-12d5494f262c
  spec:
    backupName: ark-backup-6
    excludedNamespaces: null
    excludedResources: null
    includeClusterResources: null
    includedNamespaces:
    - '*'
    includedResources: null
    labelSelector: null
    namespaceMapping: {}
    restorePVs: null
  status:
    errors: 0
    phase: ""
    validationErrors: null
    warnings: 0
- apiVersion: ark.heptio.com/v1
  kind: Restore
  metadata:
    clusterName: ""
    creationTimestamp: 2017-08-07T20:34:43Z
    generation: 0
    name: dev-backup-20170807203443
    namespace: heptio-ark
    resourceVersion: "7153143"
    selfLink: /apis/ark.heptio.com/v1/namespaces/heptio-ark/restores/dev-backup-20170807203443
    uid: d81035d1-7baf-11e7-90ba-0ab24d0726d8
  spec:
    backupName: dev-backup
    labelSelector: null
    namespaceMapping: {}
    namespaces:
    - '*'
    restorePVs: false
  status:
    errors:
      ark: null
      cluster: null
      namespaces: null
    phase: Completed
    validationErrors: null
    warnings:
      ark: null
      cluster: null
      namespaces: null
- apiVersion: ark.heptio.com/v1
  kind: Restore
  metadata:
    clusterName: ""
    creationTimestamp: 2017-08-07T20:37:33Z
    generation: 0
    name: dev-backup-20170807203733
    namespace: heptio-ark
    resourceVersion: "7153507"
    selfLink: /apis/ark.heptio.com/v1/namespaces/heptio-ark/restores/dev-backup-20170807203733
    uid: 3d40a00a-7bb0-11e7-90ba-0ab24d0726d8
  spec:
    backupName: dev-backup
    labelSelector: null
    namespaceMapping: {}
    namespaces:
    - '*'
    restorePVs: false
  status:
    errors:
      ark: null
      cluster: null
      namespaces: null
    phase: Completed
    validationErrors: null
    warnings:
      ark: null
      cluster: null
      namespaces: null
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

**Comment by splisson-altair** [comment]
I see I have older restore CRD that were done from a previous version of ark  probaly

**Comment by ncdc** [comment]
It looks like you have 2 restores created from a previous version of Ark: `dev-backup-20170807203443` and `dev-backup-20170807203733`. You'll need to delete these. In v0.6.0 we made some breaking changes that aren't compatible with previous versions.

**Comment by splisson-altair** [comment]
I deleted all restore and created a new one. 
I had a typo in the name of the backup in the restore command!

Restore worked!

Thanks

**Comment by ncdc** [comment]
Glad you got it sorted out!

**Comment by splisson-altair** [comment]
The cleanup of restore CRDs was also needed, it was blocking the beginning of restore
