### ISSUE TITLE
Unbound PVC causes a backup to fail

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#254]
If a PVC has no `spec.volumeName`, it marks the entire backup as failed. A PVC might not have `spec.volumeName` if there is no default `storageclass` and there isn't one specified on the PVC itself, or maybe the desired dynamic provisioner isn't configure yet, to name a couple of reasons. We probably should not treat this as an error condition. WDYT @skriss?

**Comment by skriss** [comment]
agree, this shouldn't be an error from an Ark perspective.
