### ISSUE TITLE
issue with cloud-provider-specifics.md

### ISSUE THREAD

**Issue by fayazg** [heptio/ark#255]
Trying to integrate with aws but get the following error.

```
12/19/2017 11:09:10 AMtime="2017-12-19T18:09:10Z" level=error msg="error listing backups" error="rpc error: code = Unknown desc = BucketRegionError: incorrect region, the bucket is not in 'us-west-2' region\n\tstatus code: 301, request id: , host id: " logSource="pkg/controller/backup_sync_controller.go:75"
```

Anything obvious excluded from the steps that I am missing?

**Comment by skriss** [comment]
@fayazg have you created an S3 bucket in us-west-2 to store backups, and plugged the name into the ark config object? Our scripts don't do that for you.

**Comment by fayazg** [comment]
Got it, thanks Steve.

**Comment by skriss** [comment]
No problem. I'll close this issue for now but if anything else comes up feel free to file a new one or reach out on slack (#ark-dr under the kubernetes org)
