### ISSUE TITLE
Helm chart for installation ?

### ISSUE THREAD

**Issue by vietwow** [heptio/ark#257]
Hi,

Nowaway, helm seems like a "standard" way for deploying a service to Kubernetes. So I think it would be great if we have a helm chart for installing Heptio Ark.

Best Regards,
VietNC

**Comment by ncdc** [comment]
Hi @vietwow, thanks for your suggestion. We are first planning to add an `ark install` command that will cover everything needed to install Ark (#52). I think this will be the easiest way to do it, once implemented.

We may consider eventually doing a Helm chart in the future. Howerver, please be aware of potential security implications of using Helm: https://engineering.bitnami.com/articles/helm-security.html.

**Comment by ncdc** [comment]
FYI, there is a PR to add a helm chart here: https://github.com/kubernetes/charts/pull/3795

**Comment by rosskukulinski** [comment]
The helm chart PR was merged, so I'm going to mark this as closed.

That said, it's important to note that the Helm chart is a community contribution.  I would expect that the Ark project will rally around an `ark install` command (#52) as the recommended way for installation.

**Comment by bhack** [comment]
It is merged alrea in stable (`chart/stable`)  so I suppose that many users will start to use that directly. I suggest to don't let the chart to be a "2nd class" deployment.

**Comment by zakkg3** [comment]
In the docs there is a section.. Install with helm chart, but it's wrong. the command will simply wont work if you don't specify where is the chart
`helm install --set-file credentials.secretContents.cloud=./credentials-velero`
it should be
`helm install --set-file credentials.secretContents.cloud=./credentials-velero stable/velero'
 https://velero.io/docs/v1.0.0/install-overview/

And another thing to point is, if this is the official chart why not co-mantain it ?

thanks :)

**Comment by prydonius** [comment]
@zakkg3 good spot, would you want to send a PR to fix that? Otherwise I can send one (it will need to be changed in the site/docs/master, site/docs/v1.0.0 and probably also site/docs/v1.1.0-beta.2.

Also, we are now co-maintaining the chart (@nrb and I are listed as OWNERS: https://github.com/helm/charts/blob/master/stable/velero/OWNERS)!
