### ISSUE TITLE
Error creating Azure disk snapshots

### ISSUE THREAD

**Issue by timbuchwaldt** [heptio/ark#261]
When backing up our managed disk Azure PV we see the following error:
```
time="2017-12-21T13:11:30Z" level=error msg="error creating snapshot" backup=heptio-ark/rh-backup-5 error="rpc error: code = Unknown desc = disk.SnapshotsClient#CreateOrUpdate: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"NotFound\" Message=\"The entity was not found.\"" group=v1 groupResource=persistentvolumeclaims logSource="pkg/backup/item_backupper.go:306" name=pvc-$pvc_id namespace=staging volumeID=$volume-id
```

We also can't find a snapshot of the disk - any idea what we hold wrong here?

**Comment by ncdc** [comment]
Do you have the correct resource group? Are you using AKS?

**Comment by timbuchwaldt** [comment]
We are using a K8S deployed via ACE. We have two resource groups currently, one which contains our cluster, one that contains the Ark backups.

**Comment by ncdc** [comment]
You have to specify the RG where your cluster is

**Comment by ncdc** [comment]
What do you have specified for `AZURE_RESOURCE_GROUP` in your `cloud-credentials` secret - the one that contains your cluster?

**Comment by ncdc** [comment]
@timbuchwaldt were you able to resolve your issue?

**Comment by ncdc** [comment]
@timbuchwaldt checking in again - any luck?

**Comment by ncdc** [comment]
Closing due to age. Please feel free to reopen if you want to revisit this.
