### ISSUE TITLE
Document problem with restoring LoadBalancer Services

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#264]
The way that Kubernetes currently (<=v1.9.x) handles Services with type=LoadBalancer is it generates the name of the associate cloud resource (e.g. ELB) using the following formula:

`a<service UID, dashes removed, up to 31 characters>`, e.g. `a4149f70ee9dc11e68c3bacbc32c1ca8`

`UID` is a field set by the Kubernetes apiserver. It is not possible for a user to specify it.

When Ark restores a LoadBalancer Service, the Service's UID will change from its original value, meaning the identifier for the cloud load balancer resource changes too. If you have a DNS CNAME for yourapp.com that points at the DNS name of the cloud load balancer, it will likely become invalid post-restore, requiring you to update yourapp.com's CNAME pointer.

Need to document this.

TODO: link to Kubernetes issue (if it exists)

**Comment by ncdc** [comment]
Some cloud providers support reattaching to an existing IP via `spec.loadBalancerIP`, but not all of them do (e.g. AWS).

**Comment by ncdc** [comment]
xref:

https://github.com/kubernetes/kubernetes/pull/56832
https://github.com/kubernetes/kubernetes/pull/49903

**Comment by Bradamant3** [comment]
yeah, this is one I'm newly aware of for upstream also. Changing milestone to address sooner. Is anyone aware of newer work upstream to address? As of 1.12 I believe was still an issue (at least, is still documented as such)

**Comment by ncdc** [comment]
It is still an issue. There is https://github.com/kubernetes/kubernetes/pull/66589 which moves the implementation to be cloud provider specific, but it's more of a code reorganization to allow for future changes.

https://github.com/kubernetes/kubernetes/pull/64358 was an attempt to allow users to control the prefix used when naming LBs (in response to https://github.com/kubernetes/kubernetes/issues/62640), but it was closed with a suggestion to propose a KEP first.

**Comment by skriss** [comment]
FIxed by #1019
