### ISSUE TITLE
OpenShift

### ISSUE THREAD

**Issue by nevenr** [heptio/ark#267]
Hi,

is OpenShift officially supported and if not do you have plans to support it ?

Thanks.

Regards,
N.

**Comment by ncdc** [comment]
Hi @nevenr, as long as OpenShift supports CustomResourceDefinitions (CRDs), Ark should work on it just fine. I believe that means you'll need at least version 3.7.

**Comment by nevenr** [comment]
Hi @ncdc, thanks for response.
I will check with OpenShift guys about CRDs.
Regards,
N.

**Comment by ncdc** [comment]
Closing. Please reopen if you need to resume the discussion. Thanks!
