### ISSUE TITLE
[Azure] Failed to refresh the Token. Refresh request failed. Status Code = '404'

### ISSUE THREAD

**Issue by cj-anthony** [heptio/ark#269]
Hello,

I've been evaluating ark as a way to protect our kube clusters. We run in managed container services in Azure. I had everything working except persistent volume snapshots so I decided to blow away the ark namespace and start from scratch (kubectl delete namespace heptio-ark).

Ever since then I've been getting the following error when I try to start a pod.

**An error occurred: rpc error: code = Unknown desc = azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/locations?api-version=2016-06-01: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '404'**

I've checked the service principal that I'm using and it seems fine, I can use it to create and access other resources in Azure, even the storage account that ark is supposed to use. Can someone tell me what happening here? It looks like I'm trying to connect to the Azure management API and getting knocked back, which is weird as it worked once from the clean install.

**Comment by ncdc** [comment]
Hi @cj-anthony, is there any possibility that your cloud-credentials secret has the subscription specified incorrectly?

@skriss have you seen this before? @jimzim any suggestions?

**Comment by skriss** [comment]
I believe when I've seen this before it's because I've had bad data in the cloud-credentials secret. I would try checking all of the data in there or just re-creating it. Perhaps when you re-created it, one of the env vars that it uses was not set properly?

**Comment by cj-anthony** [comment]
Thanks everyone, it was as issue with those env vars. A few revs ago the azure tenant line vanished from my script and I only noticed it just now.

**Comment by skriss** [comment]
@cj-anthony great. I'll go ahead and close this issue but let us know if anything else comes up. thanks!
