### ISSUE TITLE
backup should not be aborted on error

### ISSUE THREAD

**Issue by nielsole** [heptio/ark#279]
I am currently evaluating ark and tested the backup & restore.

Apparently I ran into some race condition so that a PV was already deleted. 

`time="2018-01-10T15:30:20Z" level=error msg="backup failed" error="[persistentvolumes \"pvc-<redacted>\" not found, persistentvolumes \"pvc-<redacted>\" not found, persistentvolumes \"pvc-<redacted>\" not found, persistentvolumes \"pvc-<redacted>\" not found]" key=heptio-ark/initial-backup2 logSource="pkg/controller/backup_controller.go:258"`

The backup was subsequently aborted (I am not sure whether this was the reason, just a correlation). Wouldn't it be better to conclude the backup as far as possible and still show the backup as `Error` or `Partial`? 
Better to have something than to have nothing. Especially when the bigger the cluster gets, the more likely it is that there is some transient error.

**Comment by ncdc** [comment]
Hi @nielsole, thanks for your comments! This is similar to https://github.com/heptio/ark/issues/225#issuecomment-348226983. I think we'll probably want to make backups similar to restores, where we try to do as much as possible, recording warnings & errors along the way.

**Comment by nielsole** [comment]
hadn't seen that one. Thanks for the quick reply
