### ISSUE TITLE
Restore Persistent Disk with same name

### ISSUE THREAD

**Issue by domcar** [heptio/ark#280]
Hi,
i folowed the tutorial and i tried a backup with also a PV involved.
Everything worked out fine, backup, delete and restore.
I was wondering though, if it is possible to restore the persistent disk using the same name
it had originally instead of setting a new random one (i.e. restore-9e0e090a-e54d-4502-858d-d9251660a045)

Thanks

**Comment by ncdc** [comment]
Hi @domcar, thanks for your question! The Azure and GCP integrations currently have this behavior. I think it's safer to randomize the disk names. Imagine if you've done a backup and you want to clone it to a different namespace (which isn't quite supported yet for PVs - see #192). In this case, we have to have a unique disk name.

We could maybe consider adding a field to the restore spec indicating if you want to preserve the original disk names or not. We'd need to do some design to go along with that - right now when we create a new disk from a snapshot, our code doesn't have the original disk name (but it could).

Could you elaborate a bit on why you want the disk name unchanged?

@skriss @nrb thoughts?

**Comment by nrb** [comment]
Perhaps a compromise like the kubernetes generate name functionality? Keep the original name and append some random characters? That way the original disk and a restored version could be sorted together for easier visual inspection, especially if the use case is just making a copy. I think I'd still like to hear other use cases, though.

The challenge I would foresee with such an approach is that we'd have to have some way to know length limits for various providers, and the random suffix may not be terribly long.

**Comment by domcar** [comment]
I was thinking about metrics `diskname <-> last_snapshot_timestamp`
But in case of restore the diskname changes and my metrics wouldn't be right anymore.

I guess in the case the disk name is changing I should't get metrics about the disk instead I should use the PVC name

**Comment by ncdc** [comment]
That makes sense. Are you working on adding metrics to Ark?

**Comment by domcar** [comment]
Hi, no, i am working on a small script (external to ark)
