### ISSUE TITLE
Check for backup existence before trying to create it during backup sync

### ISSUE THREAD

**Issue by robbyt** [heptio/ark#281]
I'm using Ark 0.6.0, on GKE 1.8.6, It's working great (thank you for such a great tool)! Backups/restores are working correctly.

However, when I login to the GCP control panel, and click on "activity" (2nd tab on the main dashboard) I see the following errors:

![ark-gcp](https://user-images.githubusercontent.com/58051/34838618-c933eac0-f6cc-11e7-9554-f5e1aa53f762.jpg)

Here are the logs from this specific backup (I see nothing notable):
[ark.log](https://github.com/heptio/ark/files/1623598/ark.log)

I only have two schedules currently, and they're for different namespaces:
```
$ ark schedule get
NAME                 STATUS    CREATED                         SCHEDULE        BACKUP TTL   LAST BACKUP   SELECTOR
APP1-bidaily   Enabled   2017-12-27 18:28:38 -0500 EST   25 6,12 * * *   720h0m0s     5h ago        <none>
APP2-bidaily      Enabled   2017-12-27 18:27:29 -0500 EST   25 6,12 * * *   720h0m0s     5h ago        <none>
```

**Comment by ncdc** [comment]
I believe what you're seeing is attempts by the backup sync controller to synchronize backups stored in GCS back into Kubernetes. I would expect to see this once per backup every `backupSyncPeriod` (from `config/default`).

https://github.com/heptio/ark/blob/6712e2a9ec1faad7c5a4f9cce698446368aabbaa/pkg/controller/backup_sync_controller.go#L85

How many backups do you have? It seems a bit odd that you have so many errors from the same time 12:31.

**Comment by robbyt** [comment]
```
$ ark backup get | grep APP1 | wc -l
      32
```

**Comment by ncdc** [comment]
Ok, that makes sense then.

We could consider modifying the backup sync controller to query for the existence of a backup before trying to create it, if these log entries are of concern.

cc @skriss

**Comment by rosskukulinski** [comment]
`Failed` is a very strong word in application logs, and I can understand why @robbyt raised this issue.

Marking as a Bug and adding to v1.0.0 milestone for prioritization and scheduling.
