### ISSUE TITLE
Location constraint fails if `us-east-1` is envoked

### ISSUE THREAD

**Issue by lypht** [heptio/ark#284]
### Issue: 
When following the [AWS specific markdown](https://github.com/heptio/ark/blob/master/docs/cloud-provider-specifics.md#s3-bucket-creation) instructions to create a bucket, the command fails if the `us-east-1` region is called.

```
$ aws s3api create-bucket --bucket foo --region us-east-1 --create-bucket-configuration LocationConstraint=us-east-1

An error occurred (InvalidLocationConstraint) when calling the CreateBucket operation: The specified location-constraint is not valid
```

### Expected result: 
Bucket creation.

### Actual result:
Bucket creation fails with `invalidLocationConstraint`

### Steps to remedy: 
Remove the `create-bucket-configuration` flag when `us-east-1` is the desired region.  I realize this error is upstream in the aws-cli codebase, but instructions to circumvent this error may be helpful for others.

I'm submitting a small pr to notate this in the markdown.  Thanks!

**Comment by ncdc** [comment]
@lypht thanks, that does seem strange. Looking forward to your PR!
