### ISSUE TITLE
Put schedule manifests in version control?

### ISSUE THREAD

**Issue by jhedev** [heptio/ark#289]
At the company I'm working we currently follow GitOps like practices where we store the whole desired state in a git repository and use a deployment pipeline to apply this against the kubernetes cluster. 

Therefore I'd like to store ark schedules in a git repo as well instead of using the command line to manipulate it afterwards. Since I couldn't find any documentation about the schedules resource types except for the Go types I'm wondering if this is a good practice or if there is something that would prevent me from doing so.

**Comment by ncdc** [comment]
Hi @jhedev, you can run `ark schedule create ... -o yaml` to emit the schedule as yaml instead of uploading it to the apiserver. You can then check it in to source control. We have documentation for the `Backup` resource, and will be adding similar details for `Schedule` and `Restore` soon.

**Comment by jhedev** [comment]
Ahhh ...I could've probably found this on my own haha. Thanks for your quick help!

**Comment by ncdc** [comment]
No worries! Please let us know how things go for you - what you like, don't like, suggestions for improvement...

**Comment by ncdc** [comment]
Closing as the original question was answered. Feel free to reopen if needed.
