### ISSUE TITLE
[Feature Request] Ability to specify pattern for backup bulk deletion

### ISSUE THREAD

**Issue by rdodev** [heptio/ark#295]
Folks,

Would be great if `backup delete` had a `--pattern` flag, so that a user could do bulk delete with a PCRE pattern as follows `ark backup delete --pattern nginx*`

**Comment by ncdc** [comment]
I'd rather support `--all` and `-l, --selector` as that would be in line with `kubectl`

**Comment by rdodev** [comment]
Alignment with `kubectl` is a good point.

`--all` should be self explanatory

`--selector` what would users be selecting backups on? name?

**Comment by ncdc** [comment]
`--selector` would delete based on matching labels on the backups, just like with kubectl

**Comment by ncdc** [comment]
WIP PR in #336
