### ISSUE TITLE
User should be informed when restore is invalid

### ISSUE THREAD

**Issue by rdodev** [heptio/ark#297]
Presently a user could run the following command

`ark restore create threefiddy` which is a backup that doesn't exist.

Immediately the user receives the following feedback

```
Restore request "fiddy-20180203165643" submitted successfully.
Run `ark restore describe fiddy-20180203165643` for more details.
```

Which is true in the technical sense (i.e. the request was successfully completed), but deceiving in that the process will 100% fail because it's a non-existent backup. 

For the sake of UX, the command should at the very least check the backup exists, as a circuit breaker, before a success message is displayed on screen.

**Comment by ncdc** [comment]
@rdodev we did change the text from "restore created successfully" to "restore request submitted successfully", and we also made it a validation error if the backup doesn't exist (which you can see with `ark restore describe`). We can do 1 more thing - as part of `ark restore create`, we can check if the backup exists, and immediately return an error. Would that work for you?

**Comment by rdodev** [comment]
Yes, as I suggest at the end of the issue above, an existence check on the backup and using that as a circuit breaker would be very helpful to the user and the restore request isn't submitted at all, think of it as a pre-flight check.
