### ISSUE TITLE
Clarify kubeconfig message

### ISSUE THREAD

**Issue by Bradamant3** [heptio/ark#300]
in `pkg/client/factory.gol70` message is not clear. Questions:

"If unset, try the environment variable KUBECONFIG, as well as in-cluster configuration"
Are these meant to be alternatives to setting the path? Do you need both? Is either of them the default if not set? Or would you have to try one or the other for the command to succeed? In other words, does not specifying result in an error condition?
Or does the command look for a KUBECONFIG environment variable, and if not found then look for the path in the cluster config?
If it's the latter, the fix is fairly simple:
"If unset, tries the environment variable KUBECONFIG, and if not present, tries in-cluster configuration"
If not the latter, questions ^^ might help with clearer text.

**Comment by ncdc** [comment]
If you specify `--kubeconfig`, we use that.

If you don't specify `--kubeconfig`, we try the environment variable `KUBECONFIG`.

If the environment variable `KUBECONFIG` is not specified, we try the file `$HOME/.kube/config`, if it exists.

If none of the above conditions yielded a config, the last resort is to try what is called the "in-cluster config", which means we check to see if you're running in a pod, and if so, we use the pod's service account token.

**Comment by Bradamant3** [comment]
This now seems like a straightforward situation that needs neither doc nor changed messaging -- more an artifact of my failed understanding than a user need.
