### ISSUE TITLE
Document Azure AKS resource group requirements

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#306]
When you create an AKS cluster, you specify a resource group in which it should be created (let's call this RG1). When the AKS cluster is provisioned, the provisioning process creates a _second_ resource group, typically using a naming convention of `MC_<resource group name>_<cluster name>_<location>` (let's call this RG2).

Our documentation doesn't mention RG2 and only states to use RG1 as the value for `AZURE_RESOURCE_GROUP`. If you do this, disk snapshots will fail, because the Azure disk client won't be able to find the disks in RG1. They're actually in RG2.

We need to call out that if you're using AKS, the value of `AZURE_RESOURCE_GROUP` must be RG2 (the `MC_...` resource group created by/for the AKS cluster).

**Comment by ResDiaryLewis** [comment]
There's still a typo [here](https://heptio.github.io/ark/v0.8.1/azure-config), or at least some confusion for me. 
>2. Set the name of the Resource Group **that contains your Kubernetes cluster.**

but also:

> WARNING: AZURE_RESOURCE_GROUP must be set to the name of the second resource group that is created when you provision your cluster in Azure. **Your cluster is provisioned in the resource group that you specified when you created the cluster.** Your disks, however, are provisioned in the second resource group.
