### ISSUE TITLE
[Feature Request] PV identifiers as tags on snapshots

### ISSUE THREAD

**Issue by rbowlby** [heptio/ark#307]
It would be helpful if specific identifying information of the PV were included in a tag on the snapshot. For the sake of snapshot auditing and cost attribution.

**Comment by ncdc** [comment]
@rbowlby what sort of information are you looking for? I think on Slack you said pod name?

**Comment by kaspernissen** [comment]
+1 on this
@ncdc would be great with the pod name and maybe some more details on the namespace, cluster. Similar to the tags that are added to the volume when using pv/pvs in Kubernetes such as:

- KubernetesCluster
- Name (at least on AWS it's easier to get an overview of your snapshots when they include at Name tag. 
- Pv-name
- Pvc-name
- Pvc-namespace.

**Comment by kaspernissen** [comment]
This issue seems to be related to https://github.com/heptio/ark/issues/278
