### ISSUE TITLE
GKE: Explicitly instruct user to add `Kubernetes Engine Cluster Admin` to IAM if the user is currently an `Owner`

### ISSUE THREAD

**Issue by lypht** [heptio/ark#330]
As an organization `owner`, deployment fails if the users is not also identified as `Kubernetes Engine Cluster Admin`.  Although this is indicated as a requirement in the docs, traditional org `Owner`s may not realize they need to add this IAM policy to succeed.

**Comment by ncdc** [comment]
@lypht I have never had to explicitly add that permission (the only role I currently have on my account is `Owner`).

You do have to run `kubectl create clusterrolebinding <name> --clusterrole cluster-admin --user <your gcloud username/email>` before you can run `kubectl apply -f examples/common/00-prereqs.yaml`. Is that what you mean?

**Comment by lypht** [comment]
Yes, that clusterrolebinding requirement is not as clear to an owner (for me, at least) who otherwise is able to modify clusters at will.  Without it (or without the `Kubernetes Engine Cluster Admin` addition to IAM for the user in question), everything gets created but for the `ark` clusterrolebinding (lack of permissions):
```$ kubectl apply -f examples/common/00-prereqs.yaml
customresourcedefinition "backups.ark.heptio.com" created
customresourcedefinition "schedules.ark.heptio.com" created
customresourcedefinition "restores.ark.heptio.com" created
customresourcedefinition "configs.ark.heptio.com" created
customresourcedefinition "downloadrequests.ark.heptio.com" created
namespace "heptio-ark" created
namespace "heptio-ark-server" created
serviceaccount "ark" created
clusterrolebinding "ark" created <---This fails
```

**Comment by ncdc** [comment]
@lypht can you retest and verify if you're still running into this?

**Comment by lypht** [comment]
@ncdc The docs are clearer at this point.  Closing this issue.  Thanks.
