### ISSUE TITLE
Adjust docs to indicate that Ark can run on-prem and in the cloud

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#332]
Right now it sounds like the only real production target for Ark is a Kubernetes cluster running on one of the cloud providers. Let's adjust the documentation so it's clearer that it can run on premises as well.

cc @lypht

**Comment by ncdc** [comment]
We are planning on updating the documentation this week to make it clearer how to run on prem.

**Comment by mehemken** [comment]
Any word on this?

Does a deployment file exist for just the Ark server on bare metal Kubernetes?

**Comment by jonaskello** [comment]
Although the docs were updated in #880, I still cannot find any setup instructions for bare-metal. There are sections on how to setup for many of the cloud providers, but I did not find a section for bare-metal/on-premise.

**Comment by fei922** [comment]
@ncdc Could you give me the link  about velero installation on bare-metal k8s cluster.

**Comment by nrb** [comment]
@fei922 The minio docs at https://velero.io/docs/v1.1.0/get-started/ are a good starting point.

**Comment by fei922** [comment]
@nrb Thank you very much.
