### ISSUE TITLE
Support writing backup items as yaml

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#337]
We hardcode json but should support yaml too.

**Comment by ncdc** [comment]
Probably need to add a format field to the backup spec

**Comment by sanketjpatel** [comment]
I'll take this up

**Comment by ncdc** [comment]
FYI if you need to pull in any new vendor dependencies, we have a script called `hack/dep-save.sh` for that.

**Comment by rosskukulinski** [comment]
I'm not sure I understand why this is a helpful feature.  Do we provide (or plan to provide) any guarantees about the formatting/structure of backup files?  Should end-users be interacting with the raw contents of a backup?

**Comment by ncdc** [comment]
This was originally something that @kris-nova asked about.

I would like for us to offer guarantees around the format of backup tarballs. We have a backup version field that we set, and in the event we need to modify the format, I would expect us to increment this value, and have code that is backwards compatible to older format versions (with some sort of EOL).

We also offer `ark backup download` to retrieve the backup tarball.

**Comment by rosskukulinski** [comment]
@ncdc I'm ok with this, but do worry that this increases the scope we have to worry about regarding versioning & compatibility.  We would need to lock this in prior to cutting a 1.0

**Comment by ncdc** [comment]
I don't think this adds too much complexity, but if it becomes too much of a burden, we can punt on it.

**Comment by ncdc** [comment]
Going to close as this will add complexity and we're not sure that it's worth it. If anyone feels strongly otherwise, please let us know.
