### ISSUE TITLE
ark plugin commands need to operate against the server's namespace

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#340]
Now that the ark server runs in a separate namespace from the backups/restores/schedules, `ark plugin add/remove` attempts to modify the ark deployment in the wrong namespace. A workaround is to run `ark plugin add <plugin> -n heptio-ark-server`, but it would be ideal not to have to specify this.

We may want to consider adding a `server-namespace` setting to `ark client config` (along with a default to `heptio-ark-server`) and have the plugin commands use this value.

**Comment by nrb** [comment]
I'm in favor of adding a `server-namespace` setting that various pieces can use.

**Comment by skriss** [comment]
@ncdc @nrb see any reason to keep this open now that we're back to a single namespace?

**Comment by ncdc** [comment]
Nope!

**Comment by ncdc** [comment]
Fixed by #383
