### ISSUE TITLE
Persona placeholder

### ISSUE THREAD

**Issue by lypht** [heptio/ark#351]
This issue is to capture the desire to document and demonstrate utilization of ark for the administrator group primarily for disaster recovery, while independently documenting and demonstrating utilization of ark for an end-user interested in mirroring a specific environment for a temporary purpose (a read-only restoration, if you will).  The use cases differ enough that these separate document/walkthrough paths might help to increase adoption of ark.

**Comment by Bradamant3** [comment]
@lypht Good callout. I've been thinking of expanding the two use cases here into tutorials that roughly would match the two personas you describe: https://heptio.github.io/ark/master/use-cases

... although the cluster migration scenario doesn't quite address your end-user persona.

WDYT?

Nice thought to reframe in terms of personas. Do you have thoughts about how a persona framing would be different from a use case framing? (Just curious -- not asking you to do my job ;) )

**Comment by lypht** [comment]
I definitely think the use-cases can driving the correct perspectives. Yet unless someone considers the possibility of near-instant mirrors of various environments (dev, stage, UAT, load, QA, etc.), they may not conceptualize all of the potential of `ark`.  

A developer persona walk-through illustrating a method by which  a dev who wants to make her PR environment available for load-testing without impacting her existing environment, could share endpoints to an ark-generated deployment for that separate purpose.  This is obviously future use, and would hopefully be chatOps or gitOps enabled to include purging the environment when its purpose is fulfilled, but the potential remains.

**Comment by skriss** [comment]
We'll cover the use cases as part of #980 for 1.0; closing this issue as a dupe.
