### ISSUE TITLE
Cross-resource group volume restores don't work for Azure

### ISSUE THREAD

**Issue by skriss** [heptio/ark#352]
In Azure, all resources are contained within a resource group (RG). If a user takes a backup, including PV snapshots, in Cluster A, which is contained in RG A, then tries to restore it into Cluster B, which is contained in RG B, this will fail. The issue is that we take a resource group as part of the cloud-credentials secret for Azure, and this value is used for both fetching snapshots and creating volumes.

We need to keep track of the RG where the snapshot exists so that we can correctly locate it. We could do this by capturing the full resourceID of the snapshot in VolumeBackupInfo and using that when restoring.

**Comment by skriss** [comment]
I was able to get this working by storing the full snapshot URI rather than just the name within the backup status, and parsing it during restore to figure out which RG the snapshot was coming from.

**Comment by stephenlawrence** [comment]
@skriss Is this something I can do? Or code-related?

**Comment by stephenlawrence** [comment]
Something like this?

```
"status": {
    "version": 1,
    "expiration": "2018-04-05T00:36:26Z",
    "phase": "Completed",
    "volumeBackups": {
      "pvc-9b7fa5fc-20d2-11e8-af30-000d3a1d304f": {
        "snapshotID": "/subscriptions/SUBID/resourceGroups/MYRGNAME/providers/Microsoft.Compute/snapshots/MYRGNAME-dynamic-pvc-9b7fa5fc--2f3bba47-310a-4078-85de-269b844a2d41",
        "type": "Premium_LRS"
      },
```

**Comment by skriss** [comment]
@stephenlawrence we'll have to make a code change to support this; the restore process won't work correctly if it finds a snapshotID with the format you provided. I'll review the proposed code change with @ncdc today.
