### ISSUE TITLE
How to define StorageClass for minio

### ISSUE THREAD

**Issue by 27149chen** [heptio/ark#361]
Hi,
I'm trying the example nginx app with pv.  It need a storageclass first. I'm using minio as the provisioner, so I defined a storgecalss with provisioner aws-ebs and without any parameters. But when I deploy the example nginx application, it failed with error `Failed to provision volume with StorageClass "default": Failed to get AWS Cloud Provider. GetCloudProvider returned <nil> instead`
Could anyone tell me what is wrong? I can't find this part in the guide.

**Comment by ncdc** [comment]
@27149chen are you running in EC2? When you use Minio, it's as an S3-compatible object storage provider, and that's where the backup tarballs are uploaded. There is no PV aspect to Minio - you need something else to provide PV capabilities, such as running in EC2, GCE/GKE, ACS/AKS.

**Comment by 27149chen** [comment]
Oh, I see. @ncdc , thanks for your expaination. So minio is meaningless when PV is involved, right?

**Comment by ncdc** [comment]
It's not 100% meaningless 😄; it just has a different role. Ark has 2 storage aspects - Kubernetes objects, and persistent data. We use an object store for the Kubernetes objects (S3, Minio, Google Container Storage, Azure Blob Store), and we tap into the cloud providers for PV snapshots.

**Comment by 27149chen** [comment]
Yes, I mean that if you use a cloud provider for persistent data, you'd better to store the Kubernetes objects in it too, isn't it?

**Comment by 27149chen** [comment]
@ncdc  When I backup a service with type NodePort and restore it to another cluster, I find that the nodePort ip setting is gone, is it as designed?

**Comment by ncdc** [comment]
@27149chen for the moment, yes - I recently filed #354 to discuss this.

**Comment by ncdc** [comment]
@27149chen do you have anything further on this or is it ok to close?

**Comment by ncdc** [comment]
Closing due to age. Please feel free to reopen if you need to!
