### ISSUE TITLE
Permanently exclude restoring events

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#367]
We back up but don't ever restore nodes. Should we consider doing the same with events?

cc @lypht @jrnt30 @jbeda @skriss @nrb @paulbouwer

**Comment by jbeda** [comment]
Meh -- I have a hard time seeing that being a good idea. A lot of times they'll have details that don't apply to the current cluster. I could see it causing more confusion than helping.

**Comment by ncdc** [comment]
That's my thinking too

**Comment by skriss** [comment]
Yeah, I almost always exclude them from restores if I remember to - often I think they don't even restore properly.

**Comment by ncdc** [comment]
Add `events` to `nonRestorableResources` in `pkg/controller/restore_controller.go`

**Comment by sanketjpatel** [comment]
I'd like to give this a try over the weekend if it's not super urgent

**Comment by ncdc** [comment]
@sanketjpatel that would be fantastic! Please do!
