### ISSUE TITLE
Can we take backup of only data from persistent volumes

### ISSUE THREAD

**Issue by akgunjal** [heptio/ark#377]
Hello, I have a usecase where I need to only take backup of my data present on persistent volumes onto the object storage. Then restore the data back to same or other persistent volume later. Is this supported in ark.

**Comment by ncdc** [comment]
Hi @akgunjal, it is possible to do data-only backups, like so:

```
ark backup create my-backup --include-resources pvcs,pvs
```

This creates snapshots of your cloud disks (e.g. an EBS snapshot for AWS). It does not store the data from the PVs in object storage. When you're restoring, 1 thing to note is that we don't currently support restoring a backed-up PV into the same cluster if the PV still exists in the cluster. In other words, if you have a PV `foo`, and you use Ark to back it up, the restore will fail if `foo` is still there. This is tracked in #192.

Depending on your backup/restore needs, you may have to do some manual edits to your deployments/pods/etc as part of the restore. If you can give us more details about your desired restore process/flow, we can try to help.

We are also working on a new feature that will be able to back up any directory from a container into object storage (#19), so if that's what you're looking for, we hope to release it in v0.8.0.

**Comment by akgunjal** [comment]
@ncdc : I looked into the ark code and understood that it supports only block storage to take snapshots of PVs. And there are few plugins like aws, azure, gcp which can be used. However, our use case is we do not need to take backup of PV like a snapshot. 

Ideally we would want to take backup of our data from the containers onto the object storage. so I think the task #19 is what we are more interested. But does this feature also allow to restore the data from object storage back inside the container to the directory of user's choice?

**Comment by ncdc** [comment]
@akgunjal let's move the conversation over to #19 - thanks!
