### ISSUE TITLE
Percona XtraDB Cluster Restoration Fails

### ISSUE THREAD

**Issue by stephenlawrence** [heptio/ark#380]
We have a 3-node percona xtradb cluster with persistence in our kubernetes stack and when we backup/restore the first percona node to come up complains that it was not the last one up prior to shutting down:

```
...
2018-03-14T20:57:07.199058Z 0 [ERROR] WSREP: It may not be safe to bootstrap the cluster from this node. It was not the last one to leave the cluster and may not contain all the updates. To force cluster bootstrap with this node, edit the grastate.dat file manually and set safe_to_bootstrap to 1 .
2018-03-14T20:57:07.199064Z 0 [ERROR] WSREP: Provider/Node (gcomm://) failed to establish connection with cluster (reason: 7)
...
```

The container remains in CrashLoopBackoff

https://github.com/kubernetes/charts/tree/master/stable/percona-xtradb-cluster

**Comment by stephenlawrence** [comment]
Should we assume that node-0 will be restored and have its disk re-attached before node-1?

**Comment by stephenlawrence** [comment]
I tried to stand up the cluster so that each percona node was on its own VM with its own volume but that did not end up making a difference. It still seems to be restoring the volumes into pods that are expecting a different volume.

**Comment by stephenlawrence** [comment]
Ok, I will give it a shot.

**Comment by stephenlawrence** [comment]
@skriss How did you edit the grastate.dat file when the pod is in crashloopbackoff?

**Comment by stephenlawrence** [comment]
I ended up SSH'ing into the node/host the pod was running on, finding the pod volume mount on the host and editing the grastate.dat file.

**Comment by skriss** [comment]
Yeah, that's what I did as well.

**Comment by stephenlawrence** [comment]
@skriss Yes, I was able to start-up the restored percona xtradb cluster after editing that file on the 0-node.

**Comment by ncdc** [comment]
@skriss do you think we could use a pre hook to edit the state file before we snapshot the pv?

**Comment by ncdc** [comment]
cc @rosskukulinski - workload-specific backup/restore issues.

**Comment by skriss** [comment]
We'll be evaluating general Ark statefulset support as part of #666.  Closing this specific issue as resolved.
