### ISSUE TITLE
Throw a better error message when invalid restore name specified

### ISSUE THREAD

**Issue by containscafeine** [heptio/ark#389]
Upon providing an invalid restore name, I'd expect an error message like - `An error occurred: invalid restore name`, but current I get the following.

```console
$ ark restore logs random
An error occurred: request failed: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key></Key><BucketName></BucketName><Resource>/ark/random/restore-random-logs.gz</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
```

**Comment by ncdc** [comment]
Good idea. We can copy and adjust this to do it for the restore:

https://github.com/heptio/ark/blob/3063d33d713ef51e933aff55ffd1258e676159aa/pkg/cmd/cli/restore/create.go#L125-L128
