### ISSUE TITLE
An error occurred: unknown flag: --from-backup

### ISSUE THREAD

**Issue by nabadger** [heptio/ark#390]
This is after following the example on the README.md file.

Running the command:

```
ark restore create --from-backup nginx-backup
```
I downloaded the latest version of ark: Version: v0.7.1

**Comment by ncdc** [comment]
Please see our docs for v0.7.1: https://heptio.github.io/ark/v0.7.1/. The `--from-backup` flag is only available if you build from the `master` branch.

**Comment by nabadger** [comment]
@ncdc Ok great - thanks
