### ISSUE TITLE
Feature request: restore Azure snapshots across regions (VHD export/import)

### ISSUE THREAD

**Issue by danilina-wsib** [heptio/ark#399]
I was migrating a namespace on Azure AKS between two clusters.
Ark is installed on both cluster and point to the same Azure storage account and blob
Created a backup on cluster 1.
Restored the backup on cluster 2.
Error message in the restore object:
  Cluster:  error executing PVAction for /tmp/711011778/resources/persistentvolumes/cluster/pvc-8531c5a7-0a9e-11e8-bb43-0a58ac1f1285.json: rpc error: code = Unknown desc = disk.DisksClient#CreateOrUpdate: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="The entity was not found."
The created PVC shows LOST status

**Comment by danilina-wsib** [comment]
The new PVC has exactly the same volumeName as the original PVC. Does not look like the volume was restored from a snapshot

**Comment by danilina-wsib** [comment]
Using release 0.7.1

**Comment by ncdc** [comment]
@danilina-wsib I'm pretty sure this is the issue we fixed with #356, which is not yet in a released version. Each AKS cluster is in its own resource group, so prior to 356, you couldn't restore PVs across AKS clusters.

**Comment by danilina-wsib** [comment]
@ncdc I've tried it with the current master version - the Azure disk was restored and K8S volume bound to the PVC, but the pod fails to start with the following error message:

  Warning  FailedMount            1m    attachdetach-controller            AttachVolume.Attach failed for volume "pvc-8531c5a7-0a9e-11e8-bb43-0a58ac1f1285" : Attach volume "restore-7c3929e5-c3a2-443a-b71f-01a3676530ea" to instance "aks-agentpool-37961535-1" failed with compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="The entity was not found."
  Warning  FailedMount            1m    kubelet, aks-agentpool-37961535-1  Unable to mount volumes for pod "jenkins-jenkins-dc5bb78b4-zwq7j_jenkins(ffe0ceed-2e07-11e8-af34-0a58ac1f11ac)": timeout expired waiting for volumes to attach/mount for pod "jenkins"/"jenkins-jenkins-dc5bb78b4-zwq7j". list of unattached/unmounted volumes=[jenkins-home]

**Comment by danilina-wsib** [comment]
I see that the Azure Disk was restored in the original cluster location, while the new cluster is another location, I guess this is what caused it

**Comment by danilina-wsib** [comment]
I would like to add a new feature request - support restoring Azure disks to another location (region) by moving a VHD image
This is possible to do with Azure scripts, would be nice if Ark was capable of doing it, most realistic use cases would involve clusters running in different regions

**Comment by nrb** [comment]
@danilina-wsib Your latest request sounds a lot like https://github.com/heptio/ark/issues/103, which we're actively designing for the 3 big cloud providers. Given that, this issue now seems redundant - would you agree?

**Comment by danilina-wsib** [comment]
@nrb Yes, I agree, I am closing this issue now
