### ISSUE TITLE
ark restore failed with error

### ISSUE THREAD

**Issue by jayachandralingam** [heptio/ark#407]
I have created a backup of a namespace and then deleted the namespace to perform the test, the concern test results as below when I describe the ark restore.

Result: 
```
Errors:
  Ark:      backup does not contain top level resources directory
  Cluster:    <none>
  Namespaces: <none>
```

**Comment by ncdc** [comment]
Hi @jayachandralingam, just following up - could you please let us know what series of commands you ran?

**Comment by jayachandralingam** [comment]
Hello Andy,

I had a sample deployment with a load balancer (Azure) in a specific namespace.

Created backup using command like
`ark backup create --namespace mynamespace`

Deleted all the namespace along with it's resources, verified the status after deletion also identified that files and folders in azure blob storage with respective backup names in the container and that data together is less than 1MB.

For restore I have used the command like 
`ark restore create mybackup`
When I describe the ark restore identified the error as below 
```
Errors:
  Ark:      backup does not contain top level resources directory
  Cluster:    <none>
  Namespaces: <none>

```

Let me know if anything more required on this.

**Comment by ncdc** [comment]
@jayachandralingam could you please provide the logs from the backup (`ark backup logs <NAME>`) and the logs from the Ark server at the time you took the backup (`kubectl -n heptio-ark-server logs deploy/ark`)?

It sounds like your backup ended up backing up nothing. Is there any chance you had a typo when specifying the namespace to back up?

**Comment by ncdc** [comment]
@jayachandralingam checking in again to see if you can provide more details?

**Comment by ncdc** [comment]
Closing due to age. If you'd still like us to assist, please reopen the issue. We're here to troubleshoot if you need it!

**Comment by spoorthikh** [comment]
Please reopen this issue ,I am facing same issue in velero latest version(1.00-rc.1)

**Comment by skriss** [comment]
@spoorthikh could you please open a new issue with the specifics of the problem you're facing? thanks.
