### ISSUE TITLE
restore says complete, but actually had error

### ISSUE THREAD

**Issue by djschny** [heptio/ark#41]
It appears if a "sync" period has not happened yet, then a restore actually fails, but the ark command says it is successful:

```
NAME                         BACKUP        STATUS      WARNINGS   ERRORS    CREATED                         SELECTOR
everything4-20170814154904   everything4   Completed   0          1         2017-08-14 15:49:04 +0000 UTC   <none>
```

However the logs show the following and nothing was restored:
```
I0814 15:49:04.807551       1 restore_controller.go:183] processRestore for key "heptio-ark/everything4-20170814154904"
I0814 15:49:04.807723       1 restore_controller.go:190] Getting restore heptio-ark/everything4-20170814154904
I0814 15:49:04.807759       1 restore_controller.go:211] Cloning restore heptio-ark/everything4-20170814154904
I0814 15:49:04.812273       1 restore_controller.go:242] running restore for heptio-ark/everything4-20170814154904
E0814 15:49:04.812364       1 restore_controller.go:284] error getting backup: backup.ark.heptio.com "everything4" not found
I0814 15:49:04.812450       1 restore_controller.go:246] restore heptio-ark/everything4-20170814154904 completed
I0814 15:49:04.812476       1 restore_controller.go:249] updating restore heptio-ark/everything4-20170814154904 final status
```

The backup `everything4` is in the bucket, but a sync hasn't happened yet so if you do an `ark backup get` you only see the following:

```
[ec2-user@ip-172-31-25-73 ~]$ ark backup get
NAME          STATUS      CREATED                         EXPIRES   SELECTOR
everything3   Completed   2017-08-14 15:39:35 +0000 UTC   23h       <none>
```

IMO seems like two things should be happening?:
* if an error like the one shown above happens the restore should not be marked as `Completed`
* when a request to create a store happens, it should force a sync

**Comment by ncdc** [comment]
@djschny if we process the restore and do as much with it as we can, it is marked `Completed`. Maybe `Processed` or some other word would be better, but we chose not to have `Completed` vs `Failed` because it's possible to restore some items and have errors restoring others, and `Failed` sounds like nothing at all happened.

Now, in your case, nothing did work due to the missing backup. We should probably adjust it so that an attempt to restore a non-existent backup is `FailedValidation`.

**Comment by djschny** [comment]
OK, that brings to light an additional questions of:

* can a separate status code be returned for when it is a partial restore? As a user, to have to look through logs to find this information out can be difficult when trying to diagnose/automate/monitor this activity

I think regardless forcing a sync prior helps eliminate a lot of timing issues as well. Happy to open a separate issue on that one if you want to keep this focused on status codes

**Comment by ncdc** [comment]
> can a separate status code be returned for when it is a partial restore? As a user, to have to look through logs to find this information out can be difficult when trying to diagnose/automate/monitor this activity

Maybe, but you don't have to look through logs - this information is available via `ark restore get` (you see the # of warnings and errors listed per restore) and `ark restore get <restore name> -o yaml (or json)` (the warnings and errors are all visible)

> I think regardless forcing a sync prior helps eliminate a lot of timing issues as well. Happy to open a separate issue on that one if you want to keep this focused on status codes

I don't think forcing a sync is the right way to go about this. If you create a backup, it's immediately available for restoration. If you are trying to restore a backup from cluster A into cluster B, as soon as you start Ark in B, it syncs. The window in which cluster B doesn't know about preexisting backups in object storage is small.

What were you doing where you ended up in this situation?

**Comment by djschny** [comment]
> Maybe, but you don't have to look through logs - this information is available via ark restore get (you see the # of warnings and errors listed per restore) and ark restore get <restore name> -o yaml (or json) (the warnings and errors are all visible)

Thanks, yes I do see that and in a more structured manner, that is more usable for sure. Thank you.

```
  "status": {
    "phase": "Completed",
    "validationErrors": null,
    "warnings": {
      "ark": null,
      "cluster": null,
      "namespaces": null
    },
    "errors": {
      "ark": null,
      "cluster": [
        "backup.ark.heptio.com \"everything4\" not found"
      ],
      "namespaces": null
    }
  }
```

> What were you doing where you ended up in this situation?

I had two clusters, they already both had ark installed on them. I made a backup on cluster1 and then went to go restore it on cluster2.

**Comment by ncdc** [comment]
> Thanks, yes I do see that and in a more structured manner, that is more usable for sure. Thank you.

Great! Other than the sync issue, do you still need this open? Do you think a name like `Processed` is better than `Completed`?

> I had two clusters, they already both had ark installed on them. I made a backup on cluster1 and then went to go restore it on cluster2.

Ok. The sync interval is configurable but you can't issue a command to force a sync at the moment. You could restart the ark pod and that would force it. Or you just have to wait for the next sync interval to occur.

Syncing has a cost associated with it (the remote calls out to object storage to list a bucket are relatively inexpensive but can add up over enough time). Let's move to #42 for the sync discussion.

**Comment by djschny** [comment]
Yep, sounds good, let's take the user experience of sync'ing and that architecture to the other ticket and this one can be closed. Thank you for the help and dialogue.
