### ISSUE TITLE
AWS permissions in docs wrong for s3:AbortMultipartUpload

### ISSUE THREAD

**Issue by hopkinsth** [heptio/ark#416]
I'm filing this issue in part to remind myself to submit a PR for this later today: the `s3:AbortMultipartUpload` permission is not in the right place in docs/aws-config.md. [Aborting a multipart upload is an object- and **not** bucket-level permission](https://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadAbort.html).

I'm not sure there's a circumstance where `ark` would submit a multipart upload, but in the interest of correctness this should be changed so that AbortMultipartUpload appears in this policy statement in the docs (docs/aws-config.md):

```json
{
    "Effect": "Allow",
    "Action": [
        "s3:GetObject",
        "s3:DeleteObject",
        "s3:PutObject",
        "s3:AbortMultipartUpload"
    ],
    "Resource": [
        "arn:aws:s3:::${BUCKET}/*"
    ]
}
```

I have AWS's policy UI checker thing to thank for noticing this.

**Comment by ncdc** [comment]
Thanks @hopkinsth! Looking forward to the PR to fix this.
