### ISSUE TITLE
Decide how to handle trying to restore a backup resource that isn't currently in kube storage

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#42]
xref #41 

Summary: if you `ark restore create` a backup that is in object storage but has not yet synced to kube storage, the restore will be marked `Completed` with 1 error that the backup couldn't be found. If nothing else, this should be a validation error. Or we could force a backup sync, and if we still can't find the backup, consider it an error.

@skriss wdyt?

**Comment by djschny** [comment]
Below are my thoughts/rationale one why this not producing an error and instead working are as follows:

* It creates the favored end user experience. The sync'ing approach is essentially implementation details at this point and shouldn't affect end functionality.
* I don't see much "harm" in looking for a particular S3 object when a command is run like this. The end user is intended for something to happen.

**Comment by ncdc** [comment]
Yeah, I think we can try to do a one-off sync in this situation.

**Comment by skriss** [comment]
This is basically just an issue when you first connect a new cluster to an existing backup set, right? We should probably trigger a sync at server startup in that scenario (right now we wait for the sync period to elapse before syncing, which doesn't seem right).

**Comment by ncdc** [comment]
The backup sync controller syncs immediately at startup, unless something changed recently.

I think @djschny's case was two active clusters, both pointed at the same bucket. Create backup in cluster 1. Try to restore "immediately"/quickly into cluster 2, before it has synced.

**Comment by skriss** [comment]
ah you are right, nvm. triggering a sync seems reasonable. we'll have to trigger a cache refresh as well.

**Comment by ncdc** [comment]
I think we can do a one-off to try to grab the backup from object storage and create it in kube storage.

**Comment by ncdc** [comment]
@skriss looking more at the code in pkg/restore, we only use the data from the Backup for the custom PV restorer (to get the volume/snapshot info), although theoretically any other custom restorers could use the Backup data as needed in the future.

How about we do this:

1. Look for the Backup in the lister
1. If we find it, use it
1. Otherwise
    1. Have the restore controller try to get the backup from the BackupService (something like `GetBackup(bucket, name string, liveLookup bool)`)
    1. Try to create the Backup in kube storage (so it's there sooner rather than later)
    1. Use the retrieved Backup from (3.i.) for the restoration

**Comment by skriss** [comment]
FYI: I'm working on this.
