### ISSUE TITLE
Add backoff for GC attempts on backups

### ISSUE THREAD

**Issue by skriss** [heptio/ark#423]
A user reported that they were hitting AWS API limits as a result of Ark continually trying to GC a backup for which one of the snapshots had already been manually deleted.

I think what's happening here is:
- GC controller is regularly re-syncing, i.e. re-adding all backups to queue
- if an item in the queue has expired, GC controller creates a `DeleteBackupRequest` for it
- since the creation of the DBR succeeds, the backup is not re-added back to the GC queue
- GC controller re-syncs and adds it back to the queue
- etc.

We should be backing off on re-issuing DeleteBackupRequests for backups if prior DBRs have not successfully deleted the backup.

Separately (already being tracked elsewhere) we shouldn't fail a DBR if one of the snapshots has already been deleted.

**Comment by ncdc** [comment]
Sounds like a good idea. We should maybe also consider removing the backup informer event handler in the gc controller. That allows us to immediately check if a backup is deleted whenever the backup is added or updated. I'm not sure that's particularly valuable, especially given we have the periodic resync that checks all backups.

FYI the default rate limiter we're using is the max of:
1. a per-item exponential backoff that starts at 5ms and caps at 1000s
1. an overall token bucket for the entire queue, that fills 10 tokens/second up to a capacity of 100

This means that for unique backups, we'd be able to sustain processing 10 per second (and it could burst up to 100 at a time, if the bucket is full of tokens). For an individual, specific backup, it would wait 5ms, then 10ms, 20ms, 40ms, 80ms, ... up to 1000s.

**Comment by ncdc** [comment]
We discussed this and don't believe it's an issue since the conversion to `DeleteBackupRequests`. Please let us know if anyone is having problems and we can revisit.
