### ISSUE TITLE
AWS compatible support no longer working

### ISSUE THREAD

**Issue by jrnt30** [heptio/ark#44]
First off, thanks for the interesting project, appreciate the effort. I was walking through the tutorial for using Ark w/ Minio and a PV backup. 

I believe that commit #35 has broken support for AWS compatible services, such as Minio, as it is now attempting to actually validate the EC2 AZs and is using the `minio` region which does not exist.  

Looking into the code, the endpoint resolver is setup to deal with this for S3 however other services are explicitly not being supported. 

Steps to reproduce: 
- Follow the examples with the Minio provider. 

Outcome: 
- Ark server errors with: 

```
caused by: Post https://ec2.minio.amazonaws.com/: dial tcp: lookup ec2.minio.amazonaws.com on 10.0.0.10:53: server misbehaving
```

**Comment by ncdc** [comment]
@jrnt30 thanks for reporting this. We'll get a fix out ASAP. In the meantime, if you use the latest published image, everything should be working.

**Comment by jrnt30** [comment]
Thanks, I just reverted back to a previous commit.  Was trying to tackle #33 to get my hands on the code

**Comment by ncdc** [comment]
@jrnt30 awesome, glad to hear you're interested in contributing!

**Comment by ncdc** [comment]
Ooh I might have a better idea. Assuming we merge #43, we could only validate the AZ if the PersistentVolumeProvider is configured, and for a minio-only use case, you wouldn't have that configured, so we should be good. WDYT @skriss?

**Comment by skriss** [comment]
argh. Yeah - I like the latter the best, given that AZ is only used for volume operations.

**Comment by ncdc** [comment]
Cool, can you do that as part of #43?
