### ISSUE TITLE
Cannot restore to scheduled backup by schedule name

### ISSUE THREAD

**Issue by marpaia** [heptio/ark#440]
I have one cluster in my environment scheduled to run a backup every 5 minutes. I did this via:

```
$ ark schedule create control-plane --schedule=" 0/5 * * * *" --include-namespaces=global,edge,operations,shared
```

This works, I'm getting backups that I can see from other clusters in this environment:

```
$ ark get backups
NAME                           STATUS      CREATED                         EXPIRES   SELECTOR
control-plane-20180420014525   Completed   2018-04-19 19:49:47 -0600 MDT   29d       <none>
control-plane-20180420014025   Completed   2018-04-19 19:49:47 -0600 MDT   29d       <none>
$
```

Now the help says that I can omit the timestamp:

```
$ ark create restore -h
Create a restore

Usage:
  ark create restore [RESTORE_NAME] --from-backup BACKUP_NAME [flags]

Examples:
  # create a restore named "restore-1" from backup "backup-1"
  ark restore create restore-1 --from-backup backup-1

  # create a restore with a default name ("backup-1-<timestamp>") from backup "backup-1"
  ark restore create --from-backup backup-1
```

When when I omit the timestamp when trying to restore from another cluster, I get an error that the backup isn't found:

```
$ ark create restore control-plane --from-backup control-plane
An error occurred: backups.ark.heptio.com "control-plane" not found
```

**Comment by skriss** [comment]
Unfortunately not right now, sounds like a great feature though! something like `--from-schedule control-plane` with a way to specify latest, 2nd-latest, etc.  That'd be pretty straight-forward to implement.

There's probably a `jq` command that would work in the meantime to get the latest backup for a schedule. Can look at it tmrw

**Comment by marpaia** [comment]
Yeah, `ark get backups -o json | jq -r ' .items | .[] | .metadata.name' | sort -r | head -1` will get you the latest synced backup it seems (if you only have one scheduled backup).

I agree that `--from-schedule` would be :100: though.

**Comment by skriss** [comment]
@marpaia just opened a PR to add this functionality - take a look if you get a chance.

**Comment by rosskukulinski** [comment]
@skriss a question regarding this issue and your PR #443:

* Do we select the most recent backup or only the most recent successful backup?  What if there are none [no backups and/or no successful]

And @marpaia:

* Do you think we need improve the CLI documentation to be more explicit that the `--from-backup` command is accepting a backup name and not a schedule name?

**Comment by skriss** [comment]
It's been awhile since I've touched that one, but looks like checking for existence/success needs to be added. The functionality will need to move behind the API as well.

**Comment by marpaia** [comment]
@rosskukulinski personally, I think the CLI UX is sufficient as long as the new `--from-schedule` option is documented similarly to how `--from-backup` option is documented now. I'll admit that it was at first surprising to me that I couldn't restore "the latest backup" but that's mostly because of my perceived utility of such a feature, not necessarily because of how it was documented.

**Comment by rosskukulinski** [comment]
Great! Thanks for the feedback @marpaia.

@skriss I put this in the v1.0.0 milestone and we can figure out when to slot this in amongst the other work we're planning.
