### ISSUE TITLE
Adjust AWS cluster tags when restoring volumes

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#451]
Resources for Kubernetes clusters running in AWS have AWS tags identifying the cluster to which they belong. Some clusters may run with an IAM policy that limits the control plane so it's only allowed to attach volumes tagged with the appropriate cluster name (such as kops).

When Ark creates a volume from a snapshot, it needs to adjust the new volume's tag for the cluster name to be the name of the target cluster.

I'm not yet sure the best way to represent the cluster name's tag value when doing a restore. AFAIK that value is not guaranteed to be available with `kubectl get`. We could potentially try to query the ec2 metadata for the node where the Ark pod is running, but that's not a great idea because it could (and probably should) be blocked. We could require the user set an environment variable on the Ark deployment/pod that contains the value. That might be our best option?

**Comment by skriss** [comment]
We could put it in the Ark config (could go within `.persistentVolumeProvider.config`) - although I know long-term we're trying to gut that

**Comment by ncdc** [comment]
Yeah, I don't want to touch `persistentVolumeProvider`.

I don't think it would make sense to put it in the to-be `VolumeTarget` since that's meant to deal with replication.

I think it needs to go on something specific to the `heptio-ark` namespace in the target cluster. Could be an annotation, label, env var on the Ark pod. Could be a ConfigMap or some other resource in the ns...

**Comment by mauilion** [comment]
+1 on the environment option. Until something like cluster-api or cloud-controller-manager provide this info consistently I think we'd have to ask.

**Comment by ncdc** [comment]
Agreed - I think an env var is an "easy win" for starters.

**Comment by ncdc** [comment]
I think this is the logic we want:

1. Ark admin sets `AWS_CLUSTER_NAME` environment variable in the Ark deployment (e.g. `ABC`)
1. When restoring, Ark's AWS `blockStore` code, in `CreateVolumeFromSnapshot`:
    1. Removes all `kubernetes.io/cluster/*` tags
    1. Sets `KubernetesCluster` tag to cluster name from env var (`ABC`) (this is the "legacy" tag name)
    1. Sets `kubernetes.io/cluster/ABC` tag to `owned`

**Comment by ncdc** [comment]
Closed by #801

**Comment by skriss** [comment]
@mqsoh do you have `AWS_CLUSTER_NAME` set in your deployment?

**Comment by mqsoh** [comment]
@skriss That was my issue. [I see it in the documentation now.](https://velero.io/docs/v1.1.0/aws-config/#setting-aws_cluster_name-optional) Thanks for your help!
