### ISSUE TITLE
Binary clients

### ISSUE THREAD

**Issue by stevesloka** [heptio/ark#46]
I'm a first timer playing around with ark. My k8s master is not publically available, I access it via a Bastion over an SSH tunnel so using the docker alias method didn't work since `https://kubernetes:9443` (which is the tunnel to my k8s api) isn't accessible via the container. 

I made a change to the build to allow my mac to get a binary client and everything works fine. 

Would you be open to generating clients? Or having the build make additional architectures? I'm happy to send a PR.

**Comment by ncdc** [comment]
@stevesloka yes, this is probably something we should do. We need to work on tooling and automation for multi-arch builds, creating GitHub releases, and populating the releases with a description/changelog and binaries. A PR would definitely be appreciated - could you describe what you're thinking about having it do? Thanks!

**Comment by stevesloka** [comment]
Hey @ncdc I just sent a PR to discuss around. It's what I used to get playing locally on my mac. Going to validate on my pi cluster as well (would make a good demo). 

What I did works, but I just killed the build time. =)

**Comment by ncdc** [comment]
Fixed by #148
