### ISSUE TITLE
`latest` image tag corresponds to most-recently built release, not highest semver release

### ISSUE THREAD

**Issue by skriss** [heptio/ark#461]
If we release a `v0.8.0`, it'll also be tagged with `latest`. If we subsequently release a `v0.7.2`, it will get the `latest` tag. This is not what we want. `latest` should always be the highest (according to semver) release tag.

**Comment by ncdc** [comment]
@asenchi I'm thinking we stop auto-tagging `latest` and instead make that a manual step (in a CI job). WDYT?

**Comment by ncdc** [comment]
Moving to p0 because we need to fix this before we can release the 0.9 alphas.

**Comment by asenchi** [comment]
@ncdc That would be fine, is the "latest" tag even useful in this case? Presumably we would want people to pin to a version regardless?

@zoidbergwill Also has a good point, that logic could live here: https://github.com/heptio/ark/blob/master/Makefile#L135-L143

CI itself doesn't actually do the tagging, it just runs `make all-containers all-push VERSION="\$GIT_BRANCH"`

Let me know if you want to stand up another job, I can help guide that effort.

**Comment by asenchi** [comment]
> CI itself doesn't actually do the tagging, it just runs make all-containers all-push VERSION="\$GIT_BRANCH"

Let me clarify, the CI setup doesn't contain the logic for tagging, that is done in the Makefile (and imo should remain there). If we need to run a separate command for "latest", then we can get CI setup to handle that, we could even make it a boolean build parameter that is passed to the Makefile.

**Comment by ncdc** [comment]
@asenchi we do want people to pin to a version, or if not a version, something like `stable` (which is effectively what `latest` means right now, assuming we solve this issue). Our example yaml files currently use `latest` because we haven't gotten our docs tooling to a point where each branch has its own specific version. The combination of our future `ark server install` command (if we do it) and the community Helm chart should help here as well.

**Comment by asenchi** [comment]
Cool, makes sense. Pretty straight-forward change. Give me the go-ahead and I can PR that today.

**Comment by ncdc** [comment]
> We could do something like check if version >= latest tag name from https://api.github.com/repos/heptio/ark/releases/latest ?

If we release 0.9.0 first, and then 0.8.3, what does GitHub show as "latest" from that URL?

**Comment by ncdc** [comment]
@asenchi how about we start with the boolean build parameter passed to the Makefile as a variable?

**Comment by asenchi** [comment]
Sounds good, I added a build parameter.

**Comment by rosskukulinski** [comment]
Is this now resolved @asenchi / @ncdc ?

**Comment by ncdc** [comment]
Yes, can close
