### ISSUE TITLE
Failed to provision volume: Authentication Error

### ISSUE THREAD

**Issue by smm190** [heptio/ark#462]
I posted about this in a different ticket yesterday,but it looks like the problem is recurring.  When trying to run the "examples/nginx-app/with-pv.yaml" example, I see this error in my Kubernetes UI:

`kubectl apply -f examples/nginx-app/with-pv.yaml`

Then I go to my Kubernetes UI and I see this event warning in the nginx-example namespace: 

> Failed to provision volume with StorageClass "default": azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/378079de-70e6-423f-bf1a-93947a02ee38/resourceGroups/metaverse-acs-k8s-qa/providers/Microsoft.Compute/disks/kubemasterqa-dynamic-pvc-1886e866-48b1-11e8-a222-000d3a600c04?api-version=2016-04-30-preview: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '401'. Response body: {"error":"invalid_client","error_description":"AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided.\r\nTrace ID: 3af8f34b-6468-43f8-ac29-b6b959f47900\r\nCorrelation ID: c016488b-41a5-48cf-abcc-0dd377b60e26\r\nTimestamp: 2018-04-25 17:50:09Z","error_codes":[70002,50012],"timestamp":"2018-04-25 17:50:09Z","trace_id":"3af8f34b-6468-43f8-ac29-b6b959f47900","correlation_id":"c016488b-41a5-48cf-abcc-0dd377b60e26"}

I have checked and double-checked the credentials to make sure they are correct.  I have even tried deleting the service principal and creating an entirely new one with new credentials and updating the cloud credentials secret.  

Is there something besides the secret credentials that could be causing this error?

I am running ark on a acs-engine kubernetes cluster in Azure.

**Comment by ncdc** [comment]
cc @paulbouwer

**Comment by skriss** [comment]
Is this in the same cluster as yesterday, where you got it working? Did anything change with your Ark installation between then and now?

**Comment by smm190** [comment]
@skriss Yes this is in the same cluster as yesterday.  I noticed that even though those authentication errors stopped showing up in the backup log that the persistent volume snapshots were not getting done in the backup still and therefore not showing up when I run a restore.  So I decided to try the with-pv example to double check that the PV backups work correctly, and that's when I noticed this error after  I apply the example to my cluster.  I don't believe the problem was ever actually fixed yesterday, the errors disappeared from the backup logs but the backup also didn't actually contain the persistent volume snapshots.

**Comment by skriss** [comment]
OK - so looking more closely at the error above - this doesn't look like an Ark error at all. It looks like the service principal being used for your ACS cluster can't provision a volume for the PVC defined in the `with-pv.yaml` example.

**Comment by smm190** [comment]
@skriss Any idea why that would be the case?

**Comment by skriss** [comment]
Unfortunately I don't have a lot of experience with acs-engine - you might be better served by taking this to https://github.com/Azure/acs-engine, although I can try to help.

Did you use the `acs-engine` CLI or the Azure Portal GUI for setup?

**Comment by smm190** [comment]
I used the acs-engine CLI.

**Comment by smm190** [comment]
How can I find the name of the service principal that was created?

**Comment by skriss** [comment]
I believe it'll contain the name of your cluster (DNS prefix) if you had acs-engine create it automatically.

**Comment by skriss** [comment]
@smm190 were you able to resolve this?

**Comment by smm190** [comment]
@skriss Yes I was.  I restarted all of my nodes and this was resolved.  Our service principal credentials had been updated and the nodes needed to be restarted to pickup on the changes. 

Thank you.

**Comment by skriss** [comment]
great! please reach out if you have any further issues with Ark.
