### ISSUE TITLE
some of the Azure setup instructions don't work on macOS bash

### ISSUE THREAD

**Issue by skriss** [heptio/ark#473]
As reported by a user, they work on linux but not OS X:

```
AZURE_STORAGE_ACCOUNT_ID="ark`cat /proc/sys/kernel/random/uuid | cut -d '-' -f5`"
```
and
```
--query [0].value
```

**Comment by vishnoisuresh** [comment]
Yea I am facing the same issue. What could be the replacement of the `--query [0].value`  on macOS?

**Comment by skriss** [comment]
@vishnoisuresh I think it may need to be `--query '[0].value` (regardless of OS) - can you try that?

**Comment by vishnoisuresh** [comment]
@skriss  Yea It worked. Thanks
