### ISSUE TITLE
backup all namespaces fails on origin 3.7

### ISSUE THREAD

**Issue by cameronbraid** [heptio/ark#475]
final log message in the backup logs is :

time="2018-05-05T09:15:39Z" level=info msg="Backup completed with errors: no Items field in &v1.Status{TypeMeta:v1.TypeMeta{Kind:\"Status\", APIVersion:\"v1\"}, ListMeta:v1.ListMeta{SelfLink:\"\", ResourceVersion:\"\", Continue:\"\"}, Status:\"Success\", Message:\"\", Reason:\"\", Details:(*v1.StatusDetails)(nil), Code:0}" backup=heptio-ark/all logSource="pkg/backup/backup.go:271"

#oc version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server ******************
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

#ark version
Version: v0.8.1
Git commit: v0.8.1
Git tree state: clean

backing up a single namespace worked just fine.

**Comment by ncdc** [comment]
@cameronbraid thanks for the report. This is likely a bug in OpenShift but we'll see if we can work around it. Stay tuned...

**Comment by ncdc** [comment]
Ok, this is `GET /apis/projectrequests.openshift.io/v1/projectrequests`

**Comment by ncdc** [comment]
We currently filter on resources that support `create` and `list`. Unrelated to this issue, we also sometimes call `get` so we should add that to the filter. And it's probably good to throw `delete` into the mix, as it's highly unlikely that a resource that doesn't support `create`, `list`, `get`, and `delete` is a real resource.
