### ISSUE TITLE
Backups that fail to upload to object storage are marked as 'Completed'

### ISSUE THREAD

**Issue by skriss** [heptio/ark#491]
A user reported that a backup had a phase of `Completed` but the target object storage bucket was empty. Upon investigation, Ark was getting access denied errors when connecting to the bucket, so it couldn't upload. We set the backup phase to `Completed` before uploading (see https://github.com/heptio/ark/blob/master/pkg/controller/backup_controller.go#L359). We should probably check for errors uploading, and change it to `Failed` if there are any. 

Note that the phase should be `Completed` before json-encoding it for upload, so that the JSON in object storage (if it uploads successfully) has the right phase.

**Comment by skriss** [comment]
@nrb this would be a good one to tackle if you have bandwidth! I can provide more context if needed.

**Comment by ncdc** [comment]
@nrb & I figured this out. It turns out that with Google's go API for cloud storage, writes are async, and the only correct way to check for a write failure is to call `Close()` on the `Writer` and check the error it returns. @nrb is working on a fix with updated unit tests.

**Comment by ncdc** [comment]
(We were deferring the `Close()` call and ignoring the error)
