### ISSUE TITLE
backupPVAction crashes if spec.volumeName is missing

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#519]
If a PVC doesn't have a `spec.volumeName`, the backupPVAction plugin returns `nil` for the `updatedItem`. The BackupItemAction plugin's gRPC server code for `Execute` takes that `nil` and then tries to make a call on it. This causes the plugin process to crash.

We should do one or both of the following:

1. Modify backupPVAction to return the unmodified PVC
1. Modify the gRPC server code to handle `nil` values and ignore them

**Comment by SleepyBrett** [comment]
Thanks for looking into this for me!
