### ISSUE TITLE
Broken docs link from main readme

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/ark#554]
Page: https://heptio.github.io/ark/v0.8.1/

Any docs links that are relative seem to 404:

![image](https://user-images.githubusercontent.com/2746479/41436157-cedd93ea-6fee-11e8-9d0c-2d095cf27ac1.png)

* https://heptio.github.io/docs/cloud-common.md
* https://heptio.github.io/docs/build-from-scratch.md
* https://heptio.github.io/docs/debugging-restores.md
* and more!

**Comment by skriss** [comment]
Fixed by #773
