### ISSUE TITLE
Add documentation describing which volume types are supported

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/ark#558]
Kubernetes has an [extensive list](https://kubernetes.io/docs/concepts/storage/volumes/#types-of-volumes) of volumes in-tree.  The Ark documentation should include a list/table showing which volume types are supported directly, via restic, via 3rd party plugins, etc.

This will help new users evaluate the options they have for their clusters.

**Comment by rosskukulinski** [comment]
@ncdc how does CSI / FlexVolume impact our support for the various volumes?

**Comment by ncdc** [comment]
@rosskukulinski it won't have any immediate impact, as Ark uses its own mechanisms for doing volume snapshots and restores. If the volume snapshotting work that's currently in kubernetes incubation ends up moving to kubernetes/kubernetes core, we'll need to consider if/how to integrate with that.

**Comment by skriss** [comment]
This was fixed by #723, closing
