### ISSUE TITLE
Setup ark using role on AWS

### ISSUE THREAD

**Issue by pmquang** [heptio/ark#562]
Hi,

Im setting up heptio ark on K8S using role on AWS. 

It's fine for ark deployment but minio: 

$ kubectl logs --tail 100 minio-setup-t25t2 -n heptio-ark

mc: <ERROR> Unable to initialize new config from the provided credentials. The request signature we calculated does not match the signature you provided. Check your key and signing method.

Anyone knows how to add support role for minio ? 

Regards

**Comment by ncdc** [comment]
Did you use our example yaml to deploy minio, or did you change anything?

**Comment by pmquang** [comment]
I used the example yaml and remove lines of AWS key to deploy minio: 

---
apiVersion: v1
kind: Secret
metadata:
  namespace: heptio-ark
  name: cloud-credentials
  labels:
    component: minio
stringData:
  cloud: |
    [default]
    aws_access_key_id = xxx
    aws_secret_access_key = xxx

These lines above were removed.

**Comment by ncdc** [comment]
It looks like the minio server only supports a single access key and secret (https://github.com/minio/minio/issues/5305).

**Comment by ncdc** [comment]
@pmquang did my answer make sense? Do you need any further assistance?

**Comment by pmquang** [comment]
Yes, thank you :)

**Comment by rosskukulinski** [comment]
Closing as question answered - please feel free to comment if you think I've been over zealous
