### ISSUE TITLE
GCE PV getting restored from snapshot but spec.gcePersistentDisk.pdName still has the original PD name

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#587]
Reported by a user:

In GKE cluster1, take a backup that includes a PV for a GCE persistent disk.

Keep cluster1 running with the PV bound and in use.

Meanwhile, in GKE cluster2, restore from backup. The restore logs say it created a new persistent disk from the snapshot, but the Kubernetes PersistentVolume still has `spec.gcePersistentDisk.pdName` pointing at the original PD that is attached to cluster1.

Ark v0.8.2

**Comment by nrb** [comment]
So far I haven't been able to reproduce this with the [gitlab-omnibus](https://gitlab.com/charts/gitlab-omnibus) chart. I tried a couple methods of backing it up from the original cluster. Note that `default` is the default namespace for gitlab from the chart.

`ark backup create gitlab --exclude-namespaces=heptio-ark,kube-public,kube-system,nginx-example`

and 

`ark create backup gitlab-ns-only --include-namespaces default`

**Comment by ncdc** [comment]
After further discussion, there were already PVs in the target cluster that had the same name as the PVs from the backup. Ark created new PDs from the snapshots, but wasn't able to create PVs in Kubernetes because of the conflicts. We don't have an explanation for why the PVs already existed, but if we get that information, we can reopen and continue investigating.

The investigation did result in #609, which we need to figure out.
