### ISSUE TITLE
Make sure we're backing up the "right" API versions to support upgrades

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#592]
For example, if Kubernetes `vX` has API group/versions `abc/v1alpha1`, `abc/v1beta1`, and `abc/v1`, and the next Kubernetes version `vY` drops `abc/v1alpha1`, we shouldn’t be backing up that version.

We currently use the `ServerPreferredResources` from discovery, which returns the version of each API group preferred by the server.

**Comment by nrb** [comment]
Would this be configurable? In a DR scenario within the same Kubernetes release, presumably the API versions should remain the same.

**Comment by ncdc** [comment]
It's more of a concern for a restore into a new cluster that's at Kubernetes version _n+1_ compared to a backup taken from Kubernetes version _n_

**Comment by nrb** [comment]
Right. What I'm saying is I don't want to see us break moving between 2 clusters at _n_.

**Comment by ncdc** [comment]
I don't see how we'd break if the Kubernetes version remains constant?

**Comment by ncdc** [comment]
Copying from Slack:

If we have 3 versions: `v1alpha1`, `v1beta1`, `v1`:

The “best” one to back up for compatibility when restoring into kube clusters that are possibly older than the cluster being backed up would be `v1alpha1`.

The “best” one to back up for forward compatibility when restoring into kube clusters that are possibly newer would be `v1`.

**Comment by skriss** [comment]
@ncdc I'm tempted to say that we should just document that we back up the server's preferred version, and that in order to restore resources, the API group/version that was backed up needs to exist in the target cluster, and let Kubernetes handle any conversions.

**Comment by ncdc** [comment]
Definitely an easy and good initial step. If the need arises, we could look into making different "conversion plugins" that pull in the conversion code from Kubernetes at various points in time (to avoid missing out on a dropped API version).
