### ISSUE TITLE
Restore storageclasses before persistentvolumes and persistentvolumeclaims

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#594]
This is necessary so the PVs and PVCs can be created correctly.

**Comment by shubheksha** [comment]
I'd like to pick this up! @ncdc, can I get some more info to get started on it?

**Comment by ncdc** [comment]
@shubheksha sure! We have default restore priorities here: https://github.com/heptio/ark/blob/d7dfffa37358584d66e2d433cd79c7b8f2f43f4e/pkg/cmd/server/server.go#L456-L475. Need to insert storageclasses in the right place and test it.
