### ISSUE TITLE
Consideration for refactoring restore command 

### ISSUE THREAD

**Issue by jrnt30** [heptio/ark#60]
When creating a restore, I find it a bit confusing that the `backup`'s name is in the form of an argument, as we aren't actually creating a `backup`, it is just a piece of a given restore.  

One option would be: 
- Have the backup be an explicitly named, required flag.  
- Optionally support an argument which would then be the restore's name itself, not that of the backup

Current: `ark restore create <backup name>`
Proposed: `ark restore create --backup <backup name>`

A broader question would be, has there been consideration to flipping the verb and resource to more closely match how Kubectl works?  `ark create restore ...`

**Comment by ncdc** [comment]
We are thinking we should change this to
```
ark restore create --from-backup <backup>
```

If the user wants to, they can specify a name for the restore (`ark restore create foo --from-backup bar`), or if they don't, we'll default it as we do now (`ark restore create --from-backup bar` would yield a restore named `bar-<timestamp>`).

In the future, we may have additional backup sources (e.g. `--from-file <local tarball>`).

WDYT @jrnt30 @skriss?

**Comment by jrnt30** [comment]
Sure, that makes a lot of sense.

**Comment by rdodev** [comment]
+1 to this. It's not entirely intuitive the restore name much match the target backup.
