### ISSUE TITLE
Decide if we want to have 1 plugin manager per scope (server, backup, restore) or 1 overall

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#601]
In #495 (not yet merged), each "scope" gets its own `plugin.Manager` - the Ark server, each backup, and each restore. This has a higher memory cost if/when we support simultaneous backups or restores (each backup/restore has to load a full set of plugins). Using a unique manager per scope, however, makes it easier to distinguish log messages - we can easily direct logs from an individual backup's set of plugins to the backup's log file.

An alternative would be to have a single set of plugins, and use a structured log field to "route" messages to the right log destination.

**Comment by skriss** [comment]
@ncdc would you consider this question closed by now?

**Comment by ncdc** [comment]
Yes, I think the way things are working now is good. Thanks for checking!
