### ISSUE TITLE
Restoring: better handling of snapshots/volumes if PV already exists

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#609]
If a PV already exists in the cluster, trying to create a volume from the snapshot will succeed, but we won't be able to create the PV. We need better handling of this situation.

**Comment by wwitzel3** [comment]
From a discussion, we talked about the following new behavior when a snapshot exists:
* Before `executePVAction` check if PV already exists before attempting restore. Error/log if it exists and continue.
* PVC won't be present in the pvsToProvision.

**Comment by skriss** [comment]
Closed by #1002, #1011
