### ISSUE TITLE
Make the restore label namespaced

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#614]
When restoring, Ark adds an `ark-restore` label to all resources, where the value is the name of the restore.

We should change the key from `ark-restore` to a namespaced one such as `ark.heptio.com/restore-name`. To preserve compatibility from now to 1.0, we can continue to set `ark-restore`, but we should switch to using only the namespaced key for 1.0.

We could/should also consider including the name of the backup as a label on all restored items: `ark.heptio.com/backup-name`.

**Comment by ncdc** [comment]
@skriss @rosskukulinski

**Comment by rosskukulinski** [comment]
I think this is a good idea, but curious on your take about this situation:

1. Take a backup of a namespace
2. Restore to a new namespace (so now ark.heptio.com/backup-name and ark.heptio.com/restore-name) are set
3. Take a backup of new namespace
4. restore somewhere else.

Does the history of backups & restores matter?  Or only the immediate parent?

**Comment by ncdc** [comment]
My quick take is just immediate parent.

**Comment by skriss** [comment]
Makes sense to me, and agree re: just most-recent restore.
