### ISSUE TITLE
Ark - Restic - Setup encryption key 

### ISSUE THREAD

**Issue by pmquang** [heptio/ark#617]
Hi, 

I see on this documentation : https://github.com/heptio/ark/blob/master/docs/restic.md 

I must setup encryption key : 

```
# provide the encryption key on the command line
ark restic init-repository --namespace YOUR_NAMESPACE --key-data YOUR_ENCRYPTION_KEY
```
```
# provide the encryption key via file
ark restic init-repository --namespace YOUR_NAMESPACE --key-file YOUR_ENCRYPTION_KEY_FILE
```
```
# have Ark generate a random encryption key
ark restic init-repository --namespace YOUR_NAMESPACE --key-size ENCRYPTION_KEY_SIZE
```

But I have no idea about this. Have someone can explain this more clearly ? 

Regards

**Comment by skriss** [comment]
Hi @pmquang, with the next pre-release version of 0.9.0 you won't have to set this up. We should have this out in the next day or two. 

In the interim, it would be easiest to just specify a key size. Eg 1024.

**Comment by pmquang** [comment]
hi @skriss ,

I met some errors: 

```
E0628 07:29:16.509348       1 reflector.go:205] github.com/heptio/ark/pkg/generated/informers/externalversions/factory.go:74: Failed to list *v1.PodVolumeBackup: the server could not find the requested resource (get podvolumebackups.ark.heptio.com)
E0628 07:29:16.976141       1 reflector.go:205] github.com/heptio/ark/pkg/generated/informers/externalversions/factory.go:74: Failed to list *v1.PodVolumeRestore: the server could not find the requested resource (get podvolumerestores.ark.heptio.com)
```

After I deployed ark with restic, I can not use ark logs command:

```
ark-crd 123491$ ark backup logs nginx-example-efs
An error occurred: timed out waiting for download URL
```

**Comment by skriss** [comment]
@pmquang have you gone through all the setup steps here https://github.com/heptio/ark/blob/master/docs/restic.md#setup? It looks like you haven't done step 2.

**Comment by pmquang** [comment]
hi @skriss ,

I already did it and redeployed daemonset restic but it did not work

**Comment by ncdc** [comment]
@pmquang we will be doing a new 0.9.x release soon where you don't have to go through the encryption key setup. It might be worth waiting until then, and retrying with the new version. Would that be ok?

**Comment by skriss** [comment]
Hi @pmquang, please take a look at https://github.com/heptio/ark/releases/tag/v0.9.0-alpha.3 and the updated instructions at https://github.com/heptio/ark/blob/master/docs/restic.md.

**Comment by skriss** [comment]
Closing this issue as we've releases v0.9.0-alpha.3 which no longer requires setting up encryption keys. @pmquang feel free to reach out again if you have further issues with the new alpha, thanks!
