### ISSUE TITLE
Disallow multiple clusters backing up into the same bucket (and prefix)

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#627]
We should forcibly not allow multiple clusters to back up into the same bucket. Once we have subdirectory/prefix support, multiple clusters can share the same bucket, but they can't share the same subdirectory.

We could use the `uid` of the `default` namespace in each cluster, as it's impossible to delete that namespace.

@heptio/product-team @heptio/bluesteelsquad

**Comment by ncdc** [comment]
@rosskukulinski if we only allow a single cluster to write to (bucket,prefix), it seems ok to share a bucket.

**Comment by rosskukulinski** [comment]
Closing this in favor of an epic #726
