### ISSUE TITLE
Consider tweaking restic metadata to allow better parent snapshot finding

### ISSUE THREAD

**Issue by skriss** [heptio/ark#635]
When taking a backup, restic first looks for a "parent" snapshot, i.e. **a previous snapshot from the same host of the same directory**, from which it can perform a differential backup.  This is key for making incremental backups efficient.

With Ark, the host name corresponds to the name of the daemonset pod from which the restic cmd is run. This means that if the pod is recreated, it will have a different name, and the next set of backups for pods on that node will be full rather than incremental.

Additionally, the path we're backing up includes a pod UID element. This means that if the workload's pod is recreated (i.e. after a backup and restore, or as part of a reschedule), the next backup will be full rather than incremental.

The hostname can be overriden as a flag when running `restic backup`. I think we may want to set this to a generic value, i.e. "ark", to prevent breaks in the incremental snapshot chain.

I think workload pod UIDs in the path are less of an issue (it doesn't seem unreasonable to take a new full backup after a restore), but we should think about this.

**Comment by nrb** [comment]
What kind of severity/priority would you give this? Sounds to m like it should be in v0.9.0 in order to make incremental backups work as expected.

**Comment by skriss** [comment]
If we agree that we should use a generic hostname, then yes I'll do it for 0.9.0.  I don't think the volume path thing is essential for 0.9.0, even if we decide we want to change something.

**Comment by nrb** [comment]
Does the current behavior break restores?

**Comment by skriss** [comment]
No - nothing's "broken" in the current state, it's just that we'll end up taking full rather than incremental backups in more situations than is strictly necessary, so some backups will be slower.

**Comment by ncdc** [comment]
We can close this?

**Comment by skriss** [comment]
Fixed with #636.
