### ISSUE TITLE
Use goreleaser

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#640]
- Use a dummy repo to validate the release process
- See how customizable go releaser's steps around building and pushing images are.
- Investigate automation around updating `Gopkg.toml` in ark-plugin-examples repo; is it even possible?

**Comment by ncdc** [comment]
@skriss ready to close this?

**Comment by metadave** [comment]
just curious if there was a decision to use a different tool?

**Comment by skriss** [comment]
Closed by #1000
