### ISSUE TITLE
Reorganize docs content

### ISSUE THREAD

**Issue by Bradamant3** [heptio/ark#648]
Here's a preliminary outline/proposal (started implementation with v0.9.0 -- see PR #639 ):

```
Install
Run
  - backups, with or without schedule
  - everything
      - specific objects/etc
  -  restore
     -  everything
     -  specific objects/etc -- can you restore only bits from an everything restore?
Customize
    - build from source
    - extend
Reference
Tutorials (based on solid use cases -- see issue #372 and linked PR #346 )
```

Not accounted for: restic integation. Two possible approaches:
- keep separate (what we have now, but separate how it works into separate topic/file)
- interleave with non-restic instructions (still want separate topic for how restic works)

**Comment by Bradamant3** [comment]
N.B. This is a proposal only. Please feel free to suggest changes, or submit docs PRs that reflect a different approach.

**Comment by ncdc** [comment]
> can you restore only bits from an everything restore?

Yes

**Comment by Bradamant3** [comment]
duplicate
