### ISSUE TITLE
Ark v0.9.0 not compatible with pre-1.8 clusters

### ISSUE THREAD

**Issue by skriss** [heptio/ark#660]
A user reported that Ark was crashing on a 1.7.x cluster.  It looks like the proximate cause for that is that the new backup item action that backs up cluster roles and role bindings related to a service account is using the `rbac.authorization.k8s.io/v1` API group/version, which doesn't exist pre-1.8 when RBAC went GA.

It's possible there are other issues too; we haven't tested with 1.7 clusters.

Need to decide what our level of support should be for older versions of Kube going forward, and decide if we want to try to fix this specific issue.

cc @heptio/bluesteelsquad @rosskukulinski

**Comment by timh** [comment]
How important is the use case of folks using Ark to upgrade from an older version of K8s to a more modern one? Might this (and its ilk) be a key enabler of that use case?

**Comment by ncdc** [comment]
@timh definitely a motivator.

@skriss anywhere we're invoking k8s APIs where there are multiple API versions, we could potentially use discovery and try all the versions we have in client-go, starting with the latest (e.g. v1) and falling back (v1beta1, v1alpha1).

**Comment by skriss** [comment]
In this particular case the user upgraded their cluster and all's good.

**Comment by nrb** [comment]
> How important is the use case of folks using Ark to upgrade from an older version of K8s to a more modern one?

It's a use case we've suggested. However, we haven't yet made a firm decision on what our support window is. We'll definitely need a solid story on our k8s version window for 1.0.

**Comment by skriss** [comment]
FYI we got a second user report of the same issue today.  I'm inclined to just address this one for now, release an 0.9.1, and kick the can down the road on defining our compatibility matrix, i.e. still plan to do it for 1.0.  Any objections?

**Comment by ncdc** [comment]
SGTM. Is your plan to try multiple api versions?

**Comment by metadave** [comment]
I had the [same issue](https://github.com/heptio/ark/issues/674) w/ a 1.7.2 cluster, and was able to use Ark 0.8.3 client/server to resolve.

**Comment by skriss** [comment]
Thanks @metadave for the info. We'll also be releasing v0.9.1 shortly, which will bring back 1.7.x compatibility.
