### ISSUE TITLE
restic-wait  restore data not found

### ISSUE THREAD

**Issue by geofflamrock** [heptio/ark#669]
Hi,

I've been trying to get restic backups and restores to minio working, and I think the backup is working ok.

When I attempt to restore the data, the restore says it completed, however the restic-wait container on the pods repeatedly says "Not found: /restores/data/.ark/a4323ca2-84cd-11e8-bcec-00155da8f01e"

Is there some way I can work out why this isn't working?

Thanks.

**Comment by ncdc** [comment]
Hi @geofflamrock, sorry you're having trouble. Could you please share the logs from the `restic-*` pod in the `heptio-ark` namespace?

**Comment by geofflamrock** [comment]
Hi @ncdc , thanks for getting back to me, attached is a zip file with the logs. 

I truncated them at the certain point as they were getting relatively large in size and they just had the same lines over and over again about "Pod is not running restic-wait init container, not enqueuing restores for pod" and "Restore is not new, not enqueuing". If you want the full logs please let me know.

Thanks.
[restic-logs.zip](https://github.com/heptio/ark/files/2186413/restic-logs.zip)

**Comment by skriss** [comment]
@geofflamrock could you also provide the output of `ark restore describe` and `ark restore logs` for your restore?

**Comment by geofflamrock** [comment]
@ncdc attached, thanks.
[restore-describe.txt](https://github.com/heptio/ark/files/2186555/restore-describe.txt)
[restore-logs.txt](https://github.com/heptio/ark/files/2186556/restore-logs.txt)

**Comment by skriss** [comment]
Hmm, it sure looks like 6 restic restores completed successfully.  Are the relevant pods still around (waiting for the init container to complete)? If so, could you provide the YAML for all of them?

**Comment by geofflamrock** [comment]
Hi @ncdc, attached are the restic logs, restore logs and describe and the restored yaml.

The resources I'm specifically trying to backup and restore are kafka and zookeeper stateful sets with persistent volume claims, and I do wonder whether this is part of the problem, as I'm not sure I'm configuring the backup correctly. 

When the restore happens, the stateful set doesn't come back, just the pods. Also, I tried removing the restored pods, which leaves the pvc based volume behind and then re-deploy the stateful set, it picks up the correct volumes but there isn't anything in the data itself, like it never actually got backed up. 

All of this makes me think that my original backup is bad, but everything I could find in it said it completed successfully.

In addition to this, I am now getting an error "pod volume backup failed: error running restic backup, stderr=Fatal: unable to save snapshot: snapshot is empty" when I try to take a new backup, so I think something is screwy in the back up side, and it is probably user error is my guess.
[gl-1-20180712134553-describe.txt](https://github.com/heptio/ark/files/2187004/gl-1-20180712134553-describe.txt)
[gl-1-20180712134553-logs.txt](https://github.com/heptio/ark/files/2187005/gl-1-20180712134553-logs.txt)
[restic-logs.zip](https://github.com/heptio/ark/files/2187006/restic-logs.zip)
[blueshift-one-backup-test.yaml.txt](https://github.com/heptio/ark/files/2187007/blueshift-one-backup-test.yaml.txt)






Thanks for your help in getting this to work, I appreciate it.

**Comment by ncdc** [comment]
@geofflamrock were you able to get your backups and restores working?

**Comment by geofflamrock** [comment]
@ncdc unfortunately I haven't had the opportunity to get back to this yet due to other things I've been working on, I will try and get back to it in the next few days and see.

**Comment by mitchhh22** [comment]
I'm having a similar issue with restore/backup:
- The first backup create using restic works fine (Completed)
- Any subsequent attempt to create another backup that uses restic fails:
**restic pod log**:
```
time="2018-08-08T19:37:03Z" level=info msg="Backup starting" backup=heptio-ark/mitch-test-test controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:167" name=mitch-test-test-r62bw namespace=heptio-ark
time="2018-08-08T19:37:05Z" level=info msg="Backup completed" backup=heptio-ark/mitch-test-test controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:241" name=mitch-test-test-r62bw namespace=heptio-ark
time="2018-08-08T19:48:13Z" level=info msg="Backup starting" backup=heptio-ark/mitch-test-test2 controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:167" name=mitch-test-test2-2x9bk namespace=heptio-ark
time="2018-08-08T19:48:14Z" level=error msg="Error running command=restic backup --repo=s3:http://minio.heptio-ark.svc:9000/pv-bucket/default --password-file=/tmp/ark-restic-credentials-default677627494 --cache-dir=/scratch/.cache/restic . --tag=volume=storage-volume-new --tag=backup=mitch-test-test2 --tag=backup-uid=fc684877-9b43-11e8-94d4-0cc47ac91aec --tag=ns=default --tag=pod=mitch-test-df7c8d889-sq9k8 --tag=pod-uid=cb2ca1c3-9b43-11e8-94d4-0cc47ac91aec --hostname=ark, stdout=, stderr=Fatal: unable to save snapshot: snapshot is empty\n" backup=heptio-ark/mitch-test-test2 controller=pod-volume-backup error="exit status 1" error.file="pod_volume_backup_controller.go:219" error.function="(*podVolumeBackupController).processBackup" logSource="pkg/controller/pod_volume_backup_controller.go:219" name=mitch-test-test2-2x9bk namespace=heptio-ark
```
- Trying to restore from the successful backup restores resources but the persistentVolume is not populated with data:
**ark restore logs mitch-test-restore3**
```
An error occurred: Get http://minio.heptio-ark.svc:9000/ark/mitch-test-test/restore-mitch-test-restore3-logs.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=minio%!F(MISSING)20180808%!F(MISSING)minio%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20180808T195055Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=ccae965d2a699c11f9f98fb71051587d45144d2b8d30d75fd3f42d682cf14ead: dial tcp: lookup minio.heptio-ark.svc on 10.50.4.2:53: no such host 
```


note: the PVC/PV I'm trying to backup is an external nfs mount.

**Comment by ncdc** [comment]
@mitchhh22 re the error you get from `ark restore logs`, please see #387 for suggestions on how to view logs with Minio.

Can you ssh to the node that's running the pod `mitch-test-df7c8d889-sq9k8` and look in `/var/lib/kubelet/...` and see if you can find the directory that represents the `storage-volume-new` volume for that pod (uid=`fc684877-9b43-11e8-94d4-0cc47ac91aec`) - is there anything in there?

**Comment by kmova** [comment]
@ncdc, I have hit a similar issue when using an iSCSI PV. 

During the restore process:
- The restore says completed successfully, but the application remains in init-container waiting state for the `.ark..` folder to be available. 
- I did exec into the restic-pod on the node and I saw that data is present in the restored volume directory along with the .ark folder. 
- I sshed into the node, the data that was visible from pod exec -- but same data is not visible under required pod mount directory under: /var/lib/kubelet/restore-pod-id/../mount.

I am running with GKE - K8s version 1.9.7 and ARK version v.0.9.5. Could there be an issue with mount propagation/shared mounts between application pod and restic-ds-pod? 

I used the following work around during restore: 
- pod exec - copy : data from restic pod datadir to scratch (temporary folder)
- node ssh - copy from /var/lib/kubelet/restic-pod/..scratch-dir to /var/lib/kubelet/application../pv-mount
Application was restored with the data. 

I have observed a similar issue during backup as well with iSCSI PV. 
- The backup works if application pod contains the data and then restic-pod is launched
- The backup doesn't work when restic-pod is already running and application pod is launched. The new mounts under the /var/lib/kubelet.. are not visible inside the pod-exec restic-pod.

**Comment by ncdc** [comment]
@kmova thanks for the additional info. This does sound like a mount propagation issue. Do you know what Docker version GKE is using offhand?

**Comment by kmova** [comment]
Here it is @ncdc 
```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.6.2
 Git commit:   f5ec1e2
 Built:        Tue Nov 21 16:41:54 2017
 OS/Arch:      linux/amd64
Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   f5ec1e2
 Built:        Tue Nov 21 16:41:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by skriss** [comment]
@kmova @ncdc I believe Kubernetes support for mount propagation only moved to beta a/o v1.10, so possible it's disabled on your 1.9.x GKE cluster which would be causing this to fail.

**Comment by ncdc** [comment]
I have seen mount propagation issues related to host bind mounts with pure Docker 17.03.02 that aren't in 18.06. @skriss this issue probably deserves more research.

**Comment by kmova** [comment]
@ncdc @skriss 

The backup/restore is working after upgrading to GKE version `v1.10.7-gke.2`
Same docker version as above : `17.03.2-ce`

Would you like me to send a PR to update the Restic - Prerequisites docs?

**Comment by nrb** [comment]
@kmova That would be great!

**Comment by skriss** [comment]
Closing as inactive.
