### ISSUE TITLE
Testing on Azure - attempting to follow Lachlan Evenson demo on Azure, fail with location error

### ISSUE THREAD

**Issue by segeva** [heptio/ark#67]
The ark pod fails as follows:

I0906 07:36:32.999205       1 server.go:244] Configuring cloud provider for backup service
An error occurred: missing location in azure configuration in config file

The azure config (examples\azure\10-ark-config.yaml) was modified as follows:
  azure:
    location: australiaeast
    apiTimeout: 20s

**Comment by ncdc** [comment]
@segeva can you post your entire config yaml?

**Comment by segeva** [comment]
azure folder with the modified 10-ark-config.yaml
[azure.zip](https://github.com/heptio/ark/files/1283019/azure.zip)

**Comment by ncdc** [comment]
@segeva ok I think I see what's happened. You're running our image tagged "latest", which corresponds to v0.3.3. You will need to follow the documentation for that version, as the documentation for the master branch applies only to that branch, and things have changed between v0.3.3 and master. In v0.3.3, you need to make sure your config looks like this: https://github.com/heptio/ark/blob/v0.3.3/examples/azure/10-ark-config.yaml.

We are working on making it easier to find documentation for the latest tagged release, previous releases, and the current bleeding-edge master, but we don't have that in place yet.

Please follow the v0.3.3 docs and let us know if that fixes things for you. Thanks!

**Comment by segeva** [comment]
Great, this worked.
I noticed that the tagged versions 'deployments' are still pointing to latest images, possibly common helm chart with specific images versions in the ‘values’ file can help …
