### ISSUE TITLE
Ark over openstack/barematal K8 deployment

### ISSUE THREAD

**Issue by VC16dec** [heptio/ark#671]
**What steps did you take and what happened:**
Deployed Ark over baremetal K8 setup and successfully able to do the restore and backup for basic nginx example shown in documentation
but when I used for my application, configmaps are not restored over same and hence application container did not came up, rest service,jobs are successfully restored.

Have checked in backup tar ball too, configmap was not there.

**What did you expect to happen:**
Ideally it should restore every objects, Does it depend upon the baremetal/openstack as well?
Or 
do I need to add something in the config
10-ark-config.yaml
apiVersion: ark.heptio.com/v1
kind: Config
metadata:
  namespace: heptio-ark
  name: default
backupStorageProvider:
  name: aws
  bucket: ark
   config:
    region: minio
    s3ForcePathStyle: "true"
    s3Url: http://minio.heptio-ark.svc:9000
backupSyncPeriod: 1m
gcSyncPeriod: 1m
scheduleSyncPeriod: 1m
restoreOnlyMode: false

**Anything else you would like to add:**

**Environment:**

- Ark version (use `ark version`): v0.9.0
- Kubernetes version (use `kubectl version`): v1.8.10
- Kubernetes installer & version: Rancher 1.6.14
- Cloud provider or hardware configuration: 64GB RAM, Ubuntu 16.0.4 and Openstack Pike
- OS (e.g. from `/etc/os-release`):"Ubuntu 16.04.3 LTS

**Comment by ncdc** [comment]
@VC16dec could you please list the exact command you ran to create the backup, or paste a copy of it in yaml format here (`ark backup get <name> -o yaml`)? And then the same thing for the configmap, and the ark restore? Thanks!

**Comment by VC16dec** [comment]
H

**Comment by VC16dec** [comment]
Can anyone look over this or have faced same?

**Comment by ncdc** [comment]
@VC16dec I'm guessing your configmaps are not labeled `app=consul`. Could you please check their labels and report back?

**Comment by VC16dec** [comment]
yes, thanks, They were not mapped correctly, So as a solution, I created a label to define release name in all entities and then it worked fine.
