### ISSUE TITLE
Ark making a lot of delete backup requests

### ISSUE THREAD

**Issue by DP19** [heptio/ark#685]
We're seeing an issue where a snapshot may be deleted by hand or by ark itself and the backup just stays in the deleting status. This causes ark to make a delete backup request then fail to remove it because the corresponding snapshot doesn't exist anymore. This continues to happen until there are thousands of deletebackuprequests. Is there a way to force delete backups? Or a code change to continue deleting the backup even if the snapshot doesn't exist?

`Deletion Attempts (50 failed):
  2018-07-18 14:28:24 -0400 EDT: Processed
  Errors:
    error deleting snapshot snap-088dc54a0627c1c41: rpc error: code = Unknown desc = InvalidSnapshot.NotFound: The snapshot 'snap-088dc54a0627c1c41' does not exist.
  status code: 400, request id: e2328806-9d25-494d-b043-9b57b91921e5
    error deleting snapshot snap-0bbb439b4aeb62e3f: rpc error: code = Unknown desc = InvalidSnapshot.NotFound: The snapshot 'snap-0bbb439b4aeb62e3f' does not exist.
  status code: 400, request id: cd4b57d5-8a79-461c-a502-79bcc3423705`

**Comment by skriss** [comment]
Thanks for reporting this @DP19.  This is an issue we're aware of and looking at solutions for (see #308, #423 for some related issues).  In the short-term, one option is to manually edit the relevant Backup's YAML and remove the snapshot info from `.status.volumeBackups`.

**Comment by ncdc** [comment]
@skriss @rosskukulinski I think we should consider modifying the object and block store plugins to return no error if we couldn't find the thing we're trying to delete (volume snapshot or object store item). That wouldn't require a change to the protobuf and hopefully could be implemented fairly quickly. WDYT?

**Comment by skriss** [comment]
Sounds like a good idea

**Comment by ncdc** [comment]
@rosskukulinski right, I'm thinking specifically about a 404

**Comment by rosskukulinski** [comment]
FYI @DP19 - we're prioritizing fixing this bug and discussing this issue in the [#ark-dr channel on Kubernetes slack](https://kubernetes.slack.com/archives/C6VCGP4MT/p1532028873000334)

**Comment by DP19** [comment]
Thanks for looking into this, we've actually had this issue for a while and have been completely re-installing ark to fix it. At one point we had over 250,000+ DBR's and it brought down our cluster, overloading the api server

**Comment by nrb** [comment]
@DP19 Are you able to capture one of the `DeleteBackupRequests` that get stuck? I'm curious to see what the `Phase` field is.

**Comment by DP19** [comment]
@nrb The phase field is processed, i had cleaned up the DBR's using @skriss suggestion but the ark archive in s3 still had them

`{"apiVersion":"ark.heptio.com/v1","kind":"DeleteBackupRequest","metadata":{"clusterName":"","creationTimestamp":"2018-07-18T11:58:24Z","deletionGracePeriodSeconds":null,"deletionTimestamp":null,"generateName":"ppek8s-hourly-20180716220729-","generation":0,"labels":{"ark.heptio.com/backup-name":"ppek8s-hourly-20180716220729","ark.heptio.com/backup-uid":"c670cf6e-8a10-11e8-8d0b-02c4169ff6ba"},"name":"ppek8s-hourly-20180716220729-drqtf","namespace":"heptio-ark","resourceVersion":"62028182","selfLink":"/apis/ark.heptio.com/v1/namespaces/heptio-ark/deletebackuprequests/ppek8s-hourly-20180716220729-drqtf","uid":"dfaa8239-8a81-11e8-8d0b-02c4169ff6ba"},"spec":{"backupName":"ppek8s-hourly-20180716220729"},"status":{"errors":["error deleting snapshot snap-0095b4bcbe1a0a822: rpc error: code = Unknown desc = InvalidSnapshot.NotFound: The snapshot 'snap-0095b4bcbe1a0a822' does not exist.\n\tstatus code: 400, request id: 29d56508-37a3-44d6-be5d-9ac4b6a2f7d8","error deleting snapshot snap-0470b86281c86a8b2: rpc error: code = Unknown desc = InvalidSnapshot.NotFound: The snapshot 'snap-0470b86281c86a8b2' does not exist.\n\tstatus code: 400, request id: b3eceed0-433e-4a59-bd3a-0c43ebac5f40"],"phase":"Processed"}}`

**Comment by DP19** [comment]
@nrb I can check tomorrow and see if this happens again and get you that as well.

**Comment by DP19** [comment]
Just a quick search and here's the log where it originally deleted the backup

`time="2018-07-17T21:28:24Z" level=info msg="Removing snapshot associated with backup" backup=ppek8s-hourly-20180716210729 controller=backup-deletion logSource="pkg/controller/backup_deletion_controller.go:237" name=ppek8s-hourly-20180716210729-5rn7l namespace=heptio-ark snapshotID=snap-088dc54a0627c1c41
time="2018-07-17T21:28:24Z" level=info msg="Removing restic snapshots" backup=ppek8s-hourly-20180716210729 controller=backup-deletion logSource="pkg/controller/backup_deletion_controller.go:244" name=ppek8s-hourly-20180716210729-5rn7l namespace=heptio-ark
time="2018-07-17T21:28:24Z" level=info msg="Removing backup from object storage" backup=ppek8s-hourly-20180716210729 controller=backup-deletion logSource="pkg/controller/backup_deletion_controller.go:252" name=ppek8s-hourly-20180716210729-5rn7l namespace=heptio-ark
time="2018-07-17T21:28:24Z" level=info msg="Removing restores" backup=ppek8s-hourly-20180716210729 controller=backup-deletion logSource="pkg/controller/backup_deletion_controller.go:258" name=ppek8s-hourly-20180716210729-5rn7l namespace=heptio-ark
time="2018-07-17T21:28:24Z" level=error msg="Error in syncHandler, re-adding item to queue" controller=backup-deletion error="error patching DeleteBackupRequest: deletebackuprequests.ark.heptio.com \"ppek8s-hourly-20180716210729-xv6zn\" not found" error.file="backup_deletion_controller.go:385" error.function="(*backupDeletionController).patchDeleteBackupRequest" key=heptio-ark/ppek8s-hourly-20180716210729-xv6zn logSource="pkg/controller/generic_controller.go:136"`

**Comment by nrb** [comment]
Thanks for this information!
