### ISSUE TITLE
S3 upload issue

### ISSUE THREAD

**Issue by thspinto** [heptio/ark#686]
**What steps did you take and what happened:**
I'm trying to do a backup but I get "SignatureDoesNotMatch" from AWS.  

The credentials are provided using kube2iam and the AWS policy allows any s3 action on the backup bucket. 

Am I missing something?

**Issue Log**

> logSource="pkg/controller/backup_controller.go:401"
time="2018-07-19T22:33:52Z" level=error msg="backup failed" error="rpc error: code = Unknown desc = error putting object default-bkp7/ark-backup.json: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, key=heptio-ark/default-bkp7 logSource="pkg/controller/backup_controller.go:280"

**Environment:**

- Ark version: v0.9.0
- Kubernetes version: v1.9.6
- Kubernetes installer & version: kops1.9.1 
- Cloud provider or hardware configuration: AWS

**Comment by nrb** [comment]
Hi @thspinto, thanks for providing the error message and environment details.

Are you able to upload to the same bucket, using the same credentials with `aws s3 cp`?

Also, is the time of `22:33:52` UTC correct for the time you tried to create a backup? The S3 code relies on synced clocks to generate upload signatures, and clock skew can affect the signatures.

**Comment by thspinto** [comment]
Thanks for the reply @nrb.

The clock is correctly synced and the credentials work fine with `aws s3 cp` from my machine.

**Comment by thspinto** [comment]
The issue was in my bucket configuration.

I used
```
backupStorageProvider:
  name: aws
  bucket: my-bucket/some-prefix
``` 
The backup worked when I removed the `/some-prefix`.

[Here](https://github.com/aws/aws-sdk-go/issues/1583) they say the object prefix should be in the key filed. Is the a way to configure that in ark?

**Comment by nrb** [comment]
Currently Ark cannot back up under a prefix, but we're planning to support that with v0.10.0.

**Comment by ncdc** [comment]
We're tracking prefix support in #167.

**Comment by thspinto** [comment]
Thanks for the help =).
