### ISSUE TITLE
[Epic] Finer-grained control of backup locations

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/ark#721]
**User Stories**
As a cluster administrator, I would like more fine-grained controls where backups are stored and where I can restore from
 - Backups & Restic Snapshots share bucket (#576)
 - Support sub-directory of object storage buckets (#167)
 - As a cluster administrator, I need to be able to provide different IAM credentials for different storage targets (buckets & snapshots) [Not currently in-scope or defined]

As a cluster administrator managing a Kubernetes cluster with multiple persistent volume types (e.g. EBS & Rook), I would like to be able to be backup/restore different types of PVs.

As a cluster administrator managing multiple Kubernetes clusters, I would like to multiple backup targets (e.g. one per cluster) to be co-located in the same storage bucket.

**Comment by skriss** [comment]
Epic is complete, closing.
