### ISSUE TITLE
Trademark conflict with Arq Backup

### ISSUE THREAD

**Issue by arqbackup** [heptio/ark#722]
Hi folks,

We've been shipping a popular online backup product for the past 9 years that has the same name, spelled with a Q instead of a K.
https://www.arqbackup.com
We have a registered trademark with the USPTO for Arq for "software for digital and electronic data and file backup and recovery". The serial number for the registered trademark is 87072023. 
I'm sure many of your users have heard of it.
Please start discussion for a new name and set a timeline to change it. Thank you!

**Comment by ncdc** [comment]
@arqbackup thank you for reaching out. We will discuss this and get back to you ASAP.

**Comment by J-Ha** [comment]
How About
"Bark"
Backup - Ark

**Comment by ae-v** [comment]
barque / bark / barc is a nautical term, too.
https://en.wikipedia.org/wiki/Barque

**Comment by ncdc** [comment]
We are resolving this matter directly with @arqbackup; therefore, I am closing this issue.
