### ISSUE TITLE
Helm chart for latest version over openstack (Local Storage)

### ISSUE THREAD

**Issue by VC16dec** [heptio/ark#728]
Hi All,

Is there a HELM Chart available with Latest ARK version and restic integration..
Moreover We want to use local storage/Baremetal or something related to openstack only. 
Is that supported, Minio need to be integrated with available helm chart?

What about secrets, anyone already did that using helm?

**Environment:**

- Ark version (use `ark version`):0.9.2
- Kubernetes version (use `kubectl version`):1.9.2
- Kubernetes installer & version:Rancher v1.6.14
- Cloud provider or hardware configuration:Openstack/Baremetal Ubuntu
- OS (e.g. from `/etc/os-release`):Ubuntu 16.0.4

**Comment by nrb** [comment]
Hi @VC16dec,

There's a community-maintained helm chart at https://github.com/helm/charts/tree/master/stable/ark. It looks like it's v0.9.0, which has restic integration. v0.9.2 is the latest release.

As far as OpenStack volume/block storage, I'm not aware of any plugins currently available. If OpenStack Swift has an S3-compatible object storage API that could be used for the backup objects.

I'm not sure about your question regarding secrets - could you provide more detail?

**Comment by VC16dec** [comment]
Hi,

Thanks
Yes, I want helm chart with local storage (may be minio) to test the functionality and then I can integrate it with openstack too. I will research on plugins.

Regarding secret creation, My query was related to helm chart only:-

"Secret for cloud provider credentials
Ark server needs an IAM service account in order to run, if you don't have it you must create it. Please follow the official documentation: https://heptio.github.io/ark/v0.9.0/cloud-common

Don't forget the step to create the secret

kubectl create secret generic cloud-credentials --namespace <ARK_NAMESPACE> --from-file cloud=credentials-ark"

That for Local Storage, I dont need this In that case, I need to change the same in Helm chart, If anyone already done that I can take help.

**Comment by ncdc** [comment]
Closing due to age.

@VC16dec if you still have questions, please send a message to our [mailing list](http://j.hept.io/ark-list), or reach out on [Slack](https://kubernetes.slack.com/messages/ark-dr).
