### ISSUE TITLE
Improve handling of preexisting resources during restore

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#74]
When restoring, if the resource already exists, we record that as a warning and move on. I can think of a few things we could do:

1. Upon seeing a preexisting resource, get it, diff against the backed up copy, and be silent if they're identical
1. If they're different
    1. Log a warning
    1. Overwrite

We could provide options in restore.spec for how to handle this.

Are there other options we could pursue?

cc @skriss @jbeda 
xref #23

**Comment by jrnt30** [comment]
Is there a straightforward way of doing that equality comparison that excludes some of the information we know will be different, such as the CreationTimestamp, etc. in the Client-Go api? 

Additionally, this comparison would be done after any Ark specific translations (such as namespace mappings) occurred, correct?

**Comment by ncdc** [comment]
I'm not aware of anything straightforward. I think we'll have to clear things like ResourceVersion and CreationTimestamp before doing the comparison.

Yes, this would be after Ark behaviors.

**Comment by robbyt** [comment]
It would be nice if we could restore objects to an alternative namespace, or otherwise change the restored object (rename it?) so it can coexist with the existing duplicate object.

restore -> diff -> replace existing object or rename restored object?
                    |-> if same? be silent

**Comment by ncdc** [comment]
@robbyt we do support restoring to alternative namespaces - that's `ark restore create --my-backup --namespace-mappings original:alternative`.

I'm not sure it'd be too easy to generally support renaming objects, unless you had some suggestions for how to control it? We are trying to figure out #192, which is somewhat related, albeit a very specific use case.

**Comment by ncdc** [comment]
@nrb did the work to omit recording "already exists" warnings (#405). The serviceaccounts imagePullSecrets issue is still open and being worked separately (#130). We don't have any examples of other actions to take when encountering a preexisting resource in the destination cluster.

I'm going to close this as implemented (other than #130, as previously mentioned).

@robbyt if you're still interested in being able to rename objects when restoring, please open a new issue and we can discuss it there. Thanks!
