### ISSUE TITLE
Create a BackupStorageLocation from the existing Config CRD at server startup

### ISSUE THREAD

**Issue by skriss** [heptio/ark#747]

**Comment by skriss** [comment]
This is to make migration from pre-v0.10 versions easy.

**Comment by carlisia** [comment]
I think we'll better serve ark's users by explicitly moving them on to the new concept of BSL and also remove the possibility of using a CRD for configuration sooner rather than later.

**Comment by ncdc** [comment]
I think it will be easier to fully delete the `Config`. If we do go this route, we should start socializing the change now - Twitter, Google Group, Slack, etc.

**Comment by rosskukulinski** [comment]
At this point in the project lifecycle, I'm on-board withfully deleting `Config` for 0.10 and forcing users to upgrade.

That said, we should plan to have solid docs on _how_ to upgrade 0.9.x to 0.10.0 and test them thoroughly.

**Comment by nrb** [comment]
I'm for deleting the `Config` CRD earlier so long as we have documentation and clear errors when they're found.

**Comment by skriss** [comment]
We decided not to do this and to require users to add their locations a/o v0.10.
