### ISSUE TITLE
Add bulk deletion support to ark restore delete

### ISSUE THREAD

**Issue by carlisia** [heptio/ark#749]
Modify ark restore to bulk delete restores, so that a user could do bulk deletes using `--all` or  `-l / --selector`. This would be in line with `kubectl`.

Examples:
* delete restores named "restore-1" and "restore-2"
`ark restore delete restore-1 restore-2`

* delete all restores with label foo: bar
`ark restore delete --selector foo=bar`
 
* delete all restores
`ark restore delete --all`

This is related to this issue: https://github.com/heptio/ark/issues/295

**Comment by ncdc** [comment]
Need to resolve 
https://github.com/heptio/ark/issues/748#issuecomment-411474132

**Comment by carlisia** [comment]
Edited the description, please check!

**Comment by shubheksha** [comment]
I'd like to take a stab at this!

**Comment by rosskukulinski** [comment]
@carlisia To clarify: is `-l` an alias for `--all` or `--selector`?

Kubectl behavior uses `-l` an alias for `--selector` and I think we should match that.

`  -l, --selector='': Selector (label query) to filter on, not including
uninitialized ones.`

**Comment by rosskukulinski** [comment]
Hi @shubheksha!  Thanks for volunteering to tackle this and #748.  You'll find that they're both likely similar to https://github.com/heptio/ark/pull/745.

Please read over https://github.com/heptio/ark/blob/master/CONTRIBUTING.md and you're welcome to join us in the [#ark-dr channel](https://kubernetes.slack.com/messages/ark-dr) on the Kubernetes slack server.

**Comment by ncdc** [comment]
@rosskukulinski `-l` is short for `--selector`. I'll adjust the description.
