### ISSUE TITLE
Enable pre/post-volume snapshot hooks for executing workload-specific actions

### ISSUE THREAD

**Issue by skriss** [heptio/ark#75]
Some workloads (e.g. databases) may require pre- and/or post-volume snapshot actions to be taken (e.g. flushing caches, fsfreeze) to ensure that the snapshot/backup taken is valid. We should create user-pluggable hooks to allow this kind of workload-specific logic to be executed during backups & restores.

**Comment by ncdc** [comment]
I think if you need to do something like fsync before taking a snapshot, you need to have the hook at the deployment/pod/container-ish level, not the PV. Maybe consider making the hooks more generic (not just applicable to volumes) and we can discuss the granularity + how to configure?

**Comment by rosskukulinski** [comment]
@ncdc some initial thoughts on real-world workloads and how they should be backed up https://docs.google.com/document/d/18_E18Zo1Ud1ShVTnFbkd69gjZoYNNfMGE-VI9yBZmS0

**Comment by ncdc** [comment]
PR for this: #112
