### ISSUE TITLE
[Design Question] Restructure of command hierarchy

### ISSUE THREAD

**Issue by jrnt30** [heptio/ark#76]
Closely related to #60, I was curious what peoples thoughts were to changing the order in which the CLI nests actions vs. resources.  Particularly, would people be open to looking at the UX of a closer parallel to kubectl itself? 

Ex. 
`ark backup create`
`ark create backup` 

As we continue to build more things "off of" the existing resources, such as the downloading of backup logs/data, it occurs to me that there is a strong correlation with the regular CRUD operations that exist for other resources in the ecosystem. 

If people are interested, I could take a stab at reworking the hierarchy of the CLI.

**Comment by ncdc** [comment]
We spent a decent amount of time discussing this previously. I definitely think it's worth another round of discussions. @jbeda @skriss fyi

**Comment by ncdc** [comment]
Before doing any coding, let's agree on the UX

**Comment by ncdc** [comment]
How does this sound:

We'll add verb-noun "aliases" for things like get and create (i.e. you could do `ark get backup` or `ark backup get` and both will do the same thing) so it will "just work". We'll probably either want to group these aliases separately in the `--help` output, or maybe even hide them. This will allow people who are used to `kubectl get` to apply that pattern to ark without getting tripped up (is it noun-verb or verb-noun?).

Over time, we will probably add more verbs (things like `ark backup cancel`, `ark backup status`, etc) so keeping them grouped as noun-verb is still nice, but where needed, we'll add the helper aliases.

**Comment by jrnt30** [comment]
We could certainly go that route and makes some sense, however your point about extensibility of the `verbs` is well received.  

The thing that tripped me up initially wouldn't really be solved by my suggestion either (ark restore create <backupname>` seemed odd), I'll close this for now and we can always re-evaluate if there are strong opinions.
