### ISSUE TITLE
Documentation on how to run ark without the cloud

### ISSUE THREAD

**Issue by mjschmidt** [heptio/ark#761]
I want to run heptio ark on premise. What steps do I need to take to make this happen?

**Comment by jenciso** [comment]
Hi @mjschmidt.

Do you want to know the step by step for running ark on premise?
Recently, I has been installing the ark using a minio server as storage and it's outside of my kubernetes cluster. The minio running on a VM. 

I created a role named `kube-backup`into my kubernetes-cluster playbook (it does provision a k8s cluster) named `. I only modify some yaml files for this purpose. you can check out here:

https://github.com/jenciso/kubernetes-cluster/tree/master/roles/kube-backup

If you need help to understand this role, please give me to know.

**Comment by ncdc** [comment]
@mjschmidt thanks for your question. We are planning to update our documentation this week to make it clearer what is needed for running on-prem. Please follow #332 for progress updates. Thanks!
