### ISSUE TITLE
ExternalName service restores log errors saying "key ports not found"

### ISSUE THREAD

**Issue by skriss** [heptio/ark#786]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

Backup and restore an ExternalName service (https://kubernetes.io/docs/concepts/services-networking/service/#externalname)

The services restore properly, but the restore results show an error saying `key ports not found`

**What did you expect to happen:**

There shouldn't be any errors in the restore results.

This is caused by the restore service action which clears out auto-assigned NodePort values from service ports.  It returns an error if `.spec.ports` isn't found.  Should be updated to not error here, at least for `ExternalName` services.

**Comment by carlisia** [comment]
Assigning this to myself, but it is actually for @shubheksha. Thank you!
