### ISSUE TITLE
Get rid of generated CLI docs

### ISSUE THREAD

**Issue by skriss** [heptio/ark#798]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Currently, we generate CLI documentation and store it in the repository.  This has questionable value and is a constant thorn in the side since contributors have to manually run `make update` to keep it updated, and builds fail if it's not updated.  We should remove the generated documentation and related steps from the build.

**Comment by ncdc** [comment]
💯

**Comment by shubheksha** [comment]
Are we planning to remove the docs from this repo altogether and move them out someplace else?
Either way, agreed that we should remove it from the build step. Maybe we can add a pre-commit hook for generating docs and formatting/linting?

**Comment by skriss** [comment]
@shubheksha we were thinking of entirely removing the generated CLI docs from the repo (along with the step in `make update` that generates them).  Odds are anyone that's looking for CLI docs just uses `ark <command> --help` anyway.

**Comment by shubheksha** [comment]
@skriss, that makes sense! Happy to take a stab at this :)

**Comment by skriss** [comment]
Awesome, thanks!!

**Comment by shubheksha** [comment]
@skriss, this mainly includes deleting the make targets, the relevant scripts and the docs themselves, right? Or am I missing something?

**Comment by ncdc** [comment]
@shubheksha that should be it.
