### ISSUE TITLE
API spec has a pointer as a return value. Please explain why ?

### ISSUE THREAD

**Issue by taherv** [heptio/ark#814]
The BlockStore API in the cloudprovider package has this function called `GetVolumeInfo`.

https://github.com/heptio/ark/blob/283a1349bdec670a1be0f3bfa19b07550c05b88f/pkg/cloudprovider/storage_interfaces.go#L81

A BlockStore plugin is expected to return a pointer to an int64, among other things ?
Why is that return value a pointer ? Shouldn't it be just an int64 ? What breaks if we don't have it as a pointer ?

**Comment by taherv** [comment]
Same question for the CreateVolumeFromSnapshot API ...
https://github.com/heptio/ark/blob/283a1349bdec670a1be0f3bfa19b07550c05b88f/pkg/cloudprovider/storage_interfaces.go#L71

Is the iops variable there an input parameter, an output parameter or both ? The documentation for this function suggests it is an input, why is it a pointer ?

**Comment by ncdc** [comment]
@taherv this is because `iops` is an optional piece of information that isn't always applicable. Some types of storage support iops, and others don't. IIRC, if we pass iops=0 when trying to create a volume (in `CreateVolumeFromSnapshot`), it results in an error if the storage type doesn't support specifying iops for the selected type of storage (and this may even vary by provider).

The godoc for GetVolumeInfo says
```go
// GetVolumeInfo returns the type and IOPS (if using provisioned IOPS) for
// the specified block volume in the given availability zone.
```
Do we need to make it clearer that iops is optional?

Same question for
```go
// CreateVolumeFromSnapshot creates a new block volume in the specified
// availability zone, initialized from the provided snapshot,
// and with the specified type and IOPS (if using provisioned IOPS).
```

**Comment by taherv** [comment]
Thanks for the explanation, I stand enlightened :)

Uggh! You are running against a golang language barrier (no optional arguments).
I understand there's no easy way out of it.

Maybe have Init() return some kind of capabilities data structure, where the plugin can express if it supports "provisioned iops" or not. You can then know when to pass 0 and when to pass an actual value.

The plugin framework is young, and you probably have a small ecosystem of plugin implementations, I would urge you to look for options and fix the API early on, this pointer approach just seems like a C++ way slapped onto golang.

**Comment by taherv** [comment]
Since I have got an explanation, as I had requested ... feel free to close this issue.

**Comment by ncdc** [comment]
Even if we used a `struct` for inputs (`CreateVolumeFromSnapshot`) and outputs (`GetVolumeInfo`), we still have to use a pointer. That's the only way to distinguish between 0 (unset) and 0 (zero).

**Comment by taherv** [comment]
Take a step back, and think about the API.
Not all PVs are for block devices, and so for some (e.g nfs) PVs, the plugin developer will be puzzled about what the field even stands for. The framework needs to abstract out a little bit more in this case.

**Comment by ncdc** [comment]
I understand your point. We could use an optional struct for block storage device options, or something like that.

**Comment by taherv** [comment]
You can return an interface (say PerfInfo, that has a method called GetIops()). 
For plugins that dont care about iops, they can return nil for the interface.

**Comment by taherv** [comment]
> https://github.com/heptio/ark/issues/814#issuecomment-418416971
That would work too, and you could use Init() for the plugin to express what it supports, if you like.

**Comment by ncdc** [comment]
All the plugins have to use protobuf-compatible messages. Can you do that easily with protobuf?

**Comment by ncdc** [comment]
https://github.com/heptio/ark/blob/283a1349bdec670a1be0f3bfa19b07550c05b88f/pkg/plugin/proto/BlockStore.proto

**Comment by taherv** [comment]
Another interface will need another proto definition, but I see your point .... its like we are being painted into a corner !

**Comment by ncdc** [comment]
I think we've concluded this discussion, so I'm closing it. Feel free to reopen if necessary.
