### ISSUE TITLE
Cannot restore secrets with owner reference set

### ISSUE THREAD

**Issue by mwieczorek** [heptio/ark#816]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

I have a cluster with Service Catalog installed and with some ServiceInstance/ServiceBindings created. Service Catalog is creating secrets for each ServiceBinding and setting owner reference in that secret.

I created a backup of those resources (ServiceInstance/ServiceBindings/Secrets) and wanted to test the restore procedure.

Unfortunately secrets were not restored. In logs I see such info message:
`time="2018-09-03T09:53:44Z" level=info msg="production/mwtest-binding has a controller owner - skipping" logSource="pkg/restore/restore.go:342"`

**What did you expect to happen:**
Secrets are restored

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Ref: [slack discussion](https://kubernetes.slack.com/archives/C6VCGP4MT/p1536059099000100?thread_ts=1535983065.000100&cid=C6VCGP4MT)

**Environment:**

- Ark version (use `ark version`):  0.9.0
- Kubernetes version (use `kubectl version`): 1.10.5
- Kubernetes installer & version: acs-engine, 0.20.0
- Cloud provider or hardware configuration: azure
- OS (e.g. from `/etc/os-release`): ubuntu

**Comment by ncdc** [comment]
@mwieczorek thanks for filing this!

@skriss @rosskukulinski IIRC, we had previously discussed removing the code that keeps us from restoring things that have controller owners. I _think_ we said we wanted to proceed with the removal. WDYT?

**Comment by rosskukulinski** [comment]
@ncdc Yep I think we were 👍 on moving forward with that change.  I believe #445 is the associated issue?

**Comment by ncdc** [comment]
@rosskukulinski yes-ish. The intent of #445 is what to do about controlled pods whose labels don't match their controller's labels. I'd say this issue is more appropriate for removing the code the doesn't restore controlled things.

**Comment by mwieczorek** [comment]
I agree with @ncdc - I’d just like to get ’controlled’ secrets and other resources restored.
And I would be happy if it gets into v0.10.0 ;)

**Comment by ncdc** [comment]
@mwieczorek would you be able to do a PR for this?

**Comment by rosskukulinski** [comment]
@ncdc this would be a change in default behavior (I'm +1 on that) -- do you think we should add a CLI flag to maintain current behavior?

**Comment by ncdc** [comment]
@rosskukulinski in this case, I don't think it's worth it. We will be moving toward a more faithful restoration of the contents in the source cluster. My assumption is this is a 100% positive improvement and that nobody will notice any detrimental effects.

**Comment by mwieczorek** [comment]
@ncdc Sure, I'll try to do it.

What about the 'breaking change'? Is mentioning it in docs and release notes enough?

**Comment by mwieczorek** [comment]
Also: do you recommend some e2e tests? I just removed 'ownerReference' check, tested my use-case and everything was working. But maybe I'm not aware of some details.

**Comment by ncdc** [comment]
@mwieczorek we don't have an e2e test framework yet, so no need for e2e tests at this time (but thanks for offering!). Another thing you could test is replicasets that were generated by the deployment controller - make sure they're restored correctly, with all their labels, annotations, etc.

**Comment by ncdc** [comment]
Oh, and I think mentioning this change in the v0.10 release notes will be sufficient (we'll take care of that).

**Comment by skriss** [comment]
Sorry, just catching up here.  One thing we're going to have to think about here is the order in which resources get restored.  If, for example, a deployment got restored before its associated replicaset, a new replicaset may be created on the cluster before the backed-up one gets restored.  Up until now, we've avoided actually having some kind of dependency graph of resources during restore by just doing a partial ordering based on things that we knew had dependencies.  But this may fall down if we start restoring all child objects.

**Comment by mwieczorek** [comment]
@skriss Good point. For "built-in" resource types, it should be easy to change `defaultRestorePriorities` list (f.e. add ReplicaSet). 
For CRDs - it could be the user's duty to modify the list appropriately

@skriss, @ncdc wdyt?

**Comment by ncdc** [comment]
> But this may fall down if we start restoring all child objects.

At worst, ark captures it as a warning.

I think we should adjust the default restore priorities to include replicasets and anything else we can think of that requires ordering.

We could also consider taking note of dependency ordering when taking the backup, and recording that information in the backup json and/or tarball. For example, if we back up a replicaset and see that it has a deployment owner, we could encode this ordering (replicaset before deployment) and use that information when restoring.
