### ISSUE TITLE
Ark Troubleshooting Two Clusters

### ISSUE THREAD

**Issue by rbankston** [heptio/ark#819]
**Describe the solution you'd like**

Update troubleshooting documentation to verify two clusters are replicating as expected. If the back ups are configured to use the same bucket and the first cluster is showing successfull backups the next step would be to  get the output of `ark restore get` from the second cluster and then `ark restore describe <last restore>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Ark version (use `ark version`): 0.9.3
- Kubernetes version (use `kubectl version`): 1.10
- Kubernetes installer & version: Kops
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Debian Jesse

**Comment by ncdc** [comment]
@rbankston would it be ok to wait to make these updates until backup replication is implemented in v0.11?

**Comment by rosskukulinski** [comment]
@ncdc I asked @rbankston to open this issue based on a ticket - 0.11 is fine IMO.

The user hadn't realized that Ark was running in a non-standard namespace (e.g. not `heptio-ark`) in the second cluster.  We could also add a troubleshooting step to look for `backup` CRDs across all namespaces using `kubectl`

**Comment by ncdc** [comment]
We actually might be able to do this as part of backup locations in 0.10. I don't think replication is necessary here.

**Comment by ncdc** [comment]
@rbankston is the relevant scenario?
- Cluster1 backs up to Bucket1
- Cluster2 wants to restore a backup from Cluster1
- Cluster2 points ark at Bucket1 in restore-only mode
- Cluster2 performs restore

**Comment by rbankston** [comment]
@ncdc That indeed is the relevant scenario

**Comment by skriss** [comment]
Closed by #1038
