### ISSUE TITLE
Failed calling admission webhook "deployment.admission.stash.appscode.com"

### ISSUE THREAD

**Issue by michaelwclark80** [heptio/ark#831]
Trying to run deployment.yaml and keep getting this error:

Internal error occurred: failed calling admission webhook "deployment.admission.stash.appscode.com"

**Comment by michaelwclark80** [comment]
Environment:

Ark version (use ark version): 0.9.3
Kubernetes version (use kubectl version): 1.9
Kubernetes installer & version: Kops
Cloud provider or hardware configuration: Azure
OS (e.g. from /etc/os-release): Ubuntu

**Comment by skriss** [comment]
Do you have stash installed in your cluster?  Looks like a webhook call related to it that intercepts all deployment creations is failing?

**Comment by michaelwclark80** [comment]
looks like someone installed Stash on this cluster.  This is going to be fun to remove.

Thanks!

**Comment by skriss** [comment]
No problem! closing this for now as it appears unrelated to Ark, but feel free to reopen if needed.
