### ISSUE TITLE
Ark pod in STATUS: CrashLoopBackOff

### ISSUE THREAD

**Issue by mehemken** [heptio/ark#836]
**What steps did you take and what happened:**
I've followed the instructions in the documentation:
- [Docs for AWS](https://heptio.github.io/ark/v0.9.0/aws-config)
- [Getting Started](https://heptio.github.io/ark/v0.9.0/quickstart)

However the ark pod goes into `CrashLoopBackOff`. I then run the nginx-example. When I take a backup it succeeds, however most of the fields in `ark backup describe nginx-backup` show up as `<none>`, `<n/a>`. Also, `ark` recognizes zero warnings and zero errors:

    $ ark get backups
    NAME           STATUS    CREATED                         EXPIRES   SELECTOR
    nginx-backup   New       2018-09-10 15:42:09 -0700 PDT   29d       app=nginx
    $ ark get restores
    NAME                          BACKUP         STATUS    WARNINGS   ERRORS    CREATED                         SELECTOR
    nginx-backup-20180910154449   nginx-backup   New       0          0         2018-09-10 15:44:50 -0700 PDT   <none>

After an `ark restore`: Even though the restore succeeds, the namespace `nginx-test` does not exist.

So I check if the pod is running:

    NAME                   READY     STATUS             RESTARTS   AGE
    ark-4179056932-dgc9r   0/1       CrashLoopBackOff   9          26m

Ok so I check the logs:

```
...
An error occurred: object storage provider name must not be empty
...
```

Ok so I check the Google. The Google says "**object storage provider name must not be empty**" shows up in the GitHub repo, but a Ctrl-F search on the page [Google points to](https://github.com/heptio/ark/blob/master/pkg/cmd/server/server.go) says the phrase does not exist. 😞 No other results.

I've checked that all the name fields in my configuration are set. Especially in the `Config` and `BackupStorageLocation` resources. I've set all the provider fields to aws.

```
---
apiVersion: ark.heptio.com/v1
kind: Config
metadata:
  namespace: heptio-ark-test
  name: default
persistentVolumeProvider:
  name: aws
  config:
    region: us-west-2

---
apiVersion: ark.heptio.com/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: heptio-ark-test
spec:
  provider: aws
  objectStorage:
    bucket: real-bucket-name
    config:
      region: us-west-2
```

The AWS user I'm using for this has all the permissions specified in the documentation. The bucket name in the IAM JSON is the correct bucket name. The bucket name in the YAML is the correct bucket name.

I've double checked that the namespace `heptio-ark-test` has been changed in all places. Including `ark client set namespace=heptio-ark-test`

# How to proceed?

For the life of me I can't think of how else to troubleshoot this. The only error I get results in zero Google results. The documentation says nothing about this issue. Nobody else seems to have seen this error.

How do I proceed in troubleshooting this?

# 🤦‍♂️

**What did you expect to happen:**
1. I should see something in the AWS Bucket
1. The `ark restore` should restore the nginx-example

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/ark -n heptio-ark`
```
time="2018-09-10T23:04:15Z" level=info msg="setting log-level to INFO"
time="2018-09-10T23:04:15Z" level=info msg="Starting Ark server v0.9.4" logSource="pkg/cmd/server/server.go:101"
time="2018-09-10T23:04:15Z" level=info msg="Checking existence of namespace" logSource="pkg/cmd/server/server.go:264" namespace=heptio-ark-test
time="2018-09-10T23:04:15Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:270" namespace=heptio-ark-test
time="2018-09-10T23:04:15Z" level=info msg="Checking existence of Ark custom resource definitions" logSource="pkg/cmd/server/server.go:299"
time="2018-09-10T23:04:15Z" level=info msg="All Ark custom resource definitions exist" logSource="pkg/cmd/server/server.go:332"
time="2018-09-10T23:04:15Z" level=info msg="Retrieving Ark configuration" logSource="pkg/cmd/server/server.go:337"
time="2018-09-10T23:04:15Z" level=info msg="Successfully retrieved Ark configuration" logSource="pkg/cmd/server/server.go:355"
time="2018-09-10T23:04:15Z" level=info msg="Using default resource priorities" logSource="pkg/cmd/server/server.go:405" priorities="[namespaces persistentvolumes persistentvolumeclaims secrets configmaps serviceaccounts limitranges pods]
"
time="2018-09-10T23:04:15Z" level=info msg="Configuring cloud provider for backup service" logSource="pkg/cmd/server/server.go:454"
An error occurred: object storage provider name must not be empty
```

* `ark backup describe <backupname>` or `kubectl get backup/<backupname> -n heptio-ark -o yaml`

```
Name:         nginx-backup
Namespace:    heptio-ark-test
Labels:       <none>
Annotations:  <none>

Phase:  New

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  app=nginx

Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  0

Started:    <n/a>
Completed:  <n/a>

Expiration:  0001-01-01 00:00:00 +0000 UTC

Validation errors:  <none>

Persistent Volumes: <none included>
```

* `ark backup logs <backupname>`

**hangs**

* `ark restore describe <restorename>` or `kubectl get restore/<restorename> -n heptio-ark -o yaml`

```
Name:         nginx-backup-20180910154449
Namespace:    heptio-ark-test
Labels:       <none>
Annotations:  <none>

Backup:  nginx-backup

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto

Phase:

Validation errors:  <none>

Warnings:  <none>
Errors:    <none>
```

* `ark restore logs <restorename>`
`An error occurred: unable to retrieve logs because restore is not complete`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
After writing the rest of this issue I noticed I could set the log-level to debug. All it told me was each custom resource it found... Something we already know from log-level INFO.

```
time="2018-09-10T23:41:55Z" level=info msg="setting log-level to DEBUG"
time="2018-09-10T23:41:55Z" level=debug msg="Found custom resource" kind=PodVolumeRestore logSource="pkg/cmd/server/server.go:321"
time="2018-09-10T23:41:55Z" level=debug msg="Found custom resource" kind=ResticRepository logSource="pkg/cmd/server/server.go:321"
time="2018-09-10T23:41:55Z" level=debug msg="Found custom resource" kind=Backup logSource="pkg/cmd/server/server.go:321"
time="2018-09-10T23:41:55Z" level=debug msg="Found custom resource" kind=Config logSource="pkg/cmd/server/server.go:321"
time="2018-09-10T23:41:55Z" level=debug msg="Found custom resource" kind=DownloadRequest logSource="pkg/cmd/server/server.go:321"
time="2018-09-10T23:41:55Z" level=debug msg="Found custom resource" kind=PodVolumeBackup logSource="pkg/cmd/server/server.go:321"
time="2018-09-10T23:41:55Z" level=debug msg="Found custom resource" kind=Restore logSource="pkg/cmd/server/server.go:321"
time="2018-09-10T23:41:55Z" level=debug msg="Found custom resource" kind=Schedule logSource="pkg/cmd/server/server.go:321"
time="2018-09-10T23:41:55Z" level=debug msg="Found custom resource" kind=DeleteBackupRequest logSource="pkg/cmd/server/server.go:321"
```

**Environment:**

- Ark version (use `ark version`):  0.9.4
- Kubernetes version (use `kubectl version`): Client 1.9 Server 1.7
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04

**Comment by ncdc** [comment]
I’m not at my computer so I can’t provide links, but if you’re using 0.9.x,
you need to be using the docs and examples for 0.9. BackupStorageLocation
is a new CRD that is in the master branch but not in any releases yet. You
need a backupStorageProvider section in the ark config with 0.9.

**Comment by mehemken** [comment]
@ncdc Hey Andy, thanks for that explanation! I'll give that a shot tomorrow.

**Comment by mehemken** [comment]
Ha. It worked. Thanks @ncdc !

**Comment by krol3** [comment]
Thanks! It works with the release branch 0.9 samples

**Comment by acbramley** [comment]
I got a similar error while using ark version v0.9.11, and the example config from the `release-0.9` git branch. The error was slightly different though:

`An error occurred: [custom resource BackupStorageLocation not found in Ark API group ark.heptio.com/v1, custom resource VolumeSnapshotLocation not found in Ark API group ark.heptio.com/v1, Ark custom resources not found - apply examples/common/00-prereqs.yaml to update the custom resource definitions]`

**Comment by ncdc** [comment]
Are you using the “latest” tag? It looks like you’re using the 0.10 server.

**Comment by acbramley** [comment]
@ncdc latest tag for what? The ark version I was using (when running `ark version`) was v0.9.11, and the config I used was from the examples directory from the release-0.9 branch (also tried from the v0.9.11 tag)

**Comment by ncdc** [comment]
For the image in the ark deployment

**Comment by acbramley** [comment]
@ncdc ahh yes you're right, the example in 0.9 uses `gcr.io/heptio-images/ark:latest` (https://github.com/heptio/ark/blob/v0.9.11/examples/minio/20-ark-deployment.yaml#L36) so that's where that'd come from. Nice catch!

**Comment by ncdc** [comment]
@roopagowda this issue has been resolved. Please ask your question in https://kubernetes.slack.com/messages/ark-dr or https://groups.google.com/forum/#!forum/heptio-ark. Thanks!
