### ISSUE TITLE
not authorized to perform backup on a specific namespace

### ISSUE THREAD

**Issue by bmihaescu** [heptio/ark#845]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

```
ark backup create cluster-backup
```

```
ark backup get 
cluster-backup   Failed      2018-09-14 09:08:35 +0000 UTC   29d       <none>
```

Failed do to UnauthorizedOperation when backing up monitoring namespace

**What did you expect to happen:**

backup Status become Completed

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/ark -n heptio-ark`
* `ark backup describe <backupname>` or `kubectl get backup/<backupname> -n heptio-ark -o yaml`
* `ark backup logs <backupname>`
* `ark restore describe <restorename>` or `kubectl get restore/<restorename> -n heptio-ark -o yaml`
* `ark restore logs <restorename>`

```
ark backup logs cluster-backup | grep error
time="2018-09-14T09:08:39Z" level=error msg="error creating snapshot" backup=heptio-ark/cluster-backup error="rpc error: code = Unknown desc = UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: 9d884399-599b-410e-9062-a38b070e8a70" group=v1 groupResource=pods logSource="pkg/backup/item_backupper.go:427" name=pvc-fa783f4f-b1aa-11e8-a206-0aa46911aea0 namespace=monitoring volumeID=vol-0c3885d80d8f3f5b2
time="2018-09-14T09:08:39Z" level=error msg="Error executing item actions" backup=heptio-ark/cluster-backup error="error creating snapshot: rpc error: code = Unknown desc = UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: 9d884399-599b-410e-9062-a38b070e8a70" group=v1 groupResource=pods logSource="pkg/backup/item_backupper.go:209" name=grafana-storage namespace=monitoring
time="2018-09-14T09:08:39Z" level=error msg="Error executing item actions" backup=heptio-ark/cluster-backup error="error creating snapshot: rpc error: code = Unknown desc = UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: 9d884399-599b-410e-9062-a38b070e8a70" group=v1 groupResource=pods logSource="pkg/backup/item_backupper.go:209" name=grafana-795b58bd54-l52td namespace=monitoring
```

**Environment:**

- Ark version (use `ark version`):  v0.9.4
- Kubernetes version (use `kubectl version`): v1.11.0 - client ; v1.10.3 - server
- Kubernetes installer & version: kops 1.10.0
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Amazon Linux 2

**Comment by skriss** [comment]
It looks like your `heptio-ark` IAM user is missing the necessary permissions to perform snapshots of your EBS volumes.  Have you configured the IAM user per https://github.com/heptio/ark/blob/master/docs/aws-config.md#create-iam-user ?

**Comment by bmihaescu** [comment]
Hi, 
Thanks for the reply. 
I'm using the keys from my fulladmin user so not sure what it can not work for monitoring namespace. 
For other namespaces also with EBS is working just fine.

**Comment by skriss** [comment]
could you try using those same credentials that are in the `cloud-credentials` secret to manually (using the AWS CLI) create a snapshot of one of those EBS volumes that are failing?

**Comment by bmihaescu** [comment]
I can create a snapshot with success using cli on that volume 
aws ec2 create-snapshot --volume-id vol-0c3885d80d9i2f5b2 --description "Test snapshot pvc" 
{
    "Description": "Test snapshot pvc",
    "Tags": [],
    "Encrypted": false,
    "VolumeId": "vol-0c3885d80d8f9i2b2",
    "State": "pending",
    "VolumeSize": 1,
    "StartTime": "2018-09-17T15:12:41.000Z",
    "Progress": "",
    "OwnerId": "12345662342",
    "SnapshotId": "snap-0c9e7649f322d66ff"
}

**Comment by bmihaescu** [comment]
/usr/local/bin/aws ec2 create-snapshot --volume-id vol-0c3885d80d9i2f5b2 --description "Test snapshot pvc" --tag-specifications "ResourceType=snapshot,Tags=[{Key=name,Value=test}]" 
{
    "Description": "Test snapshot pvc",
    "Encrypted": false,
    "OwnerId": "12345662342",
    "Progress": "",
    "SnapshotId": "snap-0b89fce02190f6e",
    "StartTime": "2018-09-17T16:00:26.000Z",
    "State": "pending",
    "VolumeId": "vol-0c3885d80d9i2f5b2",
    "VolumeSize": 1,
    "Tags": [
        {
            "Key": "name",
            "Value": "test"
        }
    ]
}


The first cmd also works.

**Comment by ncdc** [comment]
@bmihaescu were you ever able to resolve this issue?

**Comment by ncdc** [comment]
Closing. Please reopen if you need more assistance.
