### ISSUE TITLE
Namespace backup with volume-snapshot.

### ISSUE THREAD

**Issue by sachinar** [heptio/ark#846]
Hi Team, 
@ncdc @skriss 
We have some scenario where we have to take full namespace backup.
We tried with --include-namespace option but I think it is only taking namespace config backup.
So how we can take volume backup with namespace.

**Comment by skriss** [comment]
If you have a `persistentVolumeProvider` configured properly, and the namespace(s) you're specifying with `--include-namespaces` have pods that mount PVCs/PVs that are snapshottable (e.g. EBS), then the backup *should* include snapshots of those volumes.

Are you seeing something different?

**Comment by sachinar** [comment]
@skriss  I have already added `persistentVolumeProvider` & configured properly coz if I take backup of any pv it is coming with data. As I already mentioned ` --include-namespaces`  this option tried.

**Comment by skriss** [comment]
OK, please provide `ark backup logs <your-backup>` and `ark backup describe <your-backup>`.

**Comment by sachinar** [comment]
Thanks @skriss It worked.

**Comment by skriss** [comment]
Closing this issue - reach out if you have any further issues!
