### ISSUE TITLE
how to get backups of persistent volumes

### ISSUE THREAD

**Issue by dirtbag** [heptio/ark#851]
I ran  ark backup create test-backup --include-namespaces mynamespace 
and noticed that the backup files didnt include any of our persistent volumes.. I tried using 
ark backup create test-backup3 --include-namespaces mynamespace --snapshot-volumes
and got the error 
"Validation errors:  Server is not configured for PV snapshots"
when looking at the ark backup describe ...

[jwelsh@jwelsh-desktop heptio_ark]$ ark backup logs test-backup3
An error occurred: request failed: <?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: ark-lulu-backup/test-upp-backup3/test-upp-backup3-logs.gz</Details></Error>

**Environment:**
[jwelsh@jwelsh-desktop heptio_ark]$ ark version 
Version: v0.9.4
Git commit: v0.9.4
Git tree state: clean
[jwelsh@jwelsh-desktop heptio_ark]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"archive", BuildDate:"2018-04-26T09:29:05Z", GoVersion:"go1.10.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.6-gke.2", GitCommit:"384b4eaa132ca9a295fcb3e5dfc74062b257e7df", GitTreeState:"clean", BuildDate:"2018-08-15T00:10:14Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

this is on google cloud.

-db

**Comment by skriss** [comment]
To enable PV snapshots, you need to ensure you have this section in your Ark config:

https://github.com/heptio/ark/blob/release-0.9/examples/gcp/00-ark-config.yaml#L21

You're getting an error when trying to run `ark backup logs test-backup3` because the backup didn't even start, due to the validation error around not having PV snapshots configured.  So try again once you do the above!

**Comment by dirtbag** [comment]
thanks. after fixing that, it worked..
