### ISSUE TITLE
Removing stale scheduled backups

### ISSUE THREAD

**Issue by willtrking** [heptio/ark#854]
Would be awesome to be able to automatically remove scheduled backups, on a schedule. E.g. if I have a daily backup of a cluster, set a schedule to go through and delete backups that are older then a time delta.

Currently I create a schedule with:
`ark schedule create daily-backup --schedule "0 7 * * *"`

This could be changed to:
`ark schedule create backup daily-backup --schedule "0 7 * * *"`

With a corresponding
`ark schedule create backup-delete daily-backup-wipe --for-schedule daily-backup --schedule "0 7 * * *" --older-then=30d`

Fairly experienced with Go, would be interested in contributing this if it's deemed as desirable.

**Comment by ncdc** [comment]
@willtrking backups have a time-to-live (TTL) that you can set with the `--ttl` flag. Ark automatically deletes expired backups. Is this what you are looking for?

**Comment by willtrking** [comment]
Ah, yes! Thanks for that.

Does this work for scheduled backups as well?

**Comment by skriss** [comment]
@willtrking yes - you can use that same flag with `ark schedule create`

**Comment by willtrking** [comment]
Excellent, thank you!
