### ISSUE TITLE
Add an updates section to table of contents

### ISSUE THREAD

**Issue by nrb** [heptio/ark#856]
Our documentation could use a dedicate place for finding information on upgrading to various versions.

Right now, I'm thinking of a upgrades page that simply links out to documents for specific target versions. For example, the upgrades page would have a link to a v0.10.0 page, which would detail the various steps needed to upgrade to that version.

It will need to be added in to https://github.com/heptio/ark/blob/gh-pages/_data/default.yml so that new builds get it added. Since it's new, we'll also likely need a new v0.10 toc YAML file, too.

**Comment by dirtbag** [comment]
Yes I was just looking for information on how to upgrade ark from v.0.9.5 to v0.9.6
Any suggestions as I cannot find any docs on it?

-db

**Comment by skriss** [comment]
@dirtbag that should be an easy upgrade, no breaking changes.  Just update your image tags to `v0.9.6`!

**Comment by dirtbag** [comment]
I just deleted the pod and it pulled down the new version and updated automagically.

**Comment by skriss** [comment]
Just FYI, at some point you may want to switch to using specific version tags rather than `latest`, as there *will* be breaking changes when you upgrade to, e.g., `v0.10`.

**Comment by dirtbag** [comment]
sounds reasonable.. thanks for the info.

**Comment by Bradamant3** [comment]
Fixed in PR #1005 (not yet on built site but should be today)
