### ISSUE TITLE
set schedule on ark server boot

### ISSUE THREAD

**Issue by williamhuangh** [heptio/ark#858]
**Describe the solution you'd like**
is there a way to specify a schedule without having to hand-schedule using the cli? I'd like to create an ark server pod and have it configured with a schedule (perhaps a config option). I know that schedules persist after you create it, even if the pod for whatever reason gets killed, but it'd be great to be able to codify this portion as well

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Ark version (use `ark version`): v0.9.5
- Kubernetes version (use `kubectl version`): 1.10.8
- Kubernetes installer & version:
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): fedora 28

**Comment by williamhuangh** [comment]
figured i can just create a `Schedule` resource yaml -- is this the best way to go about this?

**Comment by ncdc** [comment]
@williamhuangh as you've discovered, Ark is API-based, using Kubernetes CustomResourceDefinitions. The `ark` CLI fills out a `Schedule` and `POST`s it to the kube-apiserver. Will creating a schedule yaml/json file meet your needs?

**Comment by williamhuangh** [comment]
yep it will! would be awesome to have some documentation on this -- what is the clusterName used for? seems to be blank inspecting our yaml, but the schedule functions perfectly

**Comment by sruon** [comment]
https://gist.github.com/sruon/1355db2230d651746e0541c731a2c873

Helm chart example to deploy ark Schedules.

Would be nice if the ark server Chart in helm/stable could support adding Schedules through a parameter but for the time being this will do.

**Comment by ncdc** [comment]
@williamhuangh where do you see `clusterName`?

@sruon I would recommend opening an issue in https://github.com/helm/charts about the chart feature request.

**Comment by skriss** [comment]
Closing this issue for now but feel free to reopen if needed.

**Comment by jaygorrell** [comment]
for others finding this issue when searching how-to, you can use `-oyaml` when creating a schedule with the cli to get the yaml manifest for version control
