### ISSUE TITLE
Switch to storing information about PV snapshots as VolumeSnapshot API objects

### ISSUE THREAD

**Issue by skriss** [heptio/ark#863]
- during backup, instead of storing snapshot info in `backup.status.volumeBackupInfo`, create a new VolumeSnapshot API object per snapshot
- upload a file containing all VolumeSnapshots' JSON for a backup into the backup's directory in object storage
- think about how this scales with large clusters/large # PVs - will we have too many API objects? should these only exist as files in S3?

**Comment by skriss** [comment]
I'm thinking about how this will work for v0.10 if a user wants to import backups from Cluster A to Cluster B.  Our current design has the `VolumeSnapshot` object storing the `Location` (i.e. `VSL`) as a field. So, on import to Cluster B, the naive approach would require that a VSL with the same name (and same config) exist in Cluster B as in Cluster A.

We're planning to do more sophisticated things in v0.11, that will require changes to the `BlockStore` plugin interface - but, for v0.10, do folks think that requiring that the VSL be named the same in Cluster A and Cluster B if a user wants to do a cross-cluster import is acceptable?

cc @nrb @carlisia @wwitzel3 @ncdc

**Comment by nrb** [comment]
> think about how this scales with large clusters/large # PVs - will we have too many API objects? should these only exist as files in S3?

s/S3/object storage/ ;)

>  for v0.10, do folks think that requiring that the VSL be named the same in Cluster A and Cluster B if a user wants to do a cross-cluster import is acceptable?

IMO, yes. As a first pass, I think this is acceptable, especially given we're planning to do some betas. If we receive feedback that it's too limiting, then we can change.

**Comment by carlisia** [comment]
@skriss if this simple strategy works, I'd go with it and fix potential issues if/when we come across it.

**Comment by skriss** [comment]
Tim thinks it might be a bad idea to use etcd to store this kind of information.  I guess there's no real reason, at least for right now, that these need to be stored as custom resources.  We could exclusively store them as JSON in a file in object storage, and just download them as needed to do restores.

We will need to think about implications for replication, since we were planning to use this CRD for that as well.

**Comment by ncdc** [comment]
I had a feeling he would recommend against etcd. When you have time, could you do a bit more of a walkthrough into how it would have worked with a CRD, and what is missing that we have to rework if it's not?

**Comment by skriss** [comment]
For v0.10, switching to just storing this info as JSON in object storage is pretty simple.  We weren't actually planning to use the CRD to drive any processing, it was just an in-cluster record of the snapshots that existed, and the JSON representation of them is getting uploaded to object storage anyway.  I think we'd remove the CRD, just define a basic go struct to represent them, then serialize a list of them and upload them.  

For v0.11, we were planning to use the VolumeSnapshot CRD as a work queue for snapshots that needed to be replicated due to a ReplicationPolicy.  The way this would work is that we'd have a ReplicationController that was watching for new combinations of ReplicationPolicy + matching Backup that needed to be replicated.  When one was found, if it included PV snapshots, a new VolumeSnapshot CR would be created.  A separate SnapshotReplicationController would be processing these and executing the snapshot copy.  The VolumeSnapshot CR would then also contain the status information about whether a snapshot was replicating, replicated, or in some other state.

We could replace the VolumeSnapshot CR with a SnapshotReplicationRequest or something like that - it would be short-lived, would essentially go away once the snapshot was replicated.  Each backup storage location would then store a JSON file (or files) containing information about all of the snapshot copies that existed for each backup.  That way we'd still have the benefit of a separate CR/controller to handle the copying logic, but wouldn't have the drawback of amassing a large number of these over time.

I think this would be a reasonable approach.  It is slightly more convenient to have an API-based representation of all volume snapshots, but it's not that bad to just store that info in object storage and download it as needed.

**Comment by ncdc** [comment]
Recording what we discussed earlier today for posterity: 👍 to proceed with this approach (don't store volume snapshot data as CRs).

**Comment by carlisia** [comment]
I'm pretty sure this can be closed, right? @skriss
