### ISSUE TITLE
ark restore logs doesn't work for restores of backups with hyphenated names

### ISSUE THREAD

**Issue by skriss** [heptio/ark#87]
https://github.com/heptio/ark/blob/master/pkg/cloudprovider/backup_service.go#L214

This breaks when the backup is named, e.g., `nginx-backup`.  Will likely have to do a regex to match the timestamp at the end.

**Comment by ncdc** [comment]
I knew that was probably too simple 😄

**Comment by skriss** [comment]
yeah, looked funny to me when i reviewed but i couldn't find a reason why...now we know :)

**Comment by ncdc** [comment]
Probably should do a "last index of" check on the -

**Comment by ncdc** [comment]
Working on a fix
