### ISSUE TITLE
Minor code clean up

### ISSUE THREAD

**Issue by carlisia** [heptio/ark#875]
It'd be worthwhile to address these two suggestions on `service_action.go`...

...this for consistency:
https://github.com/heptio/ark/pull/869#discussion_r220346006

...and this for better logic flow:
https://github.com/heptio/ark/pull/869#discussion_r220346670

**Comment by prateekpandey14** [comment]
@carlisia happy to take this .

**Comment by ffd2subroutine** [comment]
@carlisia @prateekpandey14 oh sorry I've already submitted a pull request for this one.
