### ISSUE TITLE
Isolating backups by namespace

### ISSUE THREAD

**Issue by kratos81** [heptio/ark#878]
We have different dev teams that have objects in their individual namespaces.  We are looking at a solution where they can only backup items in their namespaces and not have the ability to backup anything anywhere else ( same with restore ) , is this possible ? if so how ?

Would a combination of clusterrole and rolebindings be able to achieve this ?

Thanks and anticipating your response .

**Comment by skriss** [comment]
Responded on slack: 

> this isn’t something that we’ve tested or explicitly added support for, though it’s on our backlog. one thing you could try is having multiple instances of ark in different namespaces, each of which only has access to backup/restore a single namespace (instead of having the ark service account be `cluster-admin`, use RBAC to restrict each instance to only be able to access a single NS). then only give users access to the ark instance that can backup their namespace.  big disclaimer though that we haven’t really tested this, there may be issues that prevent it from working, and it might be too burdensome to manage multiple installs

**Comment by skriss** [comment]
xref #18

**Comment by skriss** [comment]
@kratos81 closing this issue, but feel free to subscribe to #18 or add comments their on your use cases for consideration. thanks!
