### ISSUE TITLE
Enable to start ark-server without defined default BackupStorageLocation

### ISSUE THREAD

**Issue by mwieczorek** [heptio/ark#898]
**Describe the solution you'd like**

In next ark version (v0.10) the default BackupStorageLocation is required (without setting it I get `An error occurred: backupstoragelocations.ark.heptio.com "default" not found` and ark-server crashes). 
Is it possible to make it optional? 
My use-case is that during ark installation details about future backups (where to store them) may not be available.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Slack discussion:
Ref: https://kubernetes.slack.com/archives/C6VCGP4MT/p1538489856000100

**Environment:**

- Ark version (use `ark version`): master tag
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by ncdc** [comment]
👍 here. I think the ark server should be able to start without a default BSL

**Comment by nrb** [comment]
I think that makes sense. Would updating the `Deployment` with the argument be sufficient for providing the BSL after the fact? Or do we want another way to update them?

**Comment by mwieczorek** [comment]
@ncdc @nrb What about annotation on BSL, similar like annotation on storageclass which is marking it as default?
So on storageclass we can have:
```
annotations:
  storageclass.kubernetes.io/is-default-class: true
```

can we have something similar on BSL:
```
annotations:
  backupstoragelocation.ark.heptio.com/is-default: true
```
When a backup is created without pointing to BSL:
- if no BSL is annotated - error
- if only one is annotated - proceed 
- if more than 1 is annotated - error

**Comment by ncdc** [comment]
My preference would be to have a default name (`default`) that the person
deploying Ark can override (`ark server --default-backup-storage-location
my-awesome-bsl`). I'd rather use first-class primitives over annotations if
possible.

And to Nolan's question, I do think it's fine to update the Deployment to
change the ark server flag's value to update to a new default BSL. I don't
expect this is something that would happen frequently - or am I wrong here?

**Comment by skriss** [comment]
I would not expect this to change frequently, no.

In the absence of a server default, I assume we'd just require that users explicitly specify a location when creating a Backup?

**Comment by ncdc** [comment]
Yes, if there is no default, the backup should probably end up with a validation error that there is no default and the user didn't specify a location.
