### ISSUE TITLE
More Sam Account Token issues when sam account and pod are collectively deleted and restored

### ISSUE THREAD

**Issue by james-powis** [heptio/ark#909]
Service Account Tokens are ephemeral, and stateless, created when a service account is created. Mounting of the service-account-token into volumes as part of the init stage of restic restores results in the init pod failing to start, thus failing the restic portion of the restore (though the pod is restored none the less to an empty functional status.

```
   default:  error restoring /tmp/293264120/resources/pods/namespaces/default/test-jenkins-99fbbdb95-8rms7.json: Pod "test-jenkins-99fbbdb95-8rms7" is invalid: spec.initContainers[1].volumeMounts[4].name: Not found: "test-jenkins-token-mbgcr"
```

I will get a PR to address this issue.

#840 had similar symptoms

**Comment by nrb** [comment]
PR's merged but apparently GitHub didn't pick it up. Closing the issue.
