### ISSUE TITLE
Question about PV/snapshot restores. 

### ISSUE THREAD

**Issue by dirtbag** [heptio/ark#917]
Hey folks, I we have a couple of ark backups on the same PV, it appears that we get multiple snapshots for that volume of varying sizes.  
![snap1](https://user-images.githubusercontent.com/808514/46745292-c64fe000-cc7a-11e8-84c6-eb445656dd7c.jpg)

So it looks like 
in this instance we have 3 snapshots of the same PV. I'm  curious how ark handles restores for a PV when you have multiple copies like this.

regards,
db

**Comment by ncdc** [comment]
Hi @dirtbag, thanks for your question. Would you mind posting this instead to our Google Group, https://groups.google.com/forum/#!forum/heptio-ark?

**Comment by skriss** [comment]
Responded on google group.
