### ISSUE TITLE
`ark backup download` has issues when you run `ark` as a container

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#93]
`ark backup download` is “not working” because when you run ark in a container, it tries to write to `$(pwd)/<file>`, and 1) that’s inside the container’s filesystem, and 2) `$(pwd)` is `/`, so it tries to write to `/<file>`. Additionally if you specify `--output FILE`, that path is inside the container, so it either needs to be a bind mount from the host, or you'll have to `docker cp` to get the file out.

It works if you’re running the binary natively.

If we set `WORKDIR` in the `Dockerfile` to something like `/host_pwd`, then bind mount `-v $(pwd):/host_pwd`, it works, although 1) you’re bind mounting whatever your current working dir is into the ark container, which might not be desirable 100% of the time, and 2) when it does download, it says `Backup foo has been successfully downloaded to /host_pwd/foo-data.tar.gz` instead of the real name of the dir on the host

**Comment by ncdc** [comment]
I think I want to change the default to write to `stdout`, so that when you run ark containerized, you can just do `ark backup download foo > foo.tar.gz`. WDYT? cc @jrnt30

**Comment by jrnt30** [comment]
I typically don't like tools streaming binary as the default behavior and I may have less accommodating view on this "just working" out of the box.  I personally think that the tool should be setup to use as an installed binary locally first, and then provide a mechanism for it working in a container. 

While not a direct solution to probelm, one way that we (credit to @fenixx for thinking of it) have had success creating "cli-tools" containers for clients to centralize "all the tools you need" is to mount the the $HOME into the container as the same destination in the container. 

```
  -e HOME="$HOME" \
  -v "$HOME:$HOME" \
  -w "$(pwd)" \
```

That being said, it's more difficult for users to get bootstrapped as you are using a wrapper script to get the variables all mapped in properly.  

If our approach is "docker first" for the CLI tool, then it may be worth defaulting to `stdout`

**Comment by skriss** [comment]
No longer an issue a/o #148
