### ISSUE TITLE
Docs about running Ark locally using Minikube

### ISSUE THREAD

**Issue by shubheksha** [heptio/ark#931]
It'd be useful to have information regarding running Ark locally for those contributors who don't have the option of testing/running using cloud providers.

**Comment by shubheksha** [comment]
Relevant info to include in #867

**Comment by ncdc** [comment]
I don't have time right now to do a PR for it, but this is what I usually do:

1. Install minikube
1. Apply all the relevant example yaml (prereqs, minio but not an ark deployment)
1. Edit the minio service and change its type to `NodePort`
1. Edit the ark configuration that points to minio so it uses the NodePort (you can get this info from `minikube service list` iirc)
1. Compile ark
1. Run `ark server [options]`, making sure `ark` is on your `$PATH`, or specify the path to it

**Comment by Bradamant3** [comment]
This seems pretty straightforward: it's effectively the quickstart with a reassurance that you can do it on minikube, yes? (plus info about `NodePort`).

Possibly related: clean up on-prem references also (done, but could be improved?). Where and how to run Ark not on cloud generally could use clarification.

**Comment by ncdc** [comment]
@Bradamant3 xref 
https://github.com/heptio/ark/issues/989#issuecomment-433420268

**Comment by skriss** [comment]
Closed by #1023
