### ISSUE TITLE
restore controller: remove code that checks backup storage directly for a backup

### ISSUE THREAD

**Issue by skriss** [heptio/ark#945]
If the restore controller can't find the requested backup in the Kube API, it checks backup storage directly.  This was implemented primarily for the scenario where Cluster B was importing backups from Cluster A, and Cluster B hadn't run a sync loop since the desired backup was taken in Cluster A.

With the sync controller changes in #825, the sync process now runs every minute.  The issue described above should no longer be material.  I'm proposing removing the code in the restore controller that checks backup storage directly, for simplification.

**Comment by ncdc** [comment]
👍

**Comment by shubheksha** [comment]
I'll pick this up!

**Comment by shubheksha** [comment]
@skriss/@ncdc, I believe this needs to be removed too: https://github.com/heptio/ark/blob/master/pkg/controller/restore_controller_test.go#L235-L236?

**Comment by skriss** [comment]
Closed by #1022
