### ISSUE TITLE
Test 0.10 on AWS

### ISSUE THREAD

**Issue by carlisia** [heptio/ark#958]
v 0.10

Basic functionality
- [ ] Basic install doc/example instructions all good
- [ ] Setup multiple backup storage locations and test
- [ ] backup, restore, delete, schedule

Cross-cluster scenarios
- [ ] backup in Cluster A, restore into Cluster B

Upgrade from 0.9.x to 0.10:
- [ ] Install v 0.9.8
- [ ] take a bunch of backups
- [ ] Upgrade to v 0.10
- [ ] Config multiple backup storage locations
- [ ] backup, restore, delete, schedule

**Comment by skriss** [comment]
@carlisia should this be closed at this point?

**Comment by carlisia** [comment]
Yes
