### ISSUE TITLE
Address Config CRD removal in v0.9 -> v0.10 upgrade

### ISSUE THREAD

**Issue by nrb** [heptio/ark#961]
**What steps did you take and what happened:**

#949 removed the Config CRD and relevant documentation, but we don't have upgrade documentation relevant to those yet.

**What did you expect to happen:**

We should have set of instructions or small scripts to help users move from a `Config` in their v0.9.x install to a set of `BackupStorageLocation`s, `VolumeStorageLocation`s, and command line flags.  Users will need these in order to test the beta, and we may need to refine them based on user feedback.

**Comment by skriss** [comment]
@nrb I thought we decided we wanted users to explicitly set these up when upgrading rather than automating it in some way.  I think the setup instructions + examples adequately cover how to set them up?

**Comment by nrb** [comment]
> I thought we decided we wanted users to explicitly set these up when upgrading rather than automating it in some way.

I think you're right. Let me review the upgrade doc you wrote again. I know you had a section for the layout of the object storage.

**Comment by carlisia** [comment]
I didn't think automating this would be required. When I get to testing upgrading I'd be glad to write additional instructions to this tix if I think what's there is not clear enough.

**Comment by tomplus** [comment]
I've just upgraded my instance to version 0.9.8 and I also noticed that you removed 'config' objects from docs. I wasn't aware that it's just planned to v0.10 so I removed the default config and created new `BackupStorageLocation`. Now I get

```
time="2018-10-22T10:13:42Z" level=info msg="Will attempt to retrieve configuration again in 5 seconds" logSource="pkg/cmd/server/server.go:352"
time="2018-10-22T10:13:47Z" level=info msg="Configuration not found" logSource="pkg/cmd/server/server.go:350"
```

Is it ready to use?

**Comment by ncdc** [comment]
@tomplus the `config` is still required in 0.9.x. `BackupStorageLocation` is new for 0.10.x only.

Here are the docs for the latest stable version (which is still 0.9.x): http://heptio.github.io/ark/

**Comment by skriss** [comment]
@nrb @carlisia I do think it'll be worthwhile to have a dedicated "upgrading to v0.10" page that we can link to in the release notes.  We can explain the Config -> BSL/VSL change and link to examples, and also can link to https://github.com/heptio/ark/blob/master/docs/storage-layout-reorg-v0.10.md.

**Comment by carlisia** [comment]
Agree, especially since your new PR. It's information that we need to follow for our tests also, so doubly helpful.

**Comment by nrb** [comment]
Yeah, I'd like to see an `Upgrading` section and `v0.10` under it with the required actions - that would be an acceptable solution to this in my mind. I know we've already started with the storage layout, but will be worth making sure it's comprehensive.
