### ISSUE TITLE
Enable setting metadata.ownerReference in RestoreItemAction plugin

### ISSUE THREAD

**Issue by mwieczorek** [heptio/ark#965]
**Describe the solution you'd like**
I'd like to backup/restore resources related to [service catalog](https://github.com/kubernetes-incubator/service-catalog).
When you create ServiceBinding (CRD from service catalog) there's also created a secret with ownerReference set to that ServiceBinding.

When I restore the secret on another cluster the ownerReference is deleted ( [code](https://github.com/heptio/ark/blob/master/pkg/restore/restore.go#L1007) ).

I'd like to be able to restore the secret with ownerReference set.

I don't want to preserve the old ownerReference because the uid of restored SB is different than from the origin cluster.

I'd like to set the new one, f.e. by plugin. But looking through the code I think it's not possible now because the resetMetadata is after the plugin execution, am I right?

Is it possible to move plugin execution after the metadata reset?

**Anything else you would like to add:**
Ref: [slack thread](https://kubernetes.slack.com/archives/C6VCGP4MT/p1539952674000100)

One more 'nice to have': 
is it possible to pass to plugin not only object with deleted metadata but also original object read from the backup? 
If I get object with deleted metadata I have to rely on secret's name (which I think should be equal to SB name) but if I get object from the backup I can get old ownerReference.

**Environment:**

- Ark version (use `ark version`): master
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by ncdc** [comment]
> is it possible to pass to plugin not only object with deleted metadata but also original object read from the backup?

If we move the execution of the restore item actions first, before resetting metadata, that would do what you need, wouldn't it?

**Comment by mwieczorek** [comment]
> > is it possible to pass to plugin not only object with deleted metadata but also original object read from the backup?
> 
> If we move the execution of the restore item actions first, before resetting metadata, that would do what you need, wouldn't it?

In such case I have access to the original object, but even if I change the uid in ownerReference than it will be deleted in resetMetadata step.

**Comment by ncdc** [comment]
Right. It's times like this when having all the objects in memory at the same time, prior to restoration, would be useful. But Ark isn't currently set up that way, so the options I can think of are:

1. Run restore item actions, then reset metadata (don't strip ownerReferences)
1. Reset metadata, then run restore item actions (modify interface as you suggested, to include original object's state too)
1. Move to a 2-pass system, where pass 1 has Ark read all objects so it can set up proper ordering, and pass 2 is restoring into the cluster. This would allow us to make your plugin generic - find all objects with ownerReferences, add all the owners to the top of the priority list, restore all the owners first, then recreate ownerReferences with the right data (uids). I don't think this idea is fool-proof, however; we currently restore pods before replicasets, for example, so the pods are preexisting and can therefore be adopted by replicasets. This idea would break that (it would create the replicasets first, giving them time to create new pods on their own before Ark can restore the pods from the backup).

Let's keep the discussion going. Hopefully we can come up with a good solution! @heptio/ark-team please weigh in too!

**Comment by nrb** [comment]
#3 seems like the biggest change, but might also help with things like https://github.com/heptio/ark/issues/314. Both of these issues want to create something additional to the item currently being processed, though this one is creating a new item vs getting another out of the backup.

I think we've briefly discussed a 2 pass system before, but not in detail. I think I'm in favor of brainstorming around it, even if we decide it's not the right direction.

**Comment by mwieczorek** [comment]
Option 1 can cause deletion of restored object if there will be no plugin for the restore action.
Option 2 will be sufficient for me because I can set the prioryty of restore in config and it will works
Option 3 - the easiest one for users especially if there will be a generic plugin for updating uids. but also in theory there can be a cyclic  dependency.

**Comment by carlisia** [comment]
Before I read @nrb's response I was thinking option 3 would be more flexible in the long term. I agree with what @nrb, we should at least brainstorm it. So, my opinion: either brainstorm option 3 and see if it's worth implementing, or implement option 2 and add option 3 to the backlog for later.

**Comment by mwieczorek** [comment]
One more thing: option 3 will override restore priority set in config. So in case of option 3 maybe it should be an opt-in?

**Comment by mwieczorek** [comment]
I know you're busy with 0.10 release but I would like to move it forward. 
What do you think about going first with option 2 and leave additional enhancements as a backlog issue?

**Comment by mwieczorek** [comment]
@ncdc Is it possible to extract part of this issue (`modify interface as you suggested, to include original object's state too`) and add it to the epic #1088 ?

**Comment by ncdc** [comment]
@mwieczorek yes, however, the ownerReference typically includes the UID of the owning object. As we've seen in #1037, if Ark creates an object and preserves the ownerReference of the original object, including its original UID, the cluster most likely will end up with too many copies of things (see my description in 1037 for more details).

And, as I wrote above, if we do

1. Restore owner e.g. ReplicaSet
1. Get UID of owner
1. Restore pod, setting its ownerReference to ReplicaSet + new UID from 2

it's possible & likely that Kubernetes will have already created a pod as soon as we restore the ReplicaSet.

Have any suggestions?

**Comment by ncdc** [comment]
There is also #612 asking for the backup/restore to be passed to the backup and restore item actions. Not 100% related to this request, but another possible change to the signatures.

**Comment by mwieczorek** [comment]
@ncdc I fully agree that setting new UID f.e. for pods doesn't make sense. And I don't want to be done by Ark itself.
What I'd like to be able to do is to enable plugins to set new UID. But for now, in plugins I don't have original UID and other metadata from ownerReference (ownerReference is deleted from the object before the plugins are executed).

So what I propose is to only modify the interface of the plugin and additionally pass into it the original object (from which I can get the original ownerReference kind, name, etc).

We can narrow the scope of this issue to only such change or create a new one (let me know what do you think). 

Regarding #612 - it also extends the interface but not with the original object but with backup definition itself.

**Comment by ncdc** [comment]
I'll open a new issue for expanding the interface and then I guess we can close this one?

**Comment by ncdc** [comment]
New issue is https://github.com/heptio/ark/issues/1092

**Comment by mwieczorek** [comment]
Yes, I'll close this one. Thanks.
