### ISSUE TITLE
[v0.10] support restoring backups w/snapshots taken prior to v0.10

### ISSUE THREAD

**Issue by skriss** [heptio/ark#966]
Prior to v0.10, Ark backups store metadata about PV snapshots as a map in their status (`.status.volumeBackups`).  A/o v0.10, this information is moving into a JSON file that gets stored in object storage (see #922).  As part of this, the JSON file will store the `VolumeSnapshotLocation` where the snapshot is stored.  This raises an issue around how v0.10 will restore backups taken prior to v0.10 that include snapshots.

My proposal is:
- retain the `.status.volumeBackups` field, but mark it deprecated/read-only
- during a restore, if a backup has *both* a `.status.volumeBackups` field and a volumesnapshots JSON file, immediately error and return (possibly fail validation?), as Ark should never put a backup into this state.
- during a restore, if a backup has the `.status.volumeBackups` field, restore the snapshots *only if* there is only a single VolumeSnapshotLocation configured, making it obvious where the snapshots are expected to be.

I think this is reasonable because (a) it keeps the amount of backwards-compatibility code very small, (b) I expect that the vast majority of users will only have a single VolumeSnapshotLocation configured, and (c) over time, these "legacy" backups will expire and be garbage-collected, making it easier for us to officially drop support for them in subsequent releases.

Appreciate input from everyone! cc @wwitzel3 @nrb @carlisia @ncdc

**Comment by ncdc** [comment]
> retain the .status.volumeBackups field, but mark it deprecated/read-only

and stop filling it in for 0.10 and later, right?

> during a restore, if a backup has the .status.volumeBackups field, restore the snapshots only if there is only a single VolumeSnapshotLocation configured, making it obvious where the snapshots are expected to be.

What is the behavior if there are 2 or more VSLs?

**Comment by skriss** [comment]
Correct, stop filling it in (hence read-only)

I'd probably lean towards having the restore fail validation if there's >1 VSL -- fail fast.

**Comment by ncdc** [comment]
👍

**Comment by nrb** [comment]
Also :+1:

**Comment by wwitzel3** [comment]
👍

**Comment by carlisia** [comment]
👍
