### ISSUE TITLE
Grammatical error in Readme file

### ISSUE THREAD

**Issue by ManavpreetSingh** [heptio/ark#968]

**Comment by skriss** [comment]
Closed by #969

**Comment by ManavpreetSingh** [comment]
Respected sir,

At the time of events I didn't received the Hacktober Fest T-shirt. I
request you to please deliver at the address which was provided in the
submission of form.

Thank you.

**Comment by carlisia** [comment]
@ManavpreetSingh you will have to contact the organization responsible for the Hacktober Fest for any enquiry related to that event. Here you can find information about rules and how to contact them: https://hacktoberfest.digitalocean.com/details
