### ISSUE TITLE
[v0.10] update `ark backup describe` for the changes to volume snapshot info storage

### ISSUE THREAD

**Issue by skriss** [heptio/ark#973]
With #922, information about volume snapshots is no longer stored as part of the Backup CRD.  The `ark backup describe` command used to display this information directly from the status.  It needs to be updated to work with the new design.  My proposal:

- [ ] add 2 new fields to `Backup`'s status, `VolumeSnapshotsAttempted` and `VolumeSnapshotsSucceeded`
- [ ] by default, `ark backup describe` will only display this summary information (e.g. `2 of 3 volume snapshots completed successfully`)
- [ ] change the current `--volume-details` flag on `ark backup describe` (used to show details of restic snapshots) to a generic `--details` flag
- [ ] add a new `DownloadRequest` target type, for the `<backup>-volumesnapshots.json.gz` file in object storage
- [ ] if the `--details` flag on `ark backup describe` is specified, download the volumesnapshots file from obj storage (similarly to how restore results are downloaded) and display the detailed info

@nrb @wwitzel3 @carlisia @ncdc WDYT?

**Comment by ncdc** [comment]
It all seems reasonable to me. I wonder if people will notice and understand the `--details` flag?

**Comment by skriss** [comment]
Currently the output of the describer if `--volume-details` is not specified has a note that it can be specified to get more info -- I'd probably do the same here so folks know it's an option

**Comment by carlisia** [comment]
Yes, this makes sense. 👍

**Comment by nrb** [comment]
@skriss Yep, I'd agree with having the note so it's more easily discoverable.

For your first point, do we want to add a Prometheus metric to that, based on schedules like the rest?

The rest seems reasonable.
