### ISSUE TITLE
Docs related issues from Ark v0.10 Testing

### ISSUE THREAD

**Issue by carlisia** [heptio/ark#978]
- [ ] This section has a reference to Config, which no longer exists https://github.com/heptio/ark/blob/master/docs/build-from-scratch.md#prerequisites-1
- [ ] This section instructs to setup multiple backets, but should we instruct to use the prefix instead? https://github.com/heptio/ark/blob/master/docs/aws-config.md#create-iam-user

**Comment by Bradamant3** [comment]
Fixed in PR #1004
