### ISSUE TITLE
[v0.10] pre-v0.10 backups fail to restore or delete after upgrade

### ISSUE THREAD

**Issue by skriss** [heptio/ark#982]
After upgrading from v0.9.x to v0.10, backups taken with v0.9.x fail to restore or delete.  This is because they don't have a value for the `.spec.storageLocation` field, and neither the restore controller nor the backup deletion controller apply any defaulting here.

I was able to work around the issue by deleting the backup CRs from the cluster, and allowing the backups to be re-synced into the cluster by the sync controller.  The sync controller updates the `.spec.storageLocation` field based on the name of the `BackupStorageLocation` it's syncing, which has the effect of populating this field for pre-v0.10 backups.

We could just make this part of the upgrade instructions - users should delete their backup CRs and allow them to be re-synced in - rather than making additional code changes to support these legacy backups.  I do think it's preferable to get this field populated rather than to have backups around that don't have a storageLocation specified.  What do you all think?

@nrb @carlisia @wwitzel3

**Comment by ncdc** [comment]
I'd recommend against having users "delete" anything, even if it's just the CRs. I'm imagining someone accidentally running `ark backup delete` instead of `kubectl delete` and ending up with their backup deleted.

**Comment by nrb** [comment]
I'd agree that deleting the CRs isn't my first choice. Perhaps during start up we try to find all backup CRs that are currently in cluster and try to pull them from the default BackupStorageLocation, and updating them? That is, unfortunately, extra code we'd have to maintain, but it seems in line with bookkeeping we've done like removing the finalizers previously.

**Comment by ncdc** [comment]
I don't think it'd be too much code in the backup sync controller to do an update if the `spec.storageLocation` is missing?
