### ISSUE TITLE
Ark not backing-up Persistent volumes created from glusterfs

### ISSUE THREAD

**Issue by suhas184** [heptio/ark#990]
**What steps did you take and what happened:**
created a backup of jenkins deployment/persistentvolume/service 
ark backup create jenkins-backup --selector app=jenkins_backup --snapshot-volumes

**What did you expect to happen:**
Expected the Persistent volume to be part of the backup.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
---------------------------------------------------------------------------------------------------------------
Name:         jenkins-backup
Namespace:    heptio-ark
Labels:       <none>
Annotations:  <none>

Phase:  Completed

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  app=jenkins_backup

Snapshot PVs:  true

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2018-10-24 12:11:21 +0000 UTC
Completed:  2018-10-24 12:11:22 +0000 UTC

Expiration:  2018-11-23 12:11:21 +0000 UTC

Validation errors:  <none>

Persistent Volumes: <none included>
--------------------------------------------------------------------------------------------------------

time="2018-10-24T12:11:21Z" level=info msg="PersistentVolume is not a supported volume type for snapshots, skipping." backup=heptio-ark/jenkins-backup group=v1 groupResource=persistentvolumeclaims logSource="pkg/backup/item_backupper.go:415" name=pvc-66ec48b9-d785-11e8-8f41-06eac1675816 namespace=default
time="2018-10-24T12:11:21Z" level=info msg="Evaluating resource" backup=heptio-ark/jenkins-backup group=v1 groupResource=persistentvolumes logSource="pkg/backup/resource_backupper.go:138"
time="2018-10-24T12:11:21Z" level=info msg="Listing items" backup=heptio-ark/jenkins-backup group=v1 groupResource=persistentvolumes logSource="pkg/backup/resource_backupper.go:253" namespace=
time="2018-10-24T12:11:21Z" level=info msg="Retrieved 0 items" backup=heptio-ark/jenkins-backup group=v1 groupResource=persistentvolumes logSource="pkg/backup/resource_backupper.go:265" namespace=

**Anything else you would like to add:**
kubernetes cluster is running on aws
glusterfs is running in the k8s cluster as pods.
jenkins pvc is created from glusterfs storageclass

**Environment:**

- Ark version (use `ark version`):  
Version: v0.9.3
Git commit: v0.9.3
Git tree state: clean

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:
kops version
Version 1.10.0 (git-8b52ea6d1)

- Cloud provider or hardware configuration:
aws

- OS (e.g. from `/etc/os-release`):
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Comment by ncdc** [comment]
@suhas184 we do not currently have native support for Gluster volumes. Please see our [support matrix](https://heptio.github.io/ark/v0.9.0/support-matrix) for the list of supported volume snapshot providers.

I do think you should be able to use our [restic integration](https://heptio.github.io/ark/v0.9.0/restic) to back up files in your Gluster volumes, as long as the volumes are not set up in your pods as `hostPath` (we don't support `hostPath` volumes with restic for security reasons).
